obj-$(CONFIG_HI3xxx_CLK_CORE)		+= clk-hi3xxx.o clk-hi3716.o
obj-$(CONFIG_HI3620_CLK_MIPI_DSI)	+= clk-hi3620-dsi.o
obj-$(CONFIG_HI3630_CLK)		+= clk-hi3630.o
obj-$(CONFIG_HI3630_CLK_MAILBOX_SUPPORT)	+= hisi-clk-mailbox.o
