#
# Makefile for the sensors drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o

obj-$(CONFIG_SENSORS_MAX86900)	+= max86900.o
obj-$(CONFIG_SENSORS_TMD3782)	+= tmd3782.o
obj-$(CONFIG_SENSORS_TMD27723)	+= tmd27723.o
obj-$(CONFIG_SENSORS_AK09911C)	+= ak09911c.o
obj-$(CONFIG_SENSORS_GP2A30)	+= gp2ap030.o