
include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mtk-src

obj-y += gt813_driver.o
obj-y += goodix_tool.o
obj-y += gt813tb_utils.o
obj-y += guitar_update.o
