# qindiwen 20120625 begin

# InputHub Driver
obj-$(CONFIG_INPUTHUB)		+= inputhub_bridge.o
obj-$(CONFIG_INPUTHUB)		+= inputhub_route.o
obj-$(CONFIG_INPUTHUB)		+= sensor_info.o
obj-$(CONFIG_INPUTHUB)       += sensorhub_debugfs.o

obj-$(CONFIG_INPUTHUB)	+= sensorhub_channel.o
# DTS2014010800416 ligang/00183889 20140108 begin
obj-$(CONFIG_INPUTHUB)  += motionhub_channel.o
# DTS2014010800416 ligang/00183889 20140108 end
#obj-$(CONFIG_INPUTHUB)	+= touch_events_channel.o

obj-$(CONFIG_INPUTHUB)  += sensor_sys_info.o
# qindiwen 20120625 end
