snd-soc-odin-audio-powclk-objs := odin_aud_powclk.o
snd-odin-hdmi-sample-objs := odin_hdmi_adriver_sample.o
snd-soc-odin-hw-semaphore-objs := hw_semaphore.o
snd-soc-odin-audio-semaphore-module-objs := odin_aud_semaphore.o
snd-soc-odin-utils-objs := odin_asoc_utils.o
snd-soc-woden-pcm-objs := woden_pcm.o
snd-soc-woden-i2s-objs := woden_i2s.o
snd-soc-odin-pcm-objs := odin_pcm.o
snd-soc-odin-pcm-sram-objs := odin_pcm_sram.o ama.o ama_debugfs.o
snd-soc-odin-mi2s-objs := odin_mi2s.o
snd-soc-odin-si2s-objs := odin_si2s.o
snd-soc-odin-alsa-dsp-objs := odin_platform.o
snd-soc-odin-dsp-ext-objs := odin_dsp_ext_driver.o
snd-soc-odin-compress-objs := odin_compress.o

obj-$(CONFIG_SND_SOC_ODIN_AUDIO_POWER_CLOCK) += snd-soc-odin-audio-powclk.o
obj-$(CONFIG_SND_SOC_ODIN_HDMI_ASAMPLE) += snd-odin-hdmi-sample.o
obj-$(CONFIG_SND_SOC_ODIN_HW_SEMAPHORE_DRIVER) += snd-soc-odin-hw-semaphore.o
obj-$(CONFIG_SND_SOC_ODIN_AUDIO_SEMAPHORE_MODULE) += snd-soc-odin-audio-semaphore-module.o
obj-$(CONFIG_SND_SOC_ODIN_UTILS) += snd-soc-odin-utils.o
obj-$(CONFIG_SND_SOC_WODEN) += snd-soc-woden-pcm.o
obj-$(CONFIG_SND_SOC_WODEN_I2S) += snd-soc-woden-i2s.o
obj-$(CONFIG_SND_SOC_ODIN_PCM_DRAM) += snd-soc-odin-pcm.o
obj-$(CONFIG_SND_SOC_ODIN_PCM_SRAM) += snd-soc-odin-pcm-sram.o
obj-$(CONFIG_SND_SOC_ODIN_MI2S) += snd-soc-odin-mi2s.o
obj-$(CONFIG_SND_SOC_ODIN_SI2S) += snd-soc-odin-si2s.o
obj-$(CONFIG_SND_SOC_ODIN_ALSA_DSP) += snd-soc-odin-alsa-dsp.o
obj-$(CONFIG_SND_SOC_ODIN_ALSA_DSP_EXT) += snd-soc-odin-dsp-ext.o
obj-$(CONFIG_SND_SOC_ODIN_COMPR) += dsp/
obj-$(CONFIG_SND_SOC_ODIN_COMPR) += snd-soc-odin-compress.o

snd-soc-woden-wm8580-objs := woden_fpga_wm8580.o
snd-soc-woden-wm5102-objs := woden_hdk_wm5102.o
snd-soc-odin-fpga-wm5102-objs := odin_fpga_wm5102.o
snd-soc-odin-madk-wm5102-objs := odin_madk_wm5102.o
snd-soc-odin-dsp-wm5102-objs := odin_dsp_wm5102.o
snd-soc-odin-rt5671-objs := odin_rt5671.o
# Please keep the hdmi object on the end line.
snd-soc-odin-madk-hdmi-objs := odin_madk_hdmi.o

obj-$(CONFIG_SND_SOC_WODEN_WM8580) += snd-soc-woden-wm8580.o
obj-$(CONFIG_SND_SOC_WODEN_WM5102) += snd-soc-woden-wm5102.o
obj-$(CONFIG_SND_SOC_ODIN_FPGA_WM5102) += snd-soc-odin-fpga-wm5102.o
obj-$(CONFIG_SND_SOC_ODIN_MADK_WM5102) += snd-soc-odin-madk-wm5102.o
obj-$(CONFIG_SND_SOC_ODIN_DSP_WM5102) += snd-soc-odin-dsp-wm5102.o
obj-$(CONFIG_SND_SOC_ODIN_RT5671) += snd-soc-odin-rt5671.o
# Please keep the hdmi object on the end line.
obj-$(CONFIG_SND_SOC_ODIN_MADK_HDMI) += snd-soc-odin-madk-hdmi.o
