#ifndef _KD_CAMERA_HW_H_
#define _KD_CAMERA_HW_H_

#include <mach/mt_pm_ldo.h>

extern void ISP_MCLK1_EN(bool En);	/* MCLK1 for Main/Sub Camera */

#ifndef GPIO_CAMERA_CMMCLK_PIN
#define GPIO_CAMERA_CMMCLK_PIN (GPIO182 | 0x80000000)
#define GPIO_CAMERA_CMMCLK_PIN_M_GPIO   GPIO_MODE_00
#define GPIO_CAMERA_CMMCLK_PIN_M_MCLK   GPIO_MODE_01
#define GPIO_CAMERA_CMMCLK_PIN_M_EINT   GPIO_MODE_02
#endif

/* FIXME, should defined in DCT tool */
/*  */
#ifndef GPIO_CAMERA_LDO_EN_PIN
#define GPIO_CAMERA_LDO_EN_PIN GPIO_CAMERA_INVALID
#endif
/*  */
#ifndef GPIO_CAMERA_CMRST_PIN
#define GPIO_CAMERA_CMRST_PIN GPIO_CAMERA_INVALID
#endif
/*  */
#ifndef GPIO_CAMERA_CMRST_PIN_M_GPIO
#define GPIO_CAMERA_CMRST_PIN_M_GPIO GPIO_MODE_00
#endif
/*  */
#ifndef GPIO_CAMERA_CMPDN_PIN
#define GPIO_CAMERA_CMPDN_PIN GPIO_CAMERA_INVALID
#endif
/*  */
#ifndef GPIO_CAMERA_LDO_EN_PIN_M_GPIO
#define GPIO_CAMERA_LDO_EN_PIN_M_GPIO GPIO_MODE_00
#endif
/*  */
#ifndef GPIO_CAMERA_CMPDN_PIN_M_GPIO
#define GPIO_CAMERA_CMPDN_PIN_M_GPIO  GPIO_MODE_00
#endif
/*  */
#ifndef GPIO_CAMERA_CMRST1_PIN
#define GPIO_CAMERA_CMRST1_PIN GPIO_CAMERA_INVALID
#endif
/*  */
#ifndef GPIO_CAMERA_CMRST1_PIN_M_GPIO
#define GPIO_CAMERA_CMRST1_PIN_M_GPIO GPIO_MODE_00
#endif
/*  */
#ifndef GPIO_CAMERA_CMPDN1_PIN
#define GPIO_CAMERA_CMPDN1_PIN GPIO_CAMERA_INVALID
#endif
/*  */
#ifndef GPIO_CAMERA_CMPDN1_PIN_M_GPIO
#define GPIO_CAMERA_CMPDN1_PIN_M_GPIO GPIO_MODE_00
#endif

#ifndef GPIO_CAMERA_2_CMRST_PIN
#define GPIO_CAMERA_2_CMRST_PIN GPIO_CAMERA_INVALID	/* shared by KPD_COL1 */
#endif
/*  */
#ifndef GPIO_CAMERA_2_CMRST_PIN_M_GPIO
#define GPIO_CAMERA_2_CMRST_PIN_M_GPIO GPIO_MODE_00
#endif
/*  */
#ifndef GPIO_CAMERA_2_CMPDN_PIN
#define GPIO_CAMERA_2_CMPDN_PIN GPIO_CAMERA_INVALID	/* shared by KPD_COL2 */
#endif
/*  */
#ifndef GPIO_CAMERA_2_CMPDN_PIN_M_GPIO
#define GPIO_CAMERA_2_CMPDN_PIN_M_GPIO GPIO_MODE_00
#endif

#ifndef GPIO_CAMERA_2_CMMCLK_PIN_M_GPIO
#define GPIO_CAMERA_2_CMMCLK_PIN_M_GPIO GPIO_MODE_00
#endif

#ifndef GPIO_CAMERA_2_CMMCLK_PIN
#define GPIO_CAMERA_2_CMMCLK_PIN GPIO_CAMERA_INVALID	/* shared by KPD_COL2 */
#endif


/* i2c id for sensor device, MT8320_fpga, the I2C is attached on 1 */
#define IMG_SENSOR_I2C_GROUP_ID 0



#endif
