ifeq ($(MET_TOP),)
	obj-$(CONFIG_MTK_MET_PLF) := met_plf.o
else
	obj-m := met_plf.o
endif

MALI_DDK_DIR := $(srctree)/mediatek/platform/mt6752/kernel/drivers/gpu/mali
KBASE_DIR = $(MALI_DDK_DIR)/drivers/gpu/arm/midgard
EXTRA_CFLAGS += -DMALI_SUPPORT=MALI_T6xx \
		-DMALI_DIR_MIDGARD=1 \
		-DMALI_DDK_GATOR_API_VERSION=2 \
		-DMALI_CUSTOMER_RELEASE=1 \
		-DMALI_UNIT_TEST=0 \
		-DGATOR_TEST=0 \

EXTRA_CFLAGS += -I$(KBASE_DIR)/ \
                -I$(MALI_DDK_DIR)/include \
		-I$(srctree)/drivers/staging/android	# mali sync.h issue

ccflags-y += $(EXTRA_ARGS) $(EXTRA_CFLAGS)

met_plf-y := plf_init.o \
	plf_trace.o \
	emi.o mt_emi_bm.o \
	smi.o mt_smi.o \
	cci400_pmu.o cci400_pmu_hw.o \
	thermal.o \
	pmic.o \
	mt_gpu_metmonitor.o \
	ptpod.o \
	spm_twam.o \
	gator/gator_events_mali_common.o \
	met_gator.o \
	met_mali.o
