#define JL_POWERKEY_PRESS                                  "JLOG0"
#define JL_USBCHARGING_START                               "JLOG1"
#define JL_USBCHARGE_DONE                                  "JLOG2"
#define JL_NEWRINGING_CONNECTION                           "JLOG3"
#define JL_INCOMINGCALL_RINGING                            "JLOG4"
#define JL_PMS_WAKEFULNESS_ASLEEP                          "JLOG5"
#define JL_PMS_WAKEFULNESS_DREAMING                        "JLOG6"
#define JL_PMS_WAKEFULNESS_NAPPING                         "JLOG7"
#define JL_PMS_WAKEUP_FINISHED                             "JLOG8"
#define JL_POWERKEY_RELEASE                                "JLOG9"
#define JL_KERNEL_LCD_OPEN                                 "JLOG10"
#define JL_KERNEL_LCD_SUSPEND                              "JLOG11"
#define JL_KERNEL_LCD_POWER_ON                             "JLOG12"
#define JL_KERNEL_LCD_POWER_OFF                            "JLOG13"
#define JL_KERNEL_PM_SUSPEND_WAKEUP                        "JLOG14"
#define JL_GO_TO_SLEEP_REASON_USER                         "JLOG15"
#define JL_KERNEL_PM_SUSPEND_SLEEP                         "JLOG16"
#define JL_KERNEL_PM_DEEPSLEEP_WAKEUP                      "JLOG17"
#define JL_KERNEL_LCD_RESUME                               "JLOG18"
#define JL_SYSPROC_INIT_POWERON_START                      "JLOG19"
#define JL_SYSPROC_INIT_POWERON_END                        "JLOG20"
#define JL_SERVICEMANAGER_POWERON_START                    "JLOG21"
#define JL_SERVICEMANAGER_STARTUP                          "JLOG22"
#define JL_START_SYSTEMSERVER                              "JLOG23"
#define JL_LAUNCHER_STARTUP                                "JLOG24"
#define JL_ZYGOTE_START                                    "JLOG25"
#define JL_BOOT_PROGRESS_PRELOAD_START                     "JLOG26"
#define JL_BOOT_PROGRESS_PRELOAD_END                       "JLOG27"
#define JL_BOOT_PROGRESS_SYSTEM_RUN                        "JLOG28"
#define JL_BOOT_PROGRESS_PMS_START                         "JLOG29"
#define JL_BOOT_PROGRESS_PMS_SYSTEM_SCAN_START             "JLOG30"
#define JL_BOOT_PROGRESS_PMS_DATA_SCAN_START               "JLOG31"
#define JL_BOOT_PROGRESS_PMS_SCAN_END                      "JLOG32"
#define JL_BOOT_PROGRESS_PMS_READY                         "JLOG33"
#define JL_BOOT_PROGRESS_AMS_READY                         "JLOG34"
#define JL_BOOT_PROGRESS_ENABLE_SCREEN                     "JLOG35"
#define JL_PROXIMITY_SENSOR_CLOSE                          "JLOG36"
#define JL_PROXIMITY_SENSOR_OPEN                           "JLOG37"

#define JLOG0         0
#define JLOG1         1
#define JLOG2         2
#define JLOG3         3
#define JLOG4         4
#define JLOG5         5
#define JLOG6         6
#define JLOG7         7
#define JLOG8         8
#define JLOG9         9
#define JLOG10        10
#define JLOG11        11
#define JLOG12        12
#define JLOG13        13
#define JLOG14        14
#define JLOG15        15
#define JLOG16        16
#define JLOG17        17
#define JLOG18        18
#define JLOG19        19
#define JLOG20        20
#define JLOG21        21
#define JLOG22        22
#define JLOG23        23
#define JLOG24        24
#define JLOG25        25
#define JLOG26        26
#define JLOG27        27
#define JLOG28        28
#define JLOG29        29
#define JLOG30        30
#define JLOG31        31
#define JLOG32        32
#define JLOG33        33
#define JLOG34        34
#define JLOG35        35
#define JLOG36        36
#define JLOG37        37
