/*
 * SIC LABORATORY, LG ELECTRONICS INC., SEOUL, KOREA
 * Copyright(c) 2013 by LG Electronics Inc.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#include <asm/ioctl.h>

#define DSP_IOC_MAGIC   'A'


#define	DSP_IO_INIT_MODULE		_IO(DSP_IOC_MAGIC,0)
#define	DSP_IOW_OPEN			_IOW(DSP_IOC_MAGIC,1,AUDIO_INFO)
#define	DSP_IO_INIT				_IO(DSP_IOC_MAGIC, 2)
#define	DSP_IOW_DECODE_READY	_IOW(DSP_IOC_MAGIC,3,DSP_BUFFER)
#define	DSP_IO_DECODE			_IO(DSP_IOC_MAGIC,4)
#define	DSP_IOR_DECODING_INFO	_IOR(DSP_IOC_MAGIC,5, DSP_BUFFER)
#define	DSP_IOR_PCM_BUFFER		_IOR(DSP_IOC_MAGIC,6, unsigned char)
#define DSP_IOR_GET_INPUT_BUFFER1	_IOR(DSP_IOC_MAGIC,7, DSP_BUFFER)
#define DSP_IOR_GET_INPUT_BUFFER2	_IOR(DSP_IOC_MAGIC,8, DSP_BUFFER)
#define DSP_IOR_GET_OUTPUT_BUFFER1	_IOR(DSP_IOC_MAGIC,9, DSP_BUFFER)
#define DSP_IOR_GET_OUTPUT_BUFFER2	_IOR(DSP_IOC_MAGIC,10, DSP_BUFFER)

#define DSP_IOW_FIRMWARE_DOWNLOAD_DATA  _IOW(DSP_IOC_MAGIC,11, DSP_BUFFER)
#define DSP_IOW_FIRMWARE_DOWNLOAD_INST  _IOW(DSP_IOC_MAGIC,12, DSP_BUFFER)
#define DSP_IOW_GET_AUDIO_INFOMATION    _IOW(DSP_IOC_MAGIC,13, AUDIO_INFO)


/* COMMON */
#define DSP_IO_POWER_ON             _IO(DSP_IOC_MAGIC,10)
#define DSP_IOW_FIRMWARE_DOWNLOAD_DATA  _IOW(DSP_IOC_MAGIC,11, DSP_BUFFER)
#define DSP_IOW_FIRMWARE_DOWNLOAD_INST  _IOW(DSP_IOC_MAGIC,12, DSP_BUFFER)

/* FOR ALSA */
#define DSP_ALSA_PCM_WRITE          _IOW(DSP_IOC_MAGIC,40,BUFFER_INFO)
#define DSP_ALSA_IO_READY          _IO(DSP_IOC_MAGIC,41)

/* FOR LPA */
#define DSP_LPA_IO_READY     _IO(DSP_IOC_MAGIC,50)
#define DSP_LPA_IOW_INIT     _IOW(DSP_IOC_MAGIC,51,AUDIO_INFO)
#define DSP_LPA_IO_START     _IO(DSP_IOC_MAGIC,52)
#define DSP_LPA_IOW_PLAY     _IOW(DSP_IOC_MAGIC,53, BUFFER_INFO)
#define DSP_LPA_IOR_BUFFER_NUMBER_INFO      _IOR(DSP_IOC_MAGIC,54, int)
#define DSP_LPA_IO_FLUSH        _IO(DSP_IOC_MAGIC,55)
#define DSP_LPA_IO_SEEK     _IO(DSP_IOC_MAGIC,56)
#define DSP_LPA_IO_PAUSE        _IO(DSP_IOC_MAGIC,57)
#define DSP_LPA_IO_RESUME   _IO(DSP_IOC_MAGIC,58)
#define DSP_LPA_IO_MUTE   _IO(DSP_IOC_MAGIC,59)
#define DSP_LPA_IO_UNMUTE   _IO(DSP_IOC_MAGIC,60)
#define DSP_LPA_IO_STOP   _IO(DSP_IOC_MAGIC,61)
#define DSP_LPA_IO_CLOSE   _IO(DSP_IOC_MAGIC,62)
#define DSP_LPA_IO_DELETE   _IO(DSP_IOC_MAGIC,63)
#define DSP_LPA_IOW_VOLUME      _IOW(DSP_IOC_MAGIC,64, int)

#define DSP_LPA_IOR_GETTIMESTAMP    _IOR(DSP_IOC_MAGIC,70, long long)
#define DSP_LPA_IOR_GETAUDIOINFO    _IOR(DSP_IOC_MAGIC,71, AUDIO_INFO)


