obj-$(CONFIG_WODEN_DSP) += woden/
obj-$(CONFIG_ODIN_DSP) += odin/
obj-y += mailbox/
obj-y += dsp_drv.o 
obj-y += dsp_cfg.o 
obj-y += dsp_omx_drv.o
obj-y += dsp_lpa_drv.o
obj-y += dsp_pcm_drv.o
obj-y += dsp_alsa_drv.o

#subdir-ccflags-$(CONFIG_ODIN_DSP) += -DWITH_BINARY
