#
#  makefile for tspdrv kernel module
#

obj-$(CONFIG_VIBETONZ) += vibrator.o
obj-$(CONFIG_MOTOR_DRV_MAX77828)	+= max77828_haptic.o
obj-$(CONFIG_MOTOR_DRV_MAX77843)	+= max77843_haptic.o
obj-$(CONFIG_MOTOR_DRV_MAX77804K)	+= max77804k_haptic.o
vibrator-objs +=tspdrv.o
