#=============================================================================
#  w62358 DTS2011072902818 hardware self adapter
#  m00182086 DTS2011103102253 sync TI sensor driver
#  hkf20596  DTS2011092500027 platform gpio unite
#  l00186656 DTS2011120701242 unification scheme of regulators
#=============================================================================

#w62358 DTS2011072902818 begin
#obj-y += hsad/
#w62358 DTS2011072902818 end

#m00182086 DTS2011103102253 begin
#m00182086 DTS2011103102253 end
obj-$(CONFIG_INPUTHUB) += inputhub/
obj-$(CONFIG_LOGGER_EXTEND) += log/
obj-$(CONFIG_BCMGPS) += gps/
obj-$(CONFIG_HUAWEI_TS) += touchscreen/
obj-$(CONFIG_BCMDHD) += wifi/
obj-y += nfc/
obj-$(CONFIG_HUAWEI_TP_COLOR_INFO) += tp_color/
obj-y += sensor/
obj-$(CONFIG_MAXQ616_POWER_SWITCH) += irda/
obj-$(CONFIG_HUAWEI_KSTATE) += hw_kstate/
obj-$(CONFIG_HUAWEI_DSM) += dsm/
obj-y += ext_modem/
