ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
obj-$(CONFIG_LG_OIS) += msm_ois.o msm_ois_i2c.o
obj-$(CONFIG_IMX214) += lgit_imx214_ois.o
obj-$(CONFIG_IMX234) += lgit_imx234_ois.o
obj-$(CONFIG_IMX135) += lgit_imx135_ois.o