#
# Makefile for mxs specific clk
#
obj-$(CONFIG_WODEN_HDK)				+= clk-woden-dt.o
obj-$(CONFIG_ARCH_ODIN)				+= clk-odin.o
obj-y 								+= clk-ljpll.o
obj-y					 			+= clk-apll.o
obj-y					 			+= clk-module.o
obj-y					 			+= clk-div.o
obj-y					 			+= clk-gate.o
obj-y					 			+= clk-mux.o
obj-y					 			+= clk-comm.o
