#ifndef __MACH_QFPROM_ADDR_8994_H__
#define __MACH_QFPROM_ADDR_8994_H__

#define SEC_PATH "/dev/block/platform/f9824900.sdhci/by-name/sec"
/* QFPROM address to blow */
#define QFPROM_CTRL_BASE            (0xfc4b8000)

#define QFPROM_RD_WR_PERM	    (QFPROM_CTRL_BASE + 0x00A8) /* 0xFC4B80A8 ok */

#define QFPROM_DBG_DISABLE        (QFPROM_CTRL_BASE + 0x00E8) /* 0xFC4B80E8 ok */
#define QFPROM_OEM_CONFIG           (QFPROM_CTRL_BASE + 0x00F0) /* 0xFC4B80F0 ok */

#define QFPROM_SPARE_REG19          (QFPROM_CTRL_BASE + 0x01F8) /* 0xFC4B81F8 ok */
#define QFPROM_FEC_EN               (QFPROM_CTRL_BASE + 0x01D0) /* 0xFC4B81D0 ok */

#define QFPROM_SEC_HW_KEY           (QFPROM_CTRL_BASE + 0x03A8) /* 0xFC4B83A8 ok */
#define QFPROM_SEC_HW_KEY_1         (QFPROM_CTRL_BASE + 0x03B0) /* 0xFC4B83B0 ok */
#define QFPROM_SEC_HW_KEY_2         (QFPROM_CTRL_BASE + 0x03B8) /* 0xFC4B83B8 ok */
#define QFPROM_SEC_HW_KEY_3         (QFPROM_CTRL_BASE + 0x03C0) /* 0xFC4B83C0 ok */
#define QFPROM_SEC_HW_KEY_4         (QFPROM_CTRL_BASE + 0x03C8) /* 0xFC4B83C8 ok */

#define QFPROM_OEM_PK_HASH          (QFPROM_CTRL_BASE + 0x03D0) /* 0xFC4B83D0 ok */
//#define QFPROM_OEM_PK_HASH_1        (QFPROM_CTRL_BASE + 0x03D8) /* 0xFC4B83D0 ok */
//#define QFPROM_OEM_PK_HASH_2        (QFPROM_CTRL_BASE + 0x03E0) /* 0xFC4B83D0 ok */
//#define QFPROM_OEM_PK_HASH_3        (QFPROM_CTRL_BASE + 0x03E8) /* 0xFC4B83D0 ok */
//#define QFPROM_OEM_PK_HASH_4        (QFPROM_CTRL_BASE + 0x03F0) /* 0xFC4B83D0 ok */

#define QFPROM_SEC_ENABLE           (QFPROM_CTRL_BASE + 0x03F8) /* 0xFC4B83F8 ok */

#define QFPROM_HW_KEY_STATUS        (QFPROM_CTRL_BASE + 0x204C) /* 0xFC4BA04C */

typedef enum {
  QFPROM_RESULT_OEM_CONFIG  = 0,
  QFPROM_RESULT_SEC_ENABLE  = 1,
  QFPROM_RESULT_DBG_DISABLE = 2,
  QFPROM_RESULT_SEC_HW_KEY  = 3,
  QFPROM_RESULT_RD_WR_PERM  = 4,
  QFPROM_RESULT_PRODUCT_ID  = 5,
  QFPROM_RESULT_FEC_EN      = 6,
  QFPROM_RESULT_OEM_PK_HASH = 7,
  QFPROM_RESULT_MAX
} qfprom_result_etype;

typedef struct {
  u32 type;
  u32 addr;
  u32 lsb;
  u32 msb;
} qfprom_result_bits;

qfprom_result_bits result_bits[QFPROM_RESULT_MAX] = {
  {QFPROM_RESULT_OEM_CONFIG,  QFPROM_OEM_CONFIG,    0xFFFFFFFF, 0x00000000},
  {QFPROM_RESULT_SEC_ENABLE,  QFPROM_SEC_ENABLE,    0x00FFFFFF, 0xFF000000},
  {QFPROM_RESULT_DBG_DISABLE, QFPROM_DBG_DISABLE,   0xFFFFFFFF, 0xFFFFFFFF},
  {QFPROM_RESULT_SEC_HW_KEY,  QFPROM_SEC_HW_KEY,    0xFFFFFFFF, 0xFFFFFFFF},
  {QFPROM_RESULT_RD_WR_PERM,  QFPROM_RD_WR_PERM,    0xFFFF0000, 0xFFFFFFFF},
  {QFPROM_RESULT_PRODUCT_ID,  QFPROM_OEM_CONFIG,    0x00000000, 0x0000FFFF},
  {QFPROM_RESULT_FEC_EN,      QFPROM_FEC_EN,        0xFFFFFFFF, 0x00000000},
  {QFPROM_RESULT_OEM_PK_HASH, QFPROM_OEM_PK_HASH,   0xFFFFFFFF, 0xFFFFFFFF},
};

/* secondary hw key status flag */
#define SEC_KEY_DERIVATION_BLOWN    (0x00000002)

#endif // __MACH_QFPROM_ADDR_8994_H__

