# hifi dsp device driver

obj-$(CONFIG_SND_HIFI_LPP)	+= hifi_lpp.o
obj-$(CONFIG_SND_HIFI_LOAD)	+= hifi_loader.o
obj-$(CONFIG_SND_HIFI_SEC_LOAD) += hifi_sec_loader.o
EXTRA_CFLAGS += -Idrivers/hisi/mailbox
EXTRA_CFLAGS += -Idrivers/hisi/ipcm
EXTRA_CFLAGS += -I../vendor/hisi/include/drv/

