obj-y += audio.o audioParams.o control.o halAudioClock.o halAudioDma.o halAudioGenerator.o halAudioGpa.o halAudioHbr.o halAudioI2s.o
obj-y += halAudioSpdif.o halColorSpaceConverter.o halFrameComposerAcp.o halFrameComposerAudio.o halFrameComposerAudioInfo.o halFrameComposerAvi.o
obj-y += halFrameComposerDebug.o halFrameComposerGamut.o halFrameComposerGcp.o halFrameComposerIsrc.o halFrameComposerPackets.o
obj-y += halFrameComposerSpd.o halFrameComposerVideo.o halFrameComposerVsd.o halIdentification.o halInterrupt.o halMainController.o
obj-y += halVideoGenerator.o halVideoPacketizer.o halVideoSampler.o packets.o productParams.o video.o videoParams.o