/*
 * Generated by MTK SP DrvGen Version 03.13.0 for MT8135_NP. Copyright MediaTek Inc. (C) 2013.
 * Fri Oct 11 14:10:18 2013
 * Do Not Modify the File.
 */

#define MSDC_POWER_MC1     MSDC_VEMC_3V3
#define MSDC_POWER_MC2     MSDC_VMC
