# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_SWITCH_USB_CLS)	+= switch_usb_class.o
obj-$(CONFIG_SWITCH_FSA9685)	+= switch_fsa9685.o
