# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_SWITCH_FSUSB104UMX)	+= usb_switch_class.o
obj-$(CONFIG_SWITCH_FSUSB104UMX)	+= usb_switch_gpio.o
obj-$(CONFIG_INPUT_MAX14688)	+= hds_max14688.o
