obj-y += hal/
obj-y += panel/

obj-y += dip_mipi.o
obj-y += dss_buf.o
obj-y += dss_comp.o
obj-y += dss_drv.o
obj-y += dss_fb.o
obj-y += dss_irq.o
obj-y += du_ovl_drv.o
obj-y += du_rsc.o
obj-y += mipi_dsi_drv.o
obj-y += rot_rsc_drv.o
obj-y += sync_src.o
obj-y += ovl_rsc.o

ccflags-y += -I$(srctree)/drivers/media/platform/odin-vcodec/misc/vevent/
