/*
              
                                                   
                                 
*/

#ifndef __LCD_PANEL_LGLH600WF2_H
#define __LCD_PANEL_LGLH600WF2_H

/* # Video Mode Porch Setting (VBP, VFP, HBP, HFP) */
static char vmps[6] = {
	0x3B,
	0x03, 0x0A, 0x0A, 0x0A, 0x0A
};

/* # Tearing timming */
static char te_timing[3] = {
	0x44,
#if 0
	0x07, 0x62,	/* 1890 line */
#else
	0x01, 0x33,	/* 307 line (2.66ms delay) */
#endif
};

static struct odin_dsi_cmd lglh600wf2_dsi_on_command[] = {
/*---------------------------------------------------------------------------*/
/* Display initial setting                                                   */
/*---------------------------------------------------------------------------*/


	/* # CMD2 Page 4 */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xFF, 0x24),
	DSI_DLY_MS(2),

	/* # CGOUT */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x00, 0x0F),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x01, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x02, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x03, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x04, 0x0B),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x05, 0x0C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x06, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x07, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x08, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x09, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0A, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0B, 0x04),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0C, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0D, 0x13),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0E, 0x15),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0F, 0x17),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x10, 0x0F),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x11, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x12, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x13, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x14, 0x0B),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x15, 0x0C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x16, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x17, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x18, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x19, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1A, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1B, 0x04),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1C, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1D, 0x13),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1E, 0x15),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1F, 0x17),

	/* # LGD Driving method */
	/* Start Pulse related (GVST) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x20, 0x05),
	/* STV_RISE_SEL */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x21, 0x01),
	/* STV_FALL_SEL */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x22, 0x00),
	/* FS_REG */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x23, 0x00),
	/* FW_REG */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x24, 0x00),
    /* GVST setting for power-on sequence (pls. set to 0x6D) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x25, 0x6D),
	/*FS_REG_V */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x26, 0x00),
	/* FS_REG_V */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x27, 0x00),

	/* # GCK(GCLK1/GCLK2), GCLK Setting */
	/* GCK(GCLK1/GCLK2) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x2F, 0x02),
	/* Set H/L toogle line numbers of each GCK and GCK toogle seq-number */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x30, 0x04),
	/* Set GCK Sequence in Forward/Backward scan */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x31, 0x49),
	/* Set GCK Sequence in Forward/Backward scan */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x32, 0x23),
	/* STI_REG/SWI_REG/STI_REG_V/SWI_REG_V/GCK_VPM */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x33, 0x01),
	/* STI_REG */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x34, 0x00),
	/* SWI_REG */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x35, 0x69),
	/* GCK power-on/off sequence setting */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x36, 0x00),
	/* GCK power-on/off sequence setting */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x37, 0x2D),
	/* GCK power-on/off sequence setting */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x38, 0x08),
	/* STI_REG_V */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x39, 0x00),
	/* SWI_REG_V */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x3A, 0x69),

	/* # UD (U2D/D2U), U2D,D2U */
	/* UD(U2D, D2U) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x29, 0x58),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x2A, 0x16),

	/* # CTRL (APO, use CTRL1), APO */
	/* CTRL (SPO, use CTRL1) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5B, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5F, 0x75),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x63, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x67, 0x04),

	/* # MUX (SERx/xSELx) */
#if 0
	/* MUX(SERx/xSELx)*/
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7A, 0x19),
#endif
	/* MUX sequence setting in Display Line */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7B, 0x80),
	/* MUX power-on/off sequencesetting */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7C, 0xD8),
	/* MUX power-on/off sequencesetting */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7D, 0x60),
	/* MUXS */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7E, 0x10),
	/* MUXW */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7F, 0x19),
	/* SD_SHIFT_POS (MUX Rising EQ) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x80, 0x00),
	/* MUXG1 */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x81, 0x06),
	/* MUXG2 */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x82, 0x03),
	/* EQT_POS (Source Rising EQ) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x83, 0x00),
	/* SOEHT (Source OP enable Time) MUXG1+MUXG2-SOEHT>=4 */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x84, 0x03),
	/* SDT_REG (Source Output Hold Time) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x85, 0x07),
	/* MUXS_V (MUX Rising Portion) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x74, 0x10),
	/* MUXW_V (MUX On Time) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x75, 0x19),
	/* MUXG1_V (MUX non-overlap Time) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x76, 0x06),
	/* MUXG2_V (MUX non-overlap Time / b wo RGB switch) */

	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x77, 0x03),
	/* # Source Control */
	/* SD_SHIFT_NEG (MUX Falling EQ) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x78, 0x00),
	/* EQ_NEG (Source Falling EQ) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x79, 0x00),
	/* PTA/SPDUMA */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x99, 0x33),
#if 0
	/* PTB/SPDUMB */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA0, 0x33),
#endif
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x98, 0x00),

	/*  LTPS Abnormal PWROFF Ctrl. */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB3, 0x28),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB4, 0x05),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB5, 0x10),

	/* # SRGB/SMX_REG/CTB/CRL */
#if 0
	/* FWD */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9D, 0xB0),
#endif
	/* BWD */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9D, 0xB6),

	/* # BP/FP Setting for Command Mode (BP=4, FP=4) */
	/* FP */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x93, 0x04),
	/* PP */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x94, 0x04),

	/* # Set Inversion Type (Pixel Column) */
	/* Inversion (Column) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9B, 0x0F),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8A, 0x33),

	/* # Less Transition Function Setting */
	/*  Alternation */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x86, 0x1B),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x87, 0x39),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x88, 0x1B),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x89, 0x39),
	/* MUX_LTF (Less Transition) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8B, 0xF4),
	/* Alternation */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8C, 0x01),

	/* # RTN Setting */
	/* RTNA_V */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x90, 0x79),
	/* DIVB/RTNA_V/DIVA/RTNB/RTNA2/RTNA */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x91, 0x44),
	/* RTNA */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x92, 0x79),

	/* # CTRL PIN */
	/* FTE_SEL/FTE1_SEL */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC4, 0x24),
	/* LEDPWM_SEL/VSOUT_SEL */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC5, 0x30),
	/* HSOUT_SEL */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC6, 0x00),

	/* #Resolution Setting */
	/* V_RES, H_RES */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x72, 0x00),

	/* #CMD2 Page 0 */
	/* Page 0, power-related setting */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xFF, 0x20),
	DSI_DLY_MS(2),

	/* # A */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x00, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x01, 0x55),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x02, 0x45),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x03, 0x55),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x05, 0x50),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x06, 0x9E),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x07, 0xA8),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x08, 0x0C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0B, 0x91),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0C, 0x91),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0E, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0F, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x11, 0x2E),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x12, 0x2E),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x13, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x14, 0x0A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x15, 0x94),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x16, 0x94),

	/*# PWM Control */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1B, 0x39),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1C, 0x39),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1D, 0x47),

	/* # Gate EQ Control */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x58, 0x05),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x59, 0x05),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5A, 0x05),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5B, 0x05),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5C, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5D, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5E, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5F, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x6D, 0x44),

	/* # CMD2 Page 0 */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xFF, 0x20),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xFB, 0x01),

	/* # R+ */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x75, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x76, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x77, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x78, 0x32),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x79, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7A, 0x60),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7B, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7C, 0x80),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7D, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7E, 0x95),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7F, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x80, 0xAF),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x81, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x82, 0xC4),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x83, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x84, 0xD2),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x85, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x86, 0xE0),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x87, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x88, 0x0C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x89, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8A, 0x2F),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8B, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8C, 0x64),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8D, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8E, 0x92),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8F, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x90, 0xD9),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x91, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x92, 0x14),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x93, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x94, 0x15),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x95, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x96, 0x4A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x97, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x98, 0x88),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x99, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9A, 0xB2),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9B, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9C, 0xEC),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9D, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9E, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9F, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA0, 0x28),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA2, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA3, 0x37),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA4, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA5, 0x47),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA6, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA7, 0x5a),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA9, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xAA, 0x6B),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xAB, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xAC, 0x7C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xAD, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xAE, 0xD9),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xAF, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB0, 0xF5),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB1, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB2, 0xFF),

	/* # R- */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB3, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB4, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB5, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB6, 0x32),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB7, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB8, 0x60),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB9, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xBA, 0x80),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xBB, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xBC, 0x95),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xBD, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xBE, 0xAF),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xBF, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC0, 0xC4),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC1, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC2, 0xD2),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC3, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC4, 0xE0),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC5, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC6, 0x0C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC7, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC8, 0x2F),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC9, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xCA, 0x64),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xCB, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xCC, 0x92),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xCD, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xCE, 0xD9),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xCF, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD0, 0x14),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD1, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD2, 0x15),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD3, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD4, 0x4A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD5, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD6, 0x88),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD7, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD8, 0xB2),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD9, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xDA, 0xEC),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xDB, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xDC, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xDD, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xDE, 0x28),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xDF, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE0, 0x37),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE1, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE2, 0x47),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE3, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE4, 0x5a),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE5, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE6, 0x6B),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE7, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE8, 0x7C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE9, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xEA, 0xD9),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xEB, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xEC, 0xF5),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xED, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xEE, 0xFF),

	/* # G+ */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xEF, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xF0, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xF1, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xF2, 0x32),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xF3, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xF4, 0x60),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xF5, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xF6, 0x80),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xF7, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xF8, 0x95),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xF9, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xFA, 0xAF),

	/* #CMD2 Page 0 */
	/* Page 0, power-related setting */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xFF, 0x21),
	DSI_DLY_MS(2),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xFB, 0x01),
	DSI_DLY_MS(2),

	/* #no name 0 */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x00, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x01, 0xC4),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x02, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x03, 0xD2),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x04, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x05, 0xE0),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x06, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x07, 0x0B),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x08, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x09, 0x2E),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0A, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0B, 0x63),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0C, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0D, 0x91),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0E, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0F, 0xD9),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x10, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x11, 0x14),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x12, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x13, 0x15),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x14, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x15, 0x4A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x16, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x17, 0x88),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x18, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x19, 0xB2),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1A, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1B, 0xEC),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1C, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1D, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1E, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1F, 0x28),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x20, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x21, 0x37),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x22, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x23, 0x47),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x24, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x25, 0x5a),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x26, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x27, 0x6B),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x28, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x29, 0x7C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x2A, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x2B, 0xD9),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x2D, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x2F, 0xF5),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x30, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x31, 0xFF),

	/* # G- */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x32, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x33, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x34, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x35, 0x32),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x36, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x37, 0x60),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x38, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x39, 0x80),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x3A, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x3B, 0x95),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x3D, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x3F, 0xAF),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x40, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x41, 0xC4),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x42, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x43, 0xD2),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x44, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x45, 0xE0),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x46, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x47, 0x0B),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x48, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x49, 0x2E),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x4A, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x4B, 0x63),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x4C, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x4D, 0x91),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x4E, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x4F, 0xD9),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x50, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x51, 0x14),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x52, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x53, 0x15),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x54, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x55, 0x4A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x56, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x58, 0x88),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x59, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5A, 0xB2),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5B, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5C, 0xEC),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5D, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5E, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5F, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x60, 0x28),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x61, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x62, 0x37),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x63, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x64, 0x47),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x65, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x66, 0x5a),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x67, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x68, 0x6B),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x69, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x6A, 0x7C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x6B, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x6C, 0xD9),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x6D, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x6E, 0xF5),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x6F, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x70, 0xFF),

	/* # B+ */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x71, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x72, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x73, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x74, 0x27),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x75, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x76, 0x4E),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x77, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x78, 0x76),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x79, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7A, 0x95),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7B, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7C, 0xAF),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7D, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7E, 0xC1),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7F, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x80, 0xCA),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x81, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x82, 0xDB),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x83, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x84, 0x04),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x85, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x86, 0x24),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x87, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x88, 0x5E),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x89, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8A, 0x8A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8B, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8C, 0xD0),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8D, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8E, 0x0A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x8F, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x90, 0x0C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x91, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x92, 0x41),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x93, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x94, 0x80),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x95, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x96, 0xAB),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x97, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x98, 0xE9),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x99, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9A, 0x05),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9B, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9C, 0x28),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9D, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9E, 0x37),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x9F, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA0, 0x47),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA2, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA3, 0x5a),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA4, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA5, 0x6B),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA6, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA7, 0x7C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xA9, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xAA, 0xD9),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xAB, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xAC, 0xF5),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xAD, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xAE, 0xFF),

	/* # B- */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xAF, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB0, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB1, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB2, 0x27),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB3, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB4, 0x4E),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB5, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB6, 0x76),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB7, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB8, 0x95),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xB9, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xBA, 0xAF),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xBB, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xBC, 0xC1),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xBD, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xBE, 0xCA),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xBF, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC0, 0xDB),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC1, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC2, 0x04),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC3, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC4, 0x24),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC5, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC6, 0x5E),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC7, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC8, 0x8A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xC9, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xCA, 0xD0),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xCB, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xCC, 0x0A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xCD, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xCE, 0x0C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xCF, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD0, 0x41),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD1, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD2, 0x80),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD3, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD4, 0xAB),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD5, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD6, 0xE9),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD7, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD8, 0x05),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xD9, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xDA, 0x28),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xDB, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xDC, 0x37),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xDD, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xDE, 0x47),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xDF, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE0, 0x5a),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE1, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE2, 0x6B),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE3, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE4, 0x7C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE5, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE6, 0xD9),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE7, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE8, 0xF5),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xE9, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xEA, 0xFF),

	/* CMD2 Page 2 */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xFF, 0x22),
	DSI_DLY_MS(2),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xFB, 0x01),
	DSI_DLY_MS(2),

	/* IE Enhance */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xFB, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x00, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x01, 0x04),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x02, 0x08),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x03, 0x0C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x04, 0x10),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x05, 0x14),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x06, 0x18),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x07, 0x20),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x08, 0x24),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x09, 0x28),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0A, 0x30),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0B, 0x38),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0C, 0x38),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0D, 0x30),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0E, 0x28),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x0F, 0x20),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x10, 0x0C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x11, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x12, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x13, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x14, 0x10),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x15, 0x18),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x16, 0x30),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x17, 0x18),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x18, 0x28),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x19, 0x38),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1A, 0x77),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1B, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1C, 0x04),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1D, 0x08),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1E, 0x0C),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x1F, 0x10),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x20, 0x14),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x21, 0x18),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x22, 0x20),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x23, 0x18),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x24, 0x10),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x25, 0x08),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x26, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x27, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x28, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x29, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x2A, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x2B, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x2F, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x30, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x31, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x32, 0x0A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x33, 0x0F),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x34, 0x0A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x35, 0x0A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x36, 0x07),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x37, 0x07),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x38, 0x07),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x39, 0x07),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x3A, 0x07),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x3B, 0x07),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x3F, 0x07),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x40, 0x07),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x41, 0x07),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x42, 0x07),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x43, 0x14),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x44, 0x14),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x45, 0x14),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x46, 0x14),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x47, 0x0A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x48, 0x0A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x49, 0x0A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x4A, 0x0A),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x4B, 0x05),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x4C, 0x05),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x4D, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x4E, 0x04),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x4F, 0x04),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x50, 0x01),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x51, 0x03),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x52, 0x05),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x53, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x54, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x55, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x56, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x58, 0x12),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x59, 0x0E),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5A, 0x0F),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5B, 0x0E),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5C, 0x16),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5D, 0x0E),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5E, 0x14),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5F, 0x12),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x60, 0x16),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x61, 0x12),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x62, 0x18),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x63, 0x12),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x64, 0x2F),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x65, 0x82),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x66, 0xA4),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x67, 0xC8),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x68, 0x77),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x69, 0x02),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x6A, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x6B, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x6C, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x6D, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x6E, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x6F, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x70, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x71, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x78, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7B, 0x30),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7C, 0x00),
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x7D, 0x00),

	/* # CMD1 */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xFF, 0x10),
	DSI_DLY_MS(2),

	/* # MIPI Video Mode Bypass RAM */
	/* Gram access, RM, DM */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0xBB, 0x10),
	/* FTE OUT */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x35, 0x00),

	/* # SET_ADDRESS_MODE  inversion */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x36, 0x03),

	/* # Video Mode Porch Setting (VBP,VFP,HBP,HFP) */
	/* DCS LONG */
	DSI_CMD_LONG(DSI_SRC_DATA_ID_DCS_LONG_WRITE, vmps),

	/* TE Timing */
	DSI_CMD_LONG(DSI_SRC_DATA_ID_DCS_LONG_WRITE, te_timing),

	/* # IEF tuning value _E */

};

static struct odin_dsi_cmd lglh600wf2_dsi_bl_cabc_on_command[] = {
	/* # Backlight & CABC Setting */
	/* LED PWM */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x51, 0xFF),
	/* HBM, BCTRL, DD,BL (when CABC On,0x2C) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x53, 0x2C),
	/* Image_Enhancement, CABC (1-UI,2-Still,3-Moving) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x55, 0x91),
	/* Scale up (qHD, HD720 -> FHD) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x58, 0x00),
	/* CABC minimum brightness */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5E, 0x00),
};

static struct odin_dsi_cmd lglh600wf2_dsi_bl_cabc_off_command[] = {
	/* # Backlight & CABC Setting */
	/* LED PWM */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x51, 0xFF),
	/* HBM, BCTRL, DD,BL (when CABC On,0x2C) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x53, 0x2C),
	/* Image_Enhancement, CABC (1-UI,2-Still,3-Moving) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x55, 0x90),
	/* Scale up (qHD, HD720 -> FHD) */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x58, 0x00),
	/* CABC minimum brightness */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_1_PARA, 0x5E, 0x00),
};


static struct odin_dsi_cmd lglh600wf2_dsi_power_on_command[] = {
	/*	11h: exit_sleep_mode : power for the display panel is on. */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_NO_PARA, 0x11, 0x00),
	DSI_DLY_MS(100),
	/*	29h: set_display_on : show the image on the display device. */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_NO_PARA, 0x29, 0x00),
	DSI_DLY_MS(50),
};


static struct odin_dsi_cmd lglh600wf2_dsi_off_command[] = {
	/* 28h: set_display_off :  blanks the display device. */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_NO_PARA, 0x28, 0x00),
	DSI_DLY_MS(20),
	/* 10h: enter_sleep_mode power for the display panel is off */
	DSI_CMD_SHORT(DSI_SRC_DATA_ID_DCS_SHORT_WRITE_NO_PARA, 0x10, 0x00),
	DSI_DLY_MS(100),
};

#endif
/*              */
