include $(srctree)/drivers/misc/mediatek/Makefile.custom

# MTK Platform Support
obj-y += AudDrv_Afe.o AudDrv_Ana.o AudDrv_Clk.o
obj-y += mt_soc_afe_control.o mt_soc_afe_connection.o
obj-y += mt_soc_pcm_capture.o mt_soc_pcm_afe.o mt_soc_pcm_routing.o mt_soc_pcm_btsco.o mt_soc_pcm_dl1_awb.o
obj-y += mt_soc_codec_6397.o
obj-y += mt_soc_dai_hdmi.o mt_soc_hdmi_control.o mt_soc_pcm_hdmi.o
obj-$(CONFIG_SND_SOC_MT8135_GENERIC) += mt_soc_machine.o
obj-$(CONFIG_SND_SOC_MT8135_ARIEL) += mt_soc_ariel.o
