#define LINUX 
#define PVR_BUILD_DIR "mt8135"
#define PVR_BUILD_TYPE "release"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SUPPORT_RGX 1
#define PVR_SECURE_HANDLES 
#define DISPLAY_CONTROLLER dc_fbdev
#define RELEASE 
#define RGX_BVNC_CORE_KM_HEADER "cores/rgxcore_km_1.31.2.0.h" 
#define RGX_BNC_CONFIG_KM_HEADER "configs/rgxconfig_km_1.V.2.0.h" 
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define SYS_USING_INTERRUPTS 
#define PVRSRV_NEED_PVR_DPF 
#define CACHEFLUSH_TYPE CACHEFLUSH_GENERIC
#define SUPPORT_INSECURE_EXPORT 
#define SUPPORT_SECURE_EXPORT 
#define SUPPORT_DISPLAY_CLASS 
#define SUPPORT_LINUX_X86_WRITECOMBINE 
#define SUPPORT_LINUX_X86_PAT 
#define PVR_LINUX_USING_WORKQUEUES 
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE 
#define PVR_LINUX_TIMERS_USING_WORKQUEUES 
#define PVR_LDM_PLATFORM_PRE_REGISTERED_DEV "pvrsrvkm"
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define LDM_PLATFORM 
#define PVRSRV_ENABLE_PROCESS_STATS 
#define PVR_LINUX_PYSMEM_MAX_POOL_PAGES 10240
#define ANDROID 
#define SUPPORT_ION 
#define PVR_ANDROID_NATIVE_WINDOW_HAS_SYNC 
#define PVR_ANDROID_ION_HEADER "linux/ion.h"
#define PVR_ANDROID_ION_PRIV_HEADER "../drivers/gpu/ion/ion_priv.h"
#define MTK_DEBUG 
#define MTK_DEBUG_PROC_PRINT 
