obj-y += cabc/
obj-$(CONFIG_ODIN_DSS) += dipc.o mipi-dsi.o du.o overlay.o overlay_manager.o dss-core.o display.o dss-features.o  writeback.o mem2mem.o crg.o
obj-$(CONFIG_LCD_KCAL) += kcalctrl.o kcalctrl-sysfs.o
obj-$(CONFIG_LCD_MIPI_SPEED_SET) += mipi-dsi-set.o mipi-dsi-set-sysfs.o
