#ifndef MIPI_MIPI_BASE_ADDR
#define MIPI_MIPI_BASE_ADDR 0x312b0000


#define ADDR_INTERRUPT_SOURCE0                         ( 0x00 )
#define ADDR_INTERRUPT_MASK0                           ( 0x04 )
#define ADDR_INTERRUPT_CLEAR0                          ( 0x08 )
#define ADDR_CONFIGURATION0                            ( 0x0C )
#define ADDR_HS_PACKET                                 ( 0x10 )
#define ADDR_ESCAPE_MODE_PACKET                        ( 0x14 )
#define ADDR_ESCAPE_MODE_TRIGGER                       ( 0x18 )
#define ADDR_ACTION                                    ( 0x1C )
#define ADDR_COMMAND_CONFIG                            ( 0x20 )
#define ADDR_VIDEO_TIMING1                             ( 0x24 )
#define ADDR_VIDEO_TIMING2                             ( 0x28 )
#define ADDR_VIDEO_CONFIG1                             ( 0x2C )
#define ADDR_VIDEO_CONFIG2                             ( 0x30 )
#define ADDR_RX_PACKET_HEADER_LANE0                    ( 0x34 )
#define ADDR_STATUS                                    ( 0x38 )
#define ADDR_FIFO_BYTE_COUNT                           ( 0x3C )
#define ADDR_CONFIGURATION1                            ( 0x40 )
#define ADDR_CONFIGURATION2                            ( 0x44 )
#define ADDR_PHY_PLL_SET__ONLY_FPGA                    ( 0x48 )
#define ADDR_PHY_REGISTER_SET__ONLY_FPGA               ( 0x4C )
#define ADDR_INTERRUPT_SOURCE1                         ( 0x50 )
#define ADDR_INTERRUPT_MASK1                           ( 0x54 )
#define ADDR_INTERRUPT_CLEAR1                          ( 0x58 )
#define ADDR_INTERRUPT_SOURCE2                         ( 0x60 )
#define ADDR_INTERRUPT_MASK2                           ( 0x64 )
#define ADDR_INTERRUPT_CLEAR2                          ( 0x68 )
#define ADDR_TEST_CLEAR                                ( 0x70 )
#define ADDR_TEST_CLOCK                                ( 0x74 )
#define ADDR_TEST_DATA_IN                              ( 0x78 )
#define ADDR_TEST_DATA_ENABLE                          ( 0x7C )
#define ADDR_TEST_DATA_OUT                             ( 0x80 )
#define ADDR_RX_PACKET_HEADER_LANE1                    ( 0x90 )
#define ADDR_RX_PACKET_HEADER_LANE2                    ( 0x94 )
#define ADDR_RX_PACKET_HEADER_LANE3                    ( 0x98 )
#define ADDR_TX_CFG_FIFO                               ( 0x1000 )
#define ADDR_RX_PACKET_PAYLOAD_FIFO                    ( 0x2000 )

/* interrupt_source0 */
#define DIP_HS_CFG_COMPLETE_START                      (0)
#define DIP_HS_CFG_COMPLETE_END                        (0)
#define DIP_ESC_COMPLETE_START                         (1)
#define DIP_ESC_COMPLETE_END                           (1)
#define DIP_HS_DATA_COMPLETE_START                     (2)
#define DIP_HS_DATA_COMPLETE_END                       (2)
#define DIP_FRAME_COMPLETE_START                       (3)
#define DIP_FRAME_COMPLETE_END                         (3)
#define DIP_RX_COMPLETE_START                          (4)
#define DIP_RX_COMPLETE_END                            (4)
#define DIP_RXDATA_COMPLETE_START                      (5)
#define DIP_RXDATA_COMPLETE_END                        (5)
#define DIP_RXTRIGGER0_START                           (6)
#define DIP_RXTRIGGER0_END                             (6)
#define DIP_RXTRIGGER1_START                           (7)
#define DIP_RXTRIGGER1_END                             (7)
#define DIP_RXTRIGGER2_START                           (8)
#define DIP_RXTRIGGER2_END                             (8)
#define DIP_RXTRIGGER3_START                           (9)
#define DIP_RXTRIGGER3_END                             (9)
#define DIP_TXCFG_FIFO_UR_ERR_START                    (10)
#define DIP_TXCFG_FIFO_UR_ERR_END                      (10)
#define DIP_TXDATA_FIFO_UR_ERR_START                   (11)
#define DIP_TXDATA_FIFO_UR_ERR_END                     (11)
#define DIP_RXDATA_FIFO_UR_ERR_START                   (12)
#define DIP_RXDATA_FIFO_UR_ERR_END                     (12)
#define DIP_RX_ECC_ERR1_L0_START                       (13)
#define DIP_RX_ECC_ERR1_L0_END                         (13)
#define DIP_RX_ECC_ERR2_L0_START                       (14)
#define DIP_RX_ECC_ERR2_L0_END                         (14)
#define DIP_RX_CHKSUM_ERR_L0_START                     (15)
#define DIP_RX_CHKSUM_ERR_L0_END                       (15)
#define DIP_PHY_ERR_ESC_L0_START                       (16)
#define DIP_PHY_ERR_ESC_L0_END                         (16)
#define DIP_PHY_SYNCERR_ESC_L0_START                   (17)
#define DIP_PHY_SYNCERR_ESC_L0_END                     (17)
#define DIP_PHY_ERR_CONTROL_L0_START                   (18)
#define DIP_PHY_ERR_CONTROL_L0_END                     (18)
#define DIP_PHY_ERR_CONT_LP0_L0_START                  (19)
#define DIP_PHY_ERR_CONT_LP0_L0_END                    (19)
#define DIP_PHY_ERR_CONT_LP1_L0_START                  (20)
#define DIP_PHY_ERR_CONT_LP1_L0_END                    (20)
#define DIP_CLK_LANE_ENTER_HS_START                    (21)
#define DIP_CLK_LANE_ENTER_HS_END                      (21)
#define DIP_CLK_LANE_EXIT_HS_START                     (22)
#define DIP_CLK_LANE_EXIT_HS_END                       (22)
#define DIP_RX_ECC_ERR1_L1_START                       (23)
#define DIP_RX_ECC_ERR1_L1_END                         (23)
#define DIP_RX_ECC_ERR2_L1_START                       (24)
#define DIP_RX_ECC_ERR2_L1_END                         (24)
#define DIP_RX_CHKSUM_ERR_L1_START                     (25)
#define DIP_RX_CHKSUM_ERR_L1_END                       (25)
#define DIP_PHY_ERR_ESC_L1_START                       (26)
#define DIP_PHY_ERR_ESC_L1_END                         (26)
#define DIP_PHY_SYNCERR_ESC_L1_START                   (27)
#define DIP_PHY_SYNCERR_ESC_L1_END                     (27)
#define DIP_PHY_ERR_CONTROL_L1_START                   (28)
#define DIP_PHY_ERR_CONTROL_L1_END                     (28)
#define DIP_PHY_ERR_CONT_LP0_L1_START                  (29)
#define DIP_PHY_ERR_CONT_LP0_L1_END                    (29)
#define DIP_PHY_ERR_CONT_LP1_L1_START                  (30)
#define DIP_PHY_ERR_CONT_LP1_L1_END                    (30)

/* interrupt_mask0 */
#define DIP_MASK0_START                                (31)
#define DIP_MASK0_END                                  (0)

/* interrupt_clear0 */
#define DIP_CLR0_START                                 (31)
#define DIP_CLR0_END                                   (0)

/* configuration0 */
#define DIP_INPUT_FORMAT_START                         (1)
#define DIP_INPUT_FORMAT_END                           (0)
#define DIP_OUTPUT_FORMAT_START                        (4)
#define DIP_OUTPUT_FORMAT_END                          (2)
#define DIP_SWAP_INPUT_START                           (5)
#define DIP_SWAP_INPUT_END                             (5)
#define DIP_LONG_PACKET_ESCAPE_START                   (6)
#define DIP_LONG_PACKET_ESCAPE_END                     (6)
#define DIP_DATAPATH_MODE_START                        (7)
#define DIP_DATAPATH_MODE_END                          (7)
#define DIP_PHY_RESETN_START                           (9)
#define DIP_PHY_RESETN_END                             (9)
#define DIP_PHY_CLK_LANE_ENA_START                     (10)
#define DIP_PHY_CLK_LANE_ENA_END                       (10)
#define DIP_PHY_CLK_LANE_SWAP_START                    (11)
#define DIP_PHY_CLK_LANE_SWAP_END                      (11)
#define DIP_PHY_DATA_LANE_ENA0_START                   (12)
#define DIP_PHY_DATA_LANE_ENA0_END                     (12)
#define DIP_PHY_DATA_LANE_SWAP0_START                  (13)
#define DIP_PHY_DATA_LANE_SWAP0_END                    (13)
#define DIP_PHY_DATA_LANE_ENA1_START                   (14)
#define DIP_PHY_DATA_LANE_ENA1_END                     (14)
#define DIP_PHY_DATA_LANE_SWAP1_START                  (15)
#define DIP_PHY_DATA_LANE_SWAP1_END                    (15)
#define DIP_PHY_DATA_LANE_ENA2_START                   (16)
#define DIP_PHY_DATA_LANE_ENA2_END                     (16)
#define DIP_PHY_DATA_LANE_SWAP2_START                  (17)
#define DIP_PHY_DATA_LANE_SWAP2_END                    (17)
#define DIP_PHY_DATA_LANE_ENA3_START                   (18)
#define DIP_PHY_DATA_LANE_ENA3_END                     (18)
#define DIP_PHY_DATA_LANE_SWAP3_START                  (19)
#define DIP_PHY_DATA_LANE_SWAP3_END                    (19)
#define DIP_TURNDISABLE0_START                         (20)
#define DIP_TURNDISABLE0_END                           (20)
#define DIP_TURNDISABLE1_START                         (21)
#define DIP_TURNDISABLE1_END                           (21)
#define DIP_TURNDISABLE2_START                         (22)
#define DIP_TURNDISABLE2_END                           (22)
#define DIP_TURNDISABLE3_START                         (23)
#define DIP_TURNDISABLE3_END                           (23)
#define DIP_RX_LONG_ENA3_START                         (28)
#define DIP_RX_LONG_ENA3_END                           (28)
#define DIP_RX_LONG_ENA2_START                         (29)
#define DIP_RX_LONG_ENA2_END                           (29)
#define DIP_RX_LONG_ENA1_START                         (30)
#define DIP_RX_LONG_ENA1_END                           (30)
#define DIP_RX_LONG_ENA0_START                         (31)
#define DIP_RX_LONG_ENA0_END                           (31)

/* hs_packet */
#define DIP_DATA_ID_START                              (7)
#define DIP_DATA_ID_END                                (0)
#define DIP_DATA_START                                 (23)
#define DIP_DATA_END                                   (8)
#define DIP_HS_ENTER_BTA_SKIP_START                    (24)
#define DIP_HS_ENTER_BTA_SKIP_END                      (24)
#define DIP_ENABLE_EOTP_START                          (29)
#define DIP_ENABLE_EOTP_END                            (29)
#define DIP_MODE_START                                 (30)
#define DIP_MODE_END                                   (30)
#define DIP_PACKET_TYPE_START                          (31)
#define DIP_PACKET_TYPE_END                            (31)

/* escape_mode_packet */
#define DIP_DATAID_START                               (7)
#define DIP_DATAID_END                                 (0)
#define DIP_DATA0_START                                (15)
#define DIP_DATA0_END                                  (8)
#define DIP_DATA1_START                                (23)
#define DIP_DATA1_END                                  (16)
#define DIP_DATA_START                                 (31)
#define DIP_DATA_END                                   (24)

/* escape_mode_trigger */
#define DIP_TRIGGER_START                              (3)
#define DIP_TRIGGER_END                                (0)

/* action */
#define DIP_CLK_LANE_ENTER_ULP_START                   (0)
#define DIP_CLK_LANE_ENTER_ULP_END                     (0)
#define DIP_CLK_LANE_EXIT_ULP_START                    (1)
#define DIP_CLK_LANE_EXIT_ULP_END                      (1)
#define DIP_CLK_LANE_ENTER_HS_START                    (2)
#define DIP_CLK_LANE_ENTER_HS_END                      (2)
#define DIP_CLK_LANE_EXIT_HS_START                     (3)
#define DIP_CLK_LANE_EXIT_HS_END                       (3)
#define DIP_DATA_LANE_ENTER_ULP_START                  (4)
#define DIP_DATA_LANE_ENTER_ULP_END                    (4)
#define DIP_DATA_LANE_EXIT_ULP_START                   (5)
#define DIP_DATA_LANE_EXIT_ULP_END                     (5)
#define DIP_FORCE_DATA_LANE_STOP_START                 (6)
#define DIP_FORCE_DATA_LANE_STOP_END                   (6)
#define DIP_TURN_REQUEST_START                         (7)
#define DIP_TURN_REQUEST_END                           (7)
#define DIP_FLUSH_RX_FIFO0_START                       (8)
#define DIP_FLUSH_RX_FIFO0_END                         (8)
#define DIP_FLUSH_CFG_FIFO_START                       (9)
#define DIP_FLUSH_CFG_FIFO_END                         (9)
#define DIP_FLUSH_DATA_FIFO_START                      (10)
#define DIP_FLUSH_DATA_FIFO_END                        (10)
#define DIP_STOP_VIDEO_DATA_START                      (11)
#define DIP_STOP_VIDEO_DATA_END                        (11)
#define DIP_FLUSH_RX_FIFO1_START                       (12)
#define DIP_FLUSH_RX_FIFO1_END                         (12)
#define DIP_FLUSH_RX_FIFO2_START                       (13)
#define DIP_FLUSH_RX_FIFO2_END                         (13)
#define DIP_FLUSH_RX_FIFO3_START                       (14)
#define DIP_FLUSH_RX_FIFO3_END                         (14)
#define DIP_PACKET_HEADER_CLR3_START                   (28)
#define DIP_PACKET_HEADER_CLR3_END                     (28)
#define DIP_PACKET_HEADER_CLR2_START                   (29)
#define DIP_PACKET_HEADER_CLR2_END                     (29)
#define DIP_PACKET_HEADER_CLR1_START                   (30)
#define DIP_PACKET_HEADER_CLR1_END                     (30)
#define DIP_PACKET_HEADER_CLR0_START                   (31)
#define DIP_PACKET_HEADER_CLR0_END                     (31)

/* command_config */
#define DIP_NUM_BYTES_START                            (15)
#define DIP_NUM_BYTES_END                              (0)
#define DIP_WAIT_FIFO_START                            (16)
#define DIP_WAIT_FIFO_END                              (16)
#define DIP_HS_CMD_FORCE_DATA_START                    (27)
#define DIP_HS_CMD_FORCE_DATA_END                      (20)
#define DIP_HS_CMD_FORCE_DATA_EN_START                 (28)
#define DIP_HS_CMD_FORCE_DATA_EN_END                   (28)

/* video_timing1 */
#define DIP_HSA_COUNT_START                            (15)
#define DIP_HSA_COUNT_END                              (0)
#define DIP_BLLP_COUNT_START                           (31)
#define DIP_BLLP_COUNT_END                             (16)

/* video_timing2 */
#define DIP_HBP_COUNT_START                            (15)
#define DIP_HBP_COUNT_END                              (0)
#define DIP_HFP_COUNT_START                            (31)
#define DIP_HFP_COUNT_END                              (16)

/* video_config1 */
#define DIP_NUM_VSA_LINES_START                        (7)
#define DIP_NUM_VSA_LINES_END                          (0)
#define DIP_NUM_VBP_LINES_START                        (15)
#define DIP_NUM_VBP_LINES_END                          (8)
#define DIP_NUM_VFP_LINES_START                        (23)
#define DIP_NUM_VFP_LINES_END                          (16)
#define DIP_FULL_SYNC_START                            (31)
#define DIP_FULL_SYNC_END                              (31)

/* video_config2 */
#define DIP_NUM_VACT_LINES_START                       (15)
#define DIP_NUM_VACT_LINES_END                         (0)
#define DIP_NUM_BYTES_LINE_START                       (31)
#define DIP_NUM_BYTES_LINE_END                         (16)

/* rx_packet_header_lane0 */
#define DIP_DATAID_START                               (7)
#define DIP_DATAID_END                                 (0)
#define DIP_DATA0_START                                (15)
#define DIP_DATA0_END                                  (8)
#define DIP_DATA1_START                                (23)
#define DIP_DATA1_END                                  (16)

/* status */
#define DIP_PHY_DIRECTION0_START                       (0)
#define DIP_PHY_DIRECTION0_END                         (0)
#define DIP_RX_ULPESC0_START                           (1)
#define DIP_RX_ULPESC0_END                             (1)
#define DIP_ESCAPE_READY_START                         (2)
#define DIP_ESCAPE_READY_END                           (2)
#define DIP_HS_DATA_READY_START                        (3)
#define DIP_HS_DATA_READY_END                          (3)
#define DIP_HS_CFG_READY_START                         (4)
#define DIP_HS_CFG_READY_END                           (4)
#define DIP_PHY_CLK_STATUS_START                       (6)
#define DIP_PHY_CLK_STATUS_END                         (5)
#define DIP_PHY_DATA_STATUS_START                      (8)
#define DIP_PHY_DATA_STATUS_END                        (7)
#define DIP_HS_DATA_SM_START                           (13)
#define DIP_HS_DATA_SM_END                             (9)
#define DIP_TXSTOPSTATEDATA0_START                     (14)
#define DIP_TXSTOPSTATEDATA0_END                       (14)
#define DIP_LOCAL_RX_LONG_ENA0_START                   (15)
#define DIP_LOCAL_RX_LONG_ENA0_END                     (15)
#define DIP_TXSTOPSTATEDATA1_START                     (16)
#define DIP_TXSTOPSTATEDATA1_END                       (16)
#define DIP_PHY_DIRECTION1_START                       (17)
#define DIP_PHY_DIRECTION1_END                         (17)
#define DIP_RX_ULPESC1_START                           (18)
#define DIP_RX_ULPESC1_END                             (18)
#define DIP_LOCAL_RX_LONG_ENA1_START                   (19)
#define DIP_LOCAL_RX_LONG_ENA1_END                     (19)
#define DIP_TXSTOPSTATEDATA2_START                     (22)
#define DIP_TXSTOPSTATEDATA2_END                       (22)
#define DIP_PHY_DIRECTION2_START                       (23)
#define DIP_PHY_DIRECTION2_END                         (23)
#define DIP_RX_ULPESC2_START                           (24)
#define DIP_RX_ULPESC2_END                             (24)
#define DIP_LOCAL_RX_LONG_ENA2_START                   (25)
#define DIP_LOCAL_RX_LONG_ENA2_END                     (25)
#define DIP_PHY_DIRECTION3_START                       (26)
#define DIP_PHY_DIRECTION3_END                         (26)
#define DIP_RX_ULPESC3_START                           (27)
#define DIP_RX_ULPESC3_END                             (27)
#define DIP_LOCAL_RX_LONG_ENA3_START                   (28)
#define DIP_LOCAL_RX_LONG_ENA3_END                     (28)
#define DIP_TXSTOPSTATEDATA3_START                     (30)
#define DIP_TXSTOPSTATEDATA3_END                       (30)
#define DIP_MIPI_PLL_LOCK_START                        (31)
#define DIP_MIPI_PLL_LOCK_END                          (31)

/* fifo_byte_count */
#define DIP_RX_FIFO_START                              (5)
#define DIP_RX_FIFO_END                                (0)
#define DIP_TX_CFG_FIFO_START                          (16)
#define DIP_TX_CFG_FIFO_END                            (8)
#define DIP_TX_DATA_FIFO_START                         (31)
#define DIP_TX_DATA_FIFO_END                           (20)

/* configuration1 */
#define DIP_LP_LANE_SEL_START                          (3)
#define DIP_LP_LANE_SEL_END                            (0)
#define DIP_HS_LANE_SEL_START                          (7)
#define DIP_HS_LANE_SEL_END                            (4)
#define DIP_TXDATAESC0_WDATA_START                     (15)
#define DIP_TXDATAESC0_WDATA_END                       (8)
#define DIP_TXDATAESC0_WEN_START                       (16)
#define DIP_TXDATAESC0_WEN_END                         (16)
#define DIP_TXDATAESC1_WDATA_START                     (27)
#define DIP_TXDATAESC1_WDATA_END                       (20)
#define DIP_TXDATAESC1_WEN_START                       (28)
#define DIP_TXDATAESC1_WEN_END                         (28)

/* configuration2 */
#define DIP_PDN_TX_CLK0_START                          (0)
#define DIP_PDN_TX_CLK0_END                            (0)
#define DIP_PDN_TX_DATA0_START                         (1)
#define DIP_PDN_TX_DATA0_END                           (1)
#define DIP_PDN_TX_DATA1_START                         (2)
#define DIP_PDN_TX_DATA1_END                           (2)
#define DIP_PDN_TX_CLK1_START                          (4)
#define DIP_PDN_TX_CLK1_END                            (4)
#define DIP_PDN_TX_DATA2_START                         (5)
#define DIP_PDN_TX_DATA2_END                           (5)
#define DIP_PDN_TX_DATA3_START                         (6)
#define DIP_PDN_TX_DATA3_END                           (6)
#define DIP_TXDATAESC2_WDATA_START                     (15)
#define DIP_TXDATAESC2_WDATA_END                       (8)
#define DIP_TXDATAESC2_WEN_START                       (16)
#define DIP_TXDATAESC2_WEN_END                         (16)
#define DIP_TXDATAESC3_WDATA_START                     (27)
#define DIP_TXDATAESC3_WDATA_END                       (20)
#define DIP_TXDATAESC3_WEN_START                       (28)
#define DIP_TXDATAESC3_WEN_END                         (28)

/* phy_pll_set__only_fpga */

/* phy_register_set__only_fpga */

/* interrupt_source1 */
#define DIP_RX_COMPLETE_L1_START                       (0)
#define DIP_RX_COMPLETE_L1_END                         (0)
#define DIP_RXDATA_COMPLETE_L1_START                   (1)
#define DIP_RXDATA_COMPLETE_L1_END                     (1)
#define DIP_RXTRIGGER0_L1_START                        (2)
#define DIP_RXTRIGGER0_L1_END                          (2)
#define DIP_RXTRIGGER1_L1_START                        (3)
#define DIP_RXTRIGGER1_L1_END                          (3)
#define DIP_RXTRIGGER2_L1_START                        (4)
#define DIP_RXTRIGGER2_L1_END                          (4)
#define DIP_RXTRIGGER3_L1_START                        (5)
#define DIP_RXTRIGGER3_L1_END                          (5)
#define DIP_RXDATA_FIFO_ERR_L1_START                   (6)
#define DIP_RXDATA_FIFO_ERR_L1_END                     (6)
#define DIP_RX_COMPLETE_L2_START                       (7)
#define DIP_RX_COMPLETE_L2_END                         (7)
#define DIP_RXDATA_COMPLETE_L2_START                   (8)
#define DIP_RXDATA_COMPLETE_L2_END                     (8)
#define DIP_RXTRIGGER0_L2_START                        (9)
#define DIP_RXTRIGGER0_L2_END                          (9)
#define DIP_RXTRIGGER1_L2_START                        (10)
#define DIP_RXTRIGGER1_L2_END                          (10)
#define DIP_RXTRIGGER2_L2_START                        (11)
#define DIP_RXTRIGGER2_L2_END                          (11)
#define DIP_RXTRIGGER3_L2_START                        (12)
#define DIP_RXTRIGGER3_L2_END                          (12)
#define DIP_RXDATA_FIFO_ERR_L2_START                   (13)
#define DIP_RXDATA_FIFO_ERR_L2_END                     (13)
#define DIP_RX_COMPLETE_L3_START                       (14)
#define DIP_RX_COMPLETE_L3_END                         (14)
#define DIP_RXDATA_COMPLETE_L3_START                   (15)
#define DIP_RXDATA_COMPLETE_L3_END                     (15)
#define DIP_RXTRIGGER0_L3_START                        (16)
#define DIP_RXTRIGGER0_L3_END                          (16)
#define DIP_RXTRIGGER1_L3_START                        (17)
#define DIP_RXTRIGGER1_L3_END                          (17)
#define DIP_RXTRIGGER2_L3_START                        (18)
#define DIP_RXTRIGGER2_L3_END                          (18)
#define DIP_RXTRIGGER3_L3_START                        (19)
#define DIP_RXTRIGGER3_L3_END                          (19)
#define DIP_RXDATA_FIFO_ERR_L3_START                   (20)
#define DIP_RXDATA_FIFO_ERR_L3_END                     (20)
#define DIP_TXCFG_FIFO_OR_ERR_START                    (21)
#define DIP_TXCFG_FIFO_OR_ERR_END                      (21)
#define DIP_TXDATA_FIFO_OR_ERR_START                   (22)
#define DIP_TXDATA_FIFO_OR_ERR_END                     (22)

/* interrupt_mask1 */
#define DIP_MASK1_START                                (31)
#define DIP_MASK1_END                                  (0)

/* interrupt_clear1 */
#define DIP_CLR1_START                                 (31)
#define DIP_CLR1_END                                   (0)

/* interrupt_source2 */
#define DIP_RX_ECC_ERR1_L2_START                       (0)
#define DIP_RX_ECC_ERR1_L2_END                         (0)
#define DIP_RX_ECC_ERR2_L2_START                       (1)
#define DIP_RX_ECC_ERR2_L2_END                         (1)
#define DIP_RX_CHKSUM_ERR_L2_START                     (2)
#define DIP_RX_CHKSUM_ERR_L2_END                       (2)
#define DIP_PHY_ERR_ESC_L2_START                       (3)
#define DIP_PHY_ERR_ESC_L2_END                         (3)
#define DIP_PHY_SYNCERR_ESC_L2_START                   (4)
#define DIP_PHY_SYNCERR_ESC_L2_END                     (4)
#define DIP_PHY_ERR_CONTROL_L2_START                   (5)
#define DIP_PHY_ERR_CONTROL_L2_END                     (5)
#define DIP_PHY_ERR_CONT_LP0_L2_START                  (6)
#define DIP_PHY_ERR_CONT_LP0_L2_END                    (6)
#define DIP_PHY_ERR_CONT_LP1_L2_START                  (7)
#define DIP_PHY_ERR_CONT_LP1_L2_END                    (7)
#define DIP_RX_ECC_ERR1_L3_START                       (8)
#define DIP_RX_ECC_ERR1_L3_END                         (8)
#define DIP_RX_ECC_ERR2_L3_START                       (9)
#define DIP_RX_ECC_ERR2_L3_END                         (9)
#define DIP_RX_CHKSUM_ERR_L3_START                     (10)
#define DIP_RX_CHKSUM_ERR_L3_END                       (10)
#define DIP_PHY_ERR_ESC_L3_START                       (11)
#define DIP_PHY_ERR_ESC_L3_END                         (11)
#define DIP_PHY_SYNCERR_ESC_L3_START                   (12)
#define DIP_PHY_SYNCERR_ESC_L3_END                     (12)
#define DIP_PHY_ERR_CONTROL_L3_START                   (13)
#define DIP_PHY_ERR_CONTROL_L3_END                     (13)
#define DIP_PHY_ERR_CONT_LP0_L3_START                  (14)
#define DIP_PHY_ERR_CONT_LP0_L3_END                    (14)
#define DIP_PHY_ERR_CONT_LP1_L3_START                  (15)
#define DIP_PHY_ERR_CONT_LP1_L3_END                    (15)

/* interrupt_mask2 */
#define DIP_MASK2_START                                (31)
#define DIP_MASK2_END                                  (0)

/* interrupt_clear2 */
#define DIP_CLR2_START                                 (31)
#define DIP_CLR2_END                                   (0)

/* test_clear */
#define DIP_TESTCLR_START                              (0)
#define DIP_TESTCLR_END                                (0)

/* test_clock */
#define DIP_TESTCLK_START                              (0)
#define DIP_TESTCLK_END                                (0)

/* test_data_in */
#define DIP_TESTDIN_START                              (7)
#define DIP_TESTDIN_END                                (0)

/* test_data_enable */
#define DIP_TESTEN_START                               (0)
#define DIP_TESTEN_END                                 (0)

/* test_data_out */
#define DIP_TESTDOUT_START                             (7)
#define DIP_TESTDOUT_END                               (0)

/* rx_packet_header_lane1 */
#define DIP_DATAID_START                               (7)
#define DIP_DATAID_END                                 (0)
#define DIP_DATA0_START                                (15)
#define DIP_DATA0_END                                  (8)
#define DIP_DATA1_START                                (23)
#define DIP_DATA1_END                                  (16)

/* rx_packet_header_lane2 */
#define DIP_DATAID_START                               (7)
#define DIP_DATAID_END                                 (0)
#define DIP_DATA0_START                                (15)
#define DIP_DATA0_END                                  (8)
#define DIP_DATA1_START                                (23)
#define DIP_DATA1_END                                  (16)

/* rx_packet_header_lane3 */
#define DIP_DATAID_START                               (7)
#define DIP_DATAID_END                                 (0)
#define DIP_DATA0_START                                (15)
#define DIP_DATA0_END                                  (8)
#define DIP_DATA1_START                                (23)
#define DIP_DATA1_END                                  (16)


#endif

