#ifndef OVL_BASE_ADDR
#define OVL_BASE_ADDR 0x31230000


#define ADDR_OVL0_CFG0                                 ( 0x0000 )
#define ADDR_OVL0_SIZEXY                               ( 0x0004 )
#define ADDR_OVL0_PATTERN_DATA                         ( 0x0008 )
#define ADDR_OVL0_CFG1                                 ( 0x000C )
#define ADDR_OVL0_L0_CKEY_VALUE                        ( 0x0010 )
#define ADDR_OVL0_L0_CKEY_MASK_VALUE                   ( 0x0014 )
#define ADDR_OVL0_L1_CKEY_VALUE                        ( 0x0018 )
#define ADDR_OVL0_L1_CKEY_MASK_VALUE                   ( 0x001C )
#define ADDR_OVL0_L2_CKEY_VALUE                        ( 0x0020 )
#define ADDR_OVL0_L2_CKEY_MASK_VALUE                   ( 0x0024 )
#define ADDR_OVL0_L3_CKEY_VALUE                        ( 0x0028 )
#define ADDR_OVL0_L3_CKEY_MASK_VALUE                   ( 0x002C )
#define ADDR_OVL0_L4_CKEY_VALUE                        ( 0x0030 )
#define ADDR_OVL0_L4_CKEY_MASK_VALUE                   ( 0x0034 )
#define ADDR_OVL0_L5_CKEY_VALUE                        ( 0x0038 )
#define ADDR_OVL0_L5_CKEY_MASK_VALUE                   ( 0x003C )
#define ADDR_OVL0_CFG2                                 ( 0x0040 )
#define ADDR_OVL0_ALPHA_REG0                           ( 0x0044 )
#define ADDR_OVL0_ALPHA_REG1                           ( 0x0048 )
#define ADDR_OVL0_CFG3                                 ( 0x004C )
#define ADDR_OVL1_CFG0                                 ( 0x0100 )
#define ADDR_OVL1_SIZEXY                               ( 0x0104 )
#define ADDR_OVL1_PATTERN_DATA                         ( 0x0108 )
#define ADDR_OVL1_CFG1                                 ( 0x010C )
#define ADDR_OVL1_L0_CKEY_VALUE                        ( 0x0110 )
#define ADDR_OVL1_L0_CKEY_MASK_VALUE                   ( 0x0114 )
#define ADDR_OVL1_L1_CKEY_VALUE                        ( 0x0118 )
#define ADDR_OVL1_L1_CKEY_MASK_VALUE                   ( 0x011C )
#define ADDR_OVL1_L2_CKEY_VALUE                        ( 0x0120 )
#define ADDR_OVL1_L2_CKEY_MASK_VALUE                   ( 0x0124 )
#define ADDR_OVL1_L3_CKEY_VALUE                        ( 0x0128 )
#define ADDR_OVL1_L3_CKEY_MASK_VALUE                   ( 0x012C )
#define ADDR_OVL1_L4_CKEY_VALUE                        ( 0x0130 )
#define ADDR_OVL1_L4_CKEY_MASK_VALUE                   ( 0x0134 )
#define ADDR_OVL1_L5_CKEY_VALUE                        ( 0x0138 )
#define ADDR_OVL1_L5_CKEY_MASK_VALUE                   ( 0x013C )
#define ADDR_OVL1_CFG2                                 ( 0x0140 )
#define ADDR_OVL1_ALPHA_REG0                           ( 0x0144 )
#define ADDR_OVL1_ALPHA_REG1                           ( 0x0148 )
#define ADDR_OVL1_CFG3                                 ( 0x014C )
#define ADDR_OVL2_CFG0                                 ( 0x0200 )
#define ADDR_OVL2_SIZEXY                               ( 0x0204 )
#define ADDR_OVL2_PATTERN_DATA                         ( 0x0208 )
#define ADDR_OVL2_CFG1                                 ( 0x020C )
#define ADDR_OVL2_L0_CKEY_VALUE                        ( 0x0210 )
#define ADDR_OVL2_L0_CKEY_MASK_VALUE                   ( 0x0214 )
#define ADDR_OVL2_L1_CKEY_VALUE                        ( 0x0218 )
#define ADDR_OVL2_L1_CKEY_MASK_VALUE                   ( 0x021C )
#define ADDR_OVL2_L2_CKEY_VALUE                        ( 0x0220 )
#define ADDR_OVL2_L2_CKEY_MASK_VALUE                   ( 0x0224 )
#define ADDR_OVL2_L3_CKEY_VALUE                        ( 0x0228 )
#define ADDR_OVL2_L3_CKEY_MASK_VALUE                   ( 0x022C )
#define ADDR_OVL2_L4_CKEY_VALUE                        ( 0x0230 )
#define ADDR_OVL2_L4_CKEY_MASK_VALUE                   ( 0x0234 )
#define ADDR_OVL2_L5_CKEY_VALUE                        ( 0x0238 )
#define ADDR_OVL2_L5_CKEY_MASK_VALUE                   ( 0x023C )
#define ADDR_OVL2_CFG2                                 ( 0x0240 )
#define ADDR_OVL2_ALPHA_REG0                           ( 0x0244 )
#define ADDR_OVL2_ALPHA_REG1                           ( 0x0248 )
#define ADDR_OVL2_CFG3                                 ( 0x024C )
#define ADDR_OVL_CFG_G0                                ( 0x0310 )
#define ADDR_OVL_S0_PIP_STARTXY                        ( 0x0318 )
#define ADDR_OVL_S0_PIP_SIZEXY                         ( 0x031C )
#define ADDR_OVL_S1_PIP_STARTXY                        ( 0x0320 )
#define ADDR_OVL_S1_PIP_SIZEXY                         ( 0x0324 )
#define ADDR_OVL_S2_PIP_STARTXY                        ( 0x0328 )
#define ADDR_OVL_S2_PIP_SIZEXY                         ( 0x032C )
#define ADDR_OVL_S3_PIP_STARTXY                        ( 0x0330 )
#define ADDR_OVL_S3_PIP_SIZEXY                         ( 0x0334 )
#define ADDR_OVL_S4_PIP_STARTXY                        ( 0x0338 )
#define ADDR_OVL_S4_PIP_SIZEXY                         ( 0x033C )
#define ADDR_OVL_S5_PIP_STARTXY                        ( 0x0340 )
#define ADDR_OVL_S5_PIP_SIZEXY                         ( 0x0344 )
#define ADDR_OVL_S6_PIP_STARTXY                        ( 0x0348 )
#define ADDR_OVL_S6_PIP_SIZEXY                         ( 0x034C )
#define ADDR_OVL_SW_UPDATE                             ( 0x0350 )
#define ADDR_OVL0_STATUS                               ( 0x0354 )
#define ADDR_OVL1_STATUS                               ( 0x0358 )
#define ADDR_OVL2_STATUS                               ( 0x035c )
#define ADDR_OVL0_SAVE_PIP_POS                         ( 0x0364 )
#define ADDR_OVL1_SAVE_PIP_POS                         ( 0x0368 )
#define ADDR_OVL2_SAVE_PIP_POS                         ( 0x036c )
#define ADDR_OVL_SE_SRC_SECURE_ENABLE                  ( 0x0398 )
#define ADDR_OVL_SE_SRC_SECURE_ENABLE                  ( 0x0398 )
#define ADDR_OVL_SE_SRC_SECURE_ENABLE                  ( 0x0398 )

/* ovl0_cfg0 */
#define DU_OVL0_EN_START                               (0)
#define DU_OVL0_EN_END                                 (0)
#define DU_OVL0_LAYER_OP_START                         (1)
#define DU_OVL0_LAYER_OP_END                           (1)
#define DU_OVL0_DST_SEL_START                          (2)
#define DU_OVL0_DST_SEL_END                            (2)
#define DU_OVL0_DUAL_OP_EN_START                       (3)
#define DU_OVL0_DUAL_OP_EN_END                         (3)
#define DU_OVL0_LAYER0_ROP_START                       (7)
#define DU_OVL0_LAYER0_ROP_END                         (4)
#define DU_OVL0_LAYER0_COP_START                       (11)
#define DU_OVL0_LAYER0_COP_END                         (8)
#define DU_OVL0_LAYER1_COP_START                       (15)
#define DU_OVL0_LAYER1_COP_END                         (12)
#define DU_OVL0_LAYER2_COP_START                       (19)
#define DU_OVL0_LAYER2_COP_END                         (16)
#define DU_OVL0_LAYER3_COP_START                       (23)
#define DU_OVL0_LAYER3_COP_END                         (20)
#define DU_OVL0_LAYER4_COP_START                       (27)
#define DU_OVL0_LAYER4_COP_END                         (24)
#define DU_OVL0_LAYER5_COP_START                       (31)
#define DU_OVL0_LAYER5_COP_END                         (28)

/* ovl0_sizexy */
#define DU_OVL0_SIZEX_START                            (12)
#define DU_OVL0_SIZEX_END                              (0)
#define DU_OVL0_SIZEY_START                            (28)
#define DU_OVL0_SIZEY_END                              (16)

/* ovl0_pattern_data */
#define DU_OVL0_BG_PAT_BDATA_START                     (7)
#define DU_OVL0_BG_PAT_BDATA_END                       (0)
#define DU_OVL0_BG_PAT_GDATA_START                     (15)
#define DU_OVL0_BG_PAT_GDATA_END                       (8)
#define DU_OVL0_BG_PAT_RDATA_START                     (23)
#define DU_OVL0_BG_PAT_RDATA_END                       (16)

/* ovl0_cfg1 */
#define DU_OVL0_LAYER0_CHROMAKEY_EN_START              (0)
#define DU_OVL0_LAYER0_CHROMAKEY_EN_END                (0)
#define DU_OVL0_LAYER1_CHROMAKEY_EN_START              (1)
#define DU_OVL0_LAYER1_CHROMAKEY_EN_END                (1)
#define DU_OVL0_LAYER2_CHROMAKEY_EN_START              (2)
#define DU_OVL0_LAYER2_CHROMAKEY_EN_END                (2)
#define DU_OVL0_LAYER3_CHROMAKEY_EN_START              (3)
#define DU_OVL0_LAYER3_CHROMAKEY_EN_END                (3)
#define DU_OVL0_LAYER4_CHROMAKEY_EN_START              (4)
#define DU_OVL0_LAYER4_CHROMAKEY_EN_END                (4)
#define DU_OVL0_LAYER5_CHROMAKEY_EN_START              (5)
#define DU_OVL0_LAYER5_CHROMAKEY_EN_END                (5)
#define DU_OVL0_LAYER0_DST_PRE_MUL_EN_START            (8)
#define DU_OVL0_LAYER0_DST_PRE_MUL_EN_END              (8)
#define DU_OVL0_LAYER0_SRC_PRE_MUL_EN_START            (9)
#define DU_OVL0_LAYER0_SRC_PRE_MUL_EN_END              (9)
#define DU_OVL0_LAYER1_DST_PRE_MUL_EN_START            (10)
#define DU_OVL0_LAYER1_DST_PRE_MUL_EN_END              (10)
#define DU_OVL0_LAYER1_SRC_PRE_MUL_EN_START            (11)
#define DU_OVL0_LAYER1_SRC_PRE_MUL_EN_END              (11)
#define DU_OVL0_LAYER2_DST_PRE_MUL_EN_START            (12)
#define DU_OVL0_LAYER2_DST_PRE_MUL_EN_END              (12)
#define DU_OVL0_LAYER2_SRC_PRE_MUL_EN_START            (13)
#define DU_OVL0_LAYER2_SRC_PRE_MUL_EN_END              (13)
#define DU_OVL0_LAYER3_DST_PRE_MUL_EN_START            (14)
#define DU_OVL0_LAYER3_DST_PRE_MUL_EN_END              (14)
#define DU_OVL0_LAYER3_SRC_PRE_MUL_EN_START            (15)
#define DU_OVL0_LAYER3_SRC_PRE_MUL_EN_END              (15)
#define DU_OVL0_LAYER4_DST_PRE_MUL_EN_START            (16)
#define DU_OVL0_LAYER4_DST_PRE_MUL_EN_END              (16)
#define DU_OVL0_LAYER4_SRC_PRE_MUL_EN_START            (17)
#define DU_OVL0_LAYER4_SRC_PRE_MUL_EN_END              (17)
#define DU_OVL0_LAYER5_DST_PRE_MUL_EN_START            (18)
#define DU_OVL0_LAYER5_DST_PRE_MUL_EN_END              (18)
#define DU_OVL0_LAYER5_SRC_PRE_MUL_EN_START            (19)
#define DU_OVL0_LAYER5_SRC_PRE_MUL_EN_END              (19)

/* ovl0_l0_ckey_value */
#define DU_OVL0_LAYER0_CHROMA_BDATA_START              (7)
#define DU_OVL0_LAYER0_CHROMA_BDATA_END                (0)
#define DU_OVL0_LAYER0_CHROMA_GDATA_START              (15)
#define DU_OVL0_LAYER0_CHROMA_GDATA_END                (8)
#define DU_OVL0_LAYER0_CHROMA_RDATA_START              (23)
#define DU_OVL0_LAYER0_CHROMA_RDATA_END                (16)

/* ovl0_l0_ckey_mask_value */
#define DU_OVL0_LAYER0_CHROMA_BMASK_START              (7)
#define DU_OVL0_LAYER0_CHROMA_BMASK_END                (0)
#define DU_OVL0_LAYER0_CHROMA_GMASK_START              (15)
#define DU_OVL0_LAYER0_CHROMA_GMASK_END                (8)
#define DU_OVL0_LAYER0_CHROMA_RMASK_START              (23)
#define DU_OVL0_LAYER0_CHROMA_RMASK_END                (16)

/* ovl0_l1_ckey_value */
#define DU_OVL0_LAYER1_CHROMA_BDATA_START              (7)
#define DU_OVL0_LAYER1_CHROMA_BDATA_END                (0)
#define DU_OVL0_LAYER1_CHROMA_GDATA_START              (15)
#define DU_OVL0_LAYER1_CHROMA_GDATA_END                (8)
#define DU_OVL0_LAYER1_CHROMA_RDATA_START              (23)
#define DU_OVL0_LAYER1_CHROMA_RDATA_END                (16)

/* ovl0_l1_ckey_mask_value */
#define DU_OVL0_LAYER1_CHROMA_BMASK_START              (7)
#define DU_OVL0_LAYER1_CHROMA_BMASK_END                (0)
#define DU_OVL0_LAYER1_CHROMA_GMASK_START              (15)
#define DU_OVL0_LAYER1_CHROMA_GMASK_END                (8)
#define DU_OVL0_LAYER1_CHROMA_RMASK_START              (23)
#define DU_OVL0_LAYER1_CHROMA_RMASK_END                (16)

/* ovl0_l2_ckey_value */
#define DU_OVL0_LAYER2_CHROMA_BDATA_START              (7)
#define DU_OVL0_LAYER2_CHROMA_BDATA_END                (0)
#define DU_OVL0_LAYER2_CHROMA_GDATA_START              (15)
#define DU_OVL0_LAYER2_CHROMA_GDATA_END                (8)
#define DU_OVL0_LAYER2_CHROMA_RDATA_START              (23)
#define DU_OVL0_LAYER2_CHROMA_RDATA_END                (16)

/* ovl0_l2_ckey_mask_value */
#define DU_OVL0_LAYER2_CHROMA_BMASK_START              (7)
#define DU_OVL0_LAYER2_CHROMA_BMASK_END                (0)
#define DU_OVL0_LAYER2_CHROMA_GMASK_START              (15)
#define DU_OVL0_LAYER2_CHROMA_GMASK_END                (8)
#define DU_OVL0_LAYER2_CHROMA_RMASK_START              (23)
#define DU_OVL0_LAYER2_CHROMA_RMASK_END                (16)

/* ovl0_l3_ckey_value */
#define DU_OVL0_LAYER3_CHROMA_BDATA_START              (7)
#define DU_OVL0_LAYER3_CHROMA_BDATA_END                (0)
#define DU_OVL0_LAYER3_CHROMA_GDATA_START              (15)
#define DU_OVL0_LAYER3_CHROMA_GDATA_END                (8)
#define DU_OVL0_LAYER3_CHROMA_RDATA_START              (23)
#define DU_OVL0_LAYER3_CHROMA_RDATA_END                (16)

/* ovl0_l3_ckey_mask_value */
#define DU_OVL0_LAYER3_CHROMA_BMASK_START              (7)
#define DU_OVL0_LAYER3_CHROMA_BMASK_END                (0)
#define DU_OVL0_LAYER3_CHROMA_GMASK_START              (15)
#define DU_OVL0_LAYER3_CHROMA_GMASK_END                (8)
#define DU_OVL0_LAYER3_CHROMA_RMASK_START              (23)
#define DU_OVL0_LAYER3_CHROMA_RMASK_END                (16)

/* ovl0_l4_ckey_value */
#define DU_OVL0_LAYER4_CHROMA_BDATA_START              (7)
#define DU_OVL0_LAYER4_CHROMA_BDATA_END                (0)
#define DU_OVL0_LAYER4_CHROMA_GDATA_START              (15)
#define DU_OVL0_LAYER4_CHROMA_GDATA_END                (8)
#define DU_OVL0_LAYER4_CHROMA_RDATA_START              (23)
#define DU_OVL0_LAYER4_CHROMA_RDATA_END                (16)

/* ovl0_l4_ckey_mask_value */
#define DU_OVL0_LAYER4_CHROMA_BMASK_START              (7)
#define DU_OVL0_LAYER4_CHROMA_BMASK_END                (0)
#define DU_OVL0_LAYER4_CHROMA_GMASK_START              (15)
#define DU_OVL0_LAYER4_CHROMA_GMASK_END                (8)
#define DU_OVL0_LAYER4_CHROMA_RMASK_START              (23)
#define DU_OVL0_LAYER4_CHROMA_RMASK_END                (16)

/* ovl0_l5_ckey_value */
#define DU_OVL0_LAYER5_CHROMA_BDATA_START              (7)
#define DU_OVL0_LAYER5_CHROMA_BDATA_END                (0)
#define DU_OVL0_LAYER5_CHROMA_GDATA_START              (15)
#define DU_OVL0_LAYER5_CHROMA_GDATA_END                (8)
#define DU_OVL0_LAYER5_CHROMA_RDATA_START              (23)
#define DU_OVL0_LAYER5_CHROMA_RDATA_END                (16)

/* ovl0_l5_ckey_mask_value */
#define DU_OVL0_LAYER5_CHROMA_BMASK_START              (7)
#define DU_OVL0_LAYER5_CHROMA_BMASK_END                (0)
#define DU_OVL0_LAYER5_CHROMA_GMASK_START              (15)
#define DU_OVL0_LAYER5_CHROMA_GMASK_END                (8)
#define DU_OVL0_LAYER5_CHROMA_RMASK_START              (23)
#define DU_OVL0_LAYER5_CHROMA_RMASK_END                (16)

/* ovl0_cfg2 */
#define DU_OVL0_SRC0_SEL_START                         (2)
#define DU_OVL0_SRC0_SEL_END                           (0)
#define DU_OVL0_SRC1_SEL_START                         (5)
#define DU_OVL0_SRC1_SEL_END                           (3)
#define DU_OVL0_SRC2_SEL_START                         (8)
#define DU_OVL0_SRC2_SEL_END                           (6)
#define DU_OVL0_SRC3_SEL_START                         (11)
#define DU_OVL0_SRC3_SEL_END                           (9)
#define DU_OVL0_SRC4_SEL_START                         (14)
#define DU_OVL0_SRC4_SEL_END                           (12)
#define DU_OVL0_SRC5_SEL_START                         (17)
#define DU_OVL0_SRC5_SEL_END                           (15)
#define DU_OVL0_SRC6_SEL_START                         (20)
#define DU_OVL0_SRC6_SEL_END                           (18)
#define DU_OVL0_SRC0_ALPHA_REG_EN_START                (24)
#define DU_OVL0_SRC0_ALPHA_REG_EN_END                  (24)
#define DU_OVL0_SRC1_ALPHA_REG_EN_START                (25)
#define DU_OVL0_SRC1_ALPHA_REG_EN_END                  (25)
#define DU_OVL0_SRC2_ALPHA_REG_EN_START                (26)
#define DU_OVL0_SRC2_ALPHA_REG_EN_END                  (26)
#define DU_OVL0_SRC3_ALPHA_REG_EN_START                (27)
#define DU_OVL0_SRC3_ALPHA_REG_EN_END                  (27)
#define DU_OVL0_SRC4_ALPHA_REG_EN_START                (28)
#define DU_OVL0_SRC4_ALPHA_REG_EN_END                  (28)
#define DU_OVL0_SRC5_ALPHA_REG_EN_START                (29)
#define DU_OVL0_SRC5_ALPHA_REG_EN_END                  (29)
#define DU_OVL0_SRC6_ALPHA_REG_EN_START                (30)
#define DU_OVL0_SRC6_ALPHA_REG_EN_END                  (30)

/* ovl0_alpha_reg0 */
#define DU_OVL0_SRC0_ALPHA_START                       (7)
#define DU_OVL0_SRC0_ALPHA_END                         (0)
#define DU_OVL0_SRC1_ALPHA_START                       (15)
#define DU_OVL0_SRC1_ALPHA_END                         (8)
#define DU_OVL0_SRC2_ALPHA_START                       (23)
#define DU_OVL0_SRC2_ALPHA_END                         (16)
#define DU_OVL0_SRC3_ALPHA_START                       (31)
#define DU_OVL0_SRC3_ALPHA_END                         (24)

/* ovl0_alpha_reg1 */
#define DU_OVL0_SRC4_ALPHA_START                       (7)
#define DU_OVL0_SRC4_ALPHA_END                         (0)
#define DU_OVL0_SRC5_ALPHA_START                       (15)
#define DU_OVL0_SRC5_ALPHA_END                         (8)
#define DU_OVL0_SRC6_ALPHA_START                       (23)
#define DU_OVL0_SRC6_ALPHA_END                         (16)

/* ovl0_cfg3 */
#define DU_OVL0_SRC2_MUX_SEL_START                     (0)
#define DU_OVL0_SRC2_MUX_SEL_END                       (0)

/* ovl1_cfg0 */
#define DU_OVL1_EN_START                               (0)
#define DU_OVL1_EN_END                                 (0)
#define DU_OVL1_LAYER_OP_START                         (1)
#define DU_OVL1_LAYER_OP_END                           (1)
#define DU_OVL1_DST_SEL_START                          (2)
#define DU_OVL1_DST_SEL_END                            (2)
#define DU_OVL1_DUAL_OP_EN_START                       (3)
#define DU_OVL1_DUAL_OP_EN_END                         (3)
#define DU_OVL1_LAYER0_ROP_START                       (7)
#define DU_OVL1_LAYER0_ROP_END                         (4)
#define DU_OVL1_LAYER0_COP_START                       (11)
#define DU_OVL1_LAYER0_COP_END                         (8)
#define DU_OVL1_LAYER1_COP_START                       (15)
#define DU_OVL1_LAYER1_COP_END                         (12)
#define DU_OVL1_LAYER2_COP_START                       (19)
#define DU_OVL1_LAYER2_COP_END                         (16)
#define DU_OVL1_LAYER3_COP_START                       (23)
#define DU_OVL1_LAYER3_COP_END                         (20)
#define DU_OVL1_LAYER4_COP_START                       (27)
#define DU_OVL1_LAYER4_COP_END                         (24)
#define DU_OVL1_LAYER5_COP_START                       (31)
#define DU_OVL1_LAYER5_COP_END                         (28)

/* ovl1_sizexy */
#define DU_OVL1_SIZEX_START                            (12)
#define DU_OVL1_SIZEX_END                              (0)
#define DU_OVL1_SIZEY_START                            (28)
#define DU_OVL1_SIZEY_END                              (16)

/* ovl1_pattern_data */
#define DU_OVL1_BG_PAT_BDATA_START                     (7)
#define DU_OVL1_BG_PAT_BDATA_END                       (0)
#define DU_OVL1_BG_PAT_GDATA_START                     (15)
#define DU_OVL1_BG_PAT_GDATA_END                       (8)
#define DU_OVL1_BG_PAT_RDATA_START                     (23)
#define DU_OVL1_BG_PAT_RDATA_END                       (16)

/* ovl1_cfg1 */
#define DU_OVL1_LAYER0_CHROMAKEY_EN_START              (0)
#define DU_OVL1_LAYER0_CHROMAKEY_EN_END                (0)
#define DU_OVL1_LAYER1_CHROMAKEY_EN_START              (1)
#define DU_OVL1_LAYER1_CHROMAKEY_EN_END                (1)
#define DU_OVL1_LAYER2_CHROMAKEY_EN_START              (2)
#define DU_OVL1_LAYER2_CHROMAKEY_EN_END                (2)
#define DU_OVL1_LAYER3_CHROMAKEY_EN_START              (3)
#define DU_OVL1_LAYER3_CHROMAKEY_EN_END                (3)
#define DU_OVL1_LAYER4_CHROMAKEY_EN_START              (4)
#define DU_OVL1_LAYER4_CHROMAKEY_EN_END                (4)
#define DU_OVL1_LAYER5_CHROMAKEY_EN_START              (5)
#define DU_OVL1_LAYER5_CHROMAKEY_EN_END                (5)
#define DU_OVL1_LAYER0_DST_PRE_MUL_EN_START            (8)
#define DU_OVL1_LAYER0_DST_PRE_MUL_EN_END              (8)
#define DU_OVL1_LAYER0_SRC_PRE_MUL_EN_START            (9)
#define DU_OVL1_LAYER0_SRC_PRE_MUL_EN_END              (9)
#define DU_OVL1_LAYER1_DST_PRE_MUL_EN_START            (10)
#define DU_OVL1_LAYER1_DST_PRE_MUL_EN_END              (10)
#define DU_OVL1_LAYER1_SRC_PRE_MUL_EN_START            (11)
#define DU_OVL1_LAYER1_SRC_PRE_MUL_EN_END              (11)
#define DU_OVL1_LAYER2_DST_PRE_MUL_EN_START            (12)
#define DU_OVL1_LAYER2_DST_PRE_MUL_EN_END              (12)
#define DU_OVL1_LAYER2_SRC_PRE_MUL_EN_START            (13)
#define DU_OVL1_LAYER2_SRC_PRE_MUL_EN_END              (13)
#define DU_OVL1_LAYER3_DST_PRE_MUL_EN_START            (14)
#define DU_OVL1_LAYER3_DST_PRE_MUL_EN_END              (14)
#define DU_OVL1_LAYER3_SRC_PRE_MUL_EN_START            (15)
#define DU_OVL1_LAYER3_SRC_PRE_MUL_EN_END              (15)
#define DU_OVL1_LAYER4_DST_PRE_MUL_EN_START            (16)
#define DU_OVL1_LAYER4_DST_PRE_MUL_EN_END              (16)
#define DU_OVL1_LAYER4_SRC_PRE_MUL_EN_START            (17)
#define DU_OVL1_LAYER4_SRC_PRE_MUL_EN_END              (17)
#define DU_OVL1_LAYER5_DST_PRE_MUL_EN_START            (18)
#define DU_OVL1_LAYER5_DST_PRE_MUL_EN_END              (18)
#define DU_OVL1_LAYER5_SRC_PRE_MUL_EN_START            (19)
#define DU_OVL1_LAYER5_SRC_PRE_MUL_EN_END              (19)

/* ovl1_l0_ckey_value */
#define DU_OVL1_LAYER0_CHROMA_BDATA_START              (7)
#define DU_OVL1_LAYER0_CHROMA_BDATA_END                (0)
#define DU_OVL1_LAYER0_CHROMA_GDATA_START              (15)
#define DU_OVL1_LAYER0_CHROMA_GDATA_END                (8)
#define DU_OVL1_LAYER0_CHROMA_RDATA_START              (23)
#define DU_OVL1_LAYER0_CHROMA_RDATA_END                (16)

/* ovl1_l0_ckey_mask_value */
#define DU_OVL1_LAYER0_CHROMA_BMASK_START              (7)
#define DU_OVL1_LAYER0_CHROMA_BMASK_END                (0)
#define DU_OVL1_LAYER0_CHROMA_GMASK_START              (15)
#define DU_OVL1_LAYER0_CHROMA_GMASK_END                (8)
#define DU_OVL1_LAYER0_CHROMA_RMASK_START              (23)
#define DU_OVL1_LAYER0_CHROMA_RMASK_END                (16)

/* ovl1_l1_ckey_value */
#define DU_OVL1_LAYER1_CHROMA_BDATA_START              (7)
#define DU_OVL1_LAYER1_CHROMA_BDATA_END                (0)
#define DU_OVL1_LAYER1_CHROMA_GDATA_START              (15)
#define DU_OVL1_LAYER1_CHROMA_GDATA_END                (8)
#define DU_OVL1_LAYER1_CHROMA_RDATA_START              (23)
#define DU_OVL1_LAYER1_CHROMA_RDATA_END                (16)

/* ovl1_l1_ckey_mask_value */
#define DU_OVL1_LAYER1_CHROMA_BMASK_START              (7)
#define DU_OVL1_LAYER1_CHROMA_BMASK_END                (0)
#define DU_OVL1_LAYER1_CHROMA_GMASK_START              (15)
#define DU_OVL1_LAYER1_CHROMA_GMASK_END                (8)
#define DU_OVL1_LAYER1_CHROMA_RMASK_START              (23)
#define DU_OVL1_LAYER1_CHROMA_RMASK_END                (16)

/* ovl1_l2_ckey_value */
#define DU_OVL1_LAYER2_CHROMA_BDATA_START              (7)
#define DU_OVL1_LAYER2_CHROMA_BDATA_END                (0)
#define DU_OVL1_LAYER2_CHROMA_GDATA_START              (15)
#define DU_OVL1_LAYER2_CHROMA_GDATA_END                (8)
#define DU_OVL1_LAYER2_CHROMA_RDATA_START              (23)
#define DU_OVL1_LAYER2_CHROMA_RDATA_END                (16)

/* ovl1_l2_ckey_mask_value */
#define DU_OVL1_LAYER2_CHROMA_BMASK_START              (7)
#define DU_OVL1_LAYER2_CHROMA_BMASK_END                (0)
#define DU_OVL1_LAYER2_CHROMA_GMASK_START              (15)
#define DU_OVL1_LAYER2_CHROMA_GMASK_END                (8)
#define DU_OVL1_LAYER2_CHROMA_RMASK_START              (23)
#define DU_OVL1_LAYER2_CHROMA_RMASK_END                (16)

/* ovl1_l3_ckey_value */
#define DU_OVL1_LAYER3_CHROMA_BDATA_START              (7)
#define DU_OVL1_LAYER3_CHROMA_BDATA_END                (0)
#define DU_OVL1_LAYER3_CHROMA_GDATA_START              (15)
#define DU_OVL1_LAYER3_CHROMA_GDATA_END                (8)
#define DU_OVL1_LAYER3_CHROMA_RDATA_START              (23)
#define DU_OVL1_LAYER3_CHROMA_RDATA_END                (16)

/* ovl1_l3_ckey_mask_value */
#define DU_OVL1_LAYER3_CHROMA_BMASK_START              (7)
#define DU_OVL1_LAYER3_CHROMA_BMASK_END                (0)
#define DU_OVL1_LAYER3_CHROMA_GMASK_START              (15)
#define DU_OVL1_LAYER3_CHROMA_GMASK_END                (8)
#define DU_OVL1_LAYER3_CHROMA_RMASK_START              (23)
#define DU_OVL1_LAYER3_CHROMA_RMASK_END                (16)

/* ovl1_l4_ckey_value */
#define DU_OVL1_LAYER4_CHROMA_BDATA_START              (7)
#define DU_OVL1_LAYER4_CHROMA_BDATA_END                (0)
#define DU_OVL1_LAYER4_CHROMA_GDATA_START              (15)
#define DU_OVL1_LAYER4_CHROMA_GDATA_END                (8)
#define DU_OVL1_LAYER4_CHROMA_RDATA_START              (23)
#define DU_OVL1_LAYER4_CHROMA_RDATA_END                (16)

/* ovl1_l4_ckey_mask_value */
#define DU_OVL1_LAYER4_CHROMA_BMASK_START              (7)
#define DU_OVL1_LAYER4_CHROMA_BMASK_END                (0)
#define DU_OVL1_LAYER4_CHROMA_GMASK_START              (15)
#define DU_OVL1_LAYER4_CHROMA_GMASK_END                (8)
#define DU_OVL1_LAYER4_CHROMA_RMASK_START              (23)
#define DU_OVL1_LAYER4_CHROMA_RMASK_END                (16)

/* ovl1_l5_ckey_value */
#define DU_OVL1_LAYER5_CHROMA_BDATA_START              (7)
#define DU_OVL1_LAYER5_CHROMA_BDATA_END                (0)
#define DU_OVL1_LAYER5_CHROMA_GDATA_START              (15)
#define DU_OVL1_LAYER5_CHROMA_GDATA_END                (8)
#define DU_OVL1_LAYER5_CHROMA_RDATA_START              (23)
#define DU_OVL1_LAYER5_CHROMA_RDATA_END                (16)

/* ovl1_l5_ckey_mask_value */
#define DU_OVL1_LAYER5_CHROMA_BMASK_START              (7)
#define DU_OVL1_LAYER5_CHROMA_BMASK_END                (0)
#define DU_OVL1_LAYER5_CHROMA_GMASK_START              (15)
#define DU_OVL1_LAYER5_CHROMA_GMASK_END                (8)
#define DU_OVL1_LAYER5_CHROMA_RMASK_START              (23)
#define DU_OVL1_LAYER5_CHROMA_RMASK_END                (16)

/* ovl1_cfg2 */
#define DU_OVL1_SRC0_SEL_START                         (2)
#define DU_OVL1_SRC0_SEL_END                           (0)
#define DU_OVL1_SRC1_SEL_START                         (5)
#define DU_OVL1_SRC1_SEL_END                           (3)
#define DU_OVL1_SRC2_SEL_START                         (8)
#define DU_OVL1_SRC2_SEL_END                           (6)
#define DU_OVL1_SRC3_SEL_START                         (11)
#define DU_OVL1_SRC3_SEL_END                           (9)
#define DU_OVL1_SRC4_SEL_START                         (14)
#define DU_OVL1_SRC4_SEL_END                           (12)
#define DU_OVL1_SRC5_SEL_START                         (17)
#define DU_OVL1_SRC5_SEL_END                           (15)
#define DU_OVL1_SRC6_SEL_START                         (20)
#define DU_OVL1_SRC6_SEL_END                           (18)
#define DU_OVL1_SRC0_ALPHA_REG_EN_START                (24)
#define DU_OVL1_SRC0_ALPHA_REG_EN_END                  (24)
#define DU_OVL1_SRC1_ALPHA_REG_EN_START                (25)
#define DU_OVL1_SRC1_ALPHA_REG_EN_END                  (25)
#define DU_OVL1_SRC2_ALPHA_REG_EN_START                (26)
#define DU_OVL1_SRC2_ALPHA_REG_EN_END                  (26)
#define DU_OVL1_SRC3_ALPHA_REG_EN_START                (27)
#define DU_OVL1_SRC3_ALPHA_REG_EN_END                  (27)
#define DU_OVL1_SRC4_ALPHA_REG_EN_START                (28)
#define DU_OVL1_SRC4_ALPHA_REG_EN_END                  (28)
#define DU_OVL1_SRC5_ALPHA_REG_EN_START                (29)
#define DU_OVL1_SRC5_ALPHA_REG_EN_END                  (29)
#define DU_OVL1_SRC6_ALPHA_REG_EN_START                (30)
#define DU_OVL1_SRC6_ALPHA_REG_EN_END                  (30)

/* ovl1_alpha_reg0 */
#define DU_OVL1_SRC0_ALPHA_START                       (7)
#define DU_OVL1_SRC0_ALPHA_END                         (0)
#define DU_OVL1_SRC1_ALPHA_START                       (15)
#define DU_OVL1_SRC1_ALPHA_END                         (8)
#define DU_OVL1_SRC2_ALPHA_START                       (23)
#define DU_OVL1_SRC2_ALPHA_END                         (16)
#define DU_OVL1_SRC3_ALPHA_START                       (31)
#define DU_OVL1_SRC3_ALPHA_END                         (24)

/* ovl1_alpha_reg1 */
#define DU_OVL1_SRC4_ALPHA_START                       (7)
#define DU_OVL1_SRC4_ALPHA_END                         (0)
#define DU_OVL1_SRC5_ALPHA_START                       (15)
#define DU_OVL1_SRC5_ALPHA_END                         (8)
#define DU_OVL1_SRC6_ALPHA_START                       (23)
#define DU_OVL1_SRC6_ALPHA_END                         (16)

/* ovl1_cfg3 */
#define DU_OVL1_SRC2_MUX_SEL_START                     (0)
#define DU_OVL1_SRC2_MUX_SEL_END                       (0)

/* ovl2_cfg0 */
#define DU_OVL2_EN_START                               (0)
#define DU_OVL2_EN_END                                 (0)
#define DU_OVL2_LAYER_OP_START                         (1)
#define DU_OVL2_LAYER_OP_END                           (1)
#define DU_OVL2_DST_SEL_START                          (2)
#define DU_OVL2_DST_SEL_END                            (2)
#define DU_OVL2_DUAL_OP_EN_START                       (3)
#define DU_OVL2_DUAL_OP_EN_END                         (3)
#define DU_OVL2_LAYER0_ROP_START                       (7)
#define DU_OVL2_LAYER0_ROP_END                         (4)
#define DU_OVL2_LAYER0_COP_START                       (11)
#define DU_OVL2_LAYER0_COP_END                         (8)
#define DU_OVL2_LAYER1_COP_START                       (15)
#define DU_OVL2_LAYER1_COP_END                         (12)
#define DU_OVL2_LAYER2_COP_START                       (19)
#define DU_OVL2_LAYER2_COP_END                         (16)
#define DU_OVL2_LAYER3_COP_START                       (23)
#define DU_OVL2_LAYER3_COP_END                         (20)
#define DU_OVL2_LAYER4_COP_START                       (27)
#define DU_OVL2_LAYER4_COP_END                         (24)
#define DU_OVL2_LAYER5_COP_START                       (31)
#define DU_OVL2_LAYER5_COP_END                         (28)

/* ovl2_sizexy */
#define DU_OVL2_SIZEX_START                            (12)
#define DU_OVL2_SIZEX_END                              (0)
#define DU_OVL2_SIZEY_START                            (28)
#define DU_OVL2_SIZEY_END                              (16)

/* ovl2_pattern_data */
#define DU_OVL2_BG_PAT_BDATA_START                     (7)
#define DU_OVL2_BG_PAT_BDATA_END                       (0)
#define DU_OVL2_BG_PAT_GDATA_START                     (15)
#define DU_OVL2_BG_PAT_GDATA_END                       (8)
#define DU_OVL2_BG_PAT_RDATA_START                     (23)
#define DU_OVL2_BG_PAT_RDATA_END                       (16)

/* ovl2_cfg1 */
#define DU_OVL2_LAYER0_CHROMAKEY_EN_START              (0)
#define DU_OVL2_LAYER0_CHROMAKEY_EN_END                (0)
#define DU_OVL2_LAYER1_CHROMAKEY_EN_START              (1)
#define DU_OVL2_LAYER1_CHROMAKEY_EN_END                (1)
#define DU_OVL2_LAYER2_CHROMAKEY_EN_START              (2)
#define DU_OVL2_LAYER2_CHROMAKEY_EN_END                (2)
#define DU_OVL2_LAYER3_CHROMAKEY_EN_START              (3)
#define DU_OVL2_LAYER3_CHROMAKEY_EN_END                (3)
#define DU_OVL2_LAYER4_CHROMAKEY_EN_START              (4)
#define DU_OVL2_LAYER4_CHROMAKEY_EN_END                (4)
#define DU_OVL2_LAYER5_CHROMAKEY_EN_START              (5)
#define DU_OVL2_LAYER5_CHROMAKEY_EN_END                (5)
#define DU_OVL2_LAYER0_DST_PRE_MUL_EN_START            (8)
#define DU_OVL2_LAYER0_DST_PRE_MUL_EN_END              (8)
#define DU_OVL2_LAYER0_SRC_PRE_MUL_EN_START            (9)
#define DU_OVL2_LAYER0_SRC_PRE_MUL_EN_END              (9)
#define DU_OVL2_LAYER1_DST_PRE_MUL_EN_START            (10)
#define DU_OVL2_LAYER1_DST_PRE_MUL_EN_END              (10)
#define DU_OVL2_LAYER1_SRC_PRE_MUL_EN_START            (11)
#define DU_OVL2_LAYER1_SRC_PRE_MUL_EN_END              (11)
#define DU_OVL2_LAYER2_DST_PRE_MUL_EN_START            (12)
#define DU_OVL2_LAYER2_DST_PRE_MUL_EN_END              (12)
#define DU_OVL2_LAYER2_SRC_PRE_MUL_EN_START            (13)
#define DU_OVL2_LAYER2_SRC_PRE_MUL_EN_END              (13)
#define DU_OVL2_LAYER3_DST_PRE_MUL_EN_START            (14)
#define DU_OVL2_LAYER3_DST_PRE_MUL_EN_END              (14)
#define DU_OVL2_LAYER3_SRC_PRE_MUL_EN_START            (15)
#define DU_OVL2_LAYER3_SRC_PRE_MUL_EN_END              (15)
#define DU_OVL2_LAYER4_DST_PRE_MUL_EN_START            (16)
#define DU_OVL2_LAYER4_DST_PRE_MUL_EN_END              (16)
#define DU_OVL2_LAYER4_SRC_PRE_MUL_EN_START            (17)
#define DU_OVL2_LAYER4_SRC_PRE_MUL_EN_END              (17)
#define DU_OVL2_LAYER5_DST_PRE_MUL_EN_START            (18)
#define DU_OVL2_LAYER5_DST_PRE_MUL_EN_END              (18)
#define DU_OVL2_LAYER5_SRC_PRE_MUL_EN_START            (19)
#define DU_OVL2_LAYER5_SRC_PRE_MUL_EN_END              (19)

/* ovl2_l0_ckey_value */
#define DU_OVL2_LAYER0_CHROMA_BDATA_START              (7)
#define DU_OVL2_LAYER0_CHROMA_BDATA_END                (0)
#define DU_OVL2_LAYER0_CHROMA_GDATA_START              (15)
#define DU_OVL2_LAYER0_CHROMA_GDATA_END                (8)
#define DU_OVL2_LAYER0_CHROMA_RDATA_START              (23)
#define DU_OVL2_LAYER0_CHROMA_RDATA_END                (16)

/* ovl2_l0_ckey_mask_value */
#define DU_OVL2_LAYER0_CHROMA_BMASK_START              (7)
#define DU_OVL2_LAYER0_CHROMA_BMASK_END                (0)
#define DU_OVL2_LAYER0_CHROMA_GMASK_START              (15)
#define DU_OVL2_LAYER0_CHROMA_GMASK_END                (8)
#define DU_OVL2_LAYER0_CHROMA_RMASK_START              (23)
#define DU_OVL2_LAYER0_CHROMA_RMASK_END                (16)

/* ovl2_l1_ckey_value */
#define DU_OVL2_LAYER1_CHROMA_BDATA_START              (7)
#define DU_OVL2_LAYER1_CHROMA_BDATA_END                (0)
#define DU_OVL2_LAYER1_CHROMA_GDATA_START              (15)
#define DU_OVL2_LAYER1_CHROMA_GDATA_END                (8)
#define DU_OVL2_LAYER1_CHROMA_RDATA_START              (23)
#define DU_OVL2_LAYER1_CHROMA_RDATA_END                (16)

/* ovl2_l1_ckey_mask_value */
#define DU_OVL2_LAYER1_CHROMA_BMASK_START              (7)
#define DU_OVL2_LAYER1_CHROMA_BMASK_END                (0)
#define DU_OVL2_LAYER1_CHROMA_GMASK_START              (15)
#define DU_OVL2_LAYER1_CHROMA_GMASK_END                (8)
#define DU_OVL2_LAYER1_CHROMA_RMASK_START              (23)
#define DU_OVL2_LAYER1_CHROMA_RMASK_END                (16)

/* ovl2_l2_ckey_value */
#define DU_OVL2_LAYER2_CHROMA_BDATA_START              (7)
#define DU_OVL2_LAYER2_CHROMA_BDATA_END                (0)
#define DU_OVL2_LAYER2_CHROMA_GDATA_START              (15)
#define DU_OVL2_LAYER2_CHROMA_GDATA_END                (8)
#define DU_OVL2_LAYER2_CHROMA_RDATA_START              (23)
#define DU_OVL2_LAYER2_CHROMA_RDATA_END                (16)

/* ovl2_l2_ckey_mask_value */
#define DU_OVL2_LAYER2_CHROMA_BMASK_START              (7)
#define DU_OVL2_LAYER2_CHROMA_BMASK_END                (0)
#define DU_OVL2_LAYER2_CHROMA_GMASK_START              (15)
#define DU_OVL2_LAYER2_CHROMA_GMASK_END                (8)
#define DU_OVL2_LAYER2_CHROMA_RMASK_START              (23)
#define DU_OVL2_LAYER2_CHROMA_RMASK_END                (16)

/* ovl2_l3_ckey_value */
#define DU_OVL2_LAYER3_CHROMA_BDATA_START              (7)
#define DU_OVL2_LAYER3_CHROMA_BDATA_END                (0)
#define DU_OVL2_LAYER3_CHROMA_GDATA_START              (15)
#define DU_OVL2_LAYER3_CHROMA_GDATA_END                (8)
#define DU_OVL2_LAYER3_CHROMA_RDATA_START              (23)
#define DU_OVL2_LAYER3_CHROMA_RDATA_END                (16)

/* ovl2_l3_ckey_mask_value */
#define DU_OVL2_LAYER3_CHROMA_BMASK_START              (7)
#define DU_OVL2_LAYER3_CHROMA_BMASK_END                (0)
#define DU_OVL2_LAYER3_CHROMA_GMASK_START              (15)
#define DU_OVL2_LAYER3_CHROMA_GMASK_END                (8)
#define DU_OVL2_LAYER3_CHROMA_RMASK_START              (23)
#define DU_OVL2_LAYER3_CHROMA_RMASK_END                (16)

/* ovl2_l4_ckey_value */
#define DU_OVL2_LAYER4_CHROMA_BDATA_START              (7)
#define DU_OVL2_LAYER4_CHROMA_BDATA_END                (0)
#define DU_OVL2_LAYER4_CHROMA_GDATA_START              (15)
#define DU_OVL2_LAYER4_CHROMA_GDATA_END                (8)
#define DU_OVL2_LAYER4_CHROMA_RDATA_START              (23)
#define DU_OVL2_LAYER4_CHROMA_RDATA_END                (16)

/* ovl2_l4_ckey_mask_value */
#define DU_OVL2_LAYER4_CHROMA_BMASK_START              (7)
#define DU_OVL2_LAYER4_CHROMA_BMASK_END                (0)
#define DU_OVL2_LAYER4_CHROMA_GMASK_START              (15)
#define DU_OVL2_LAYER4_CHROMA_GMASK_END                (8)
#define DU_OVL2_LAYER4_CHROMA_RMASK_START              (23)
#define DU_OVL2_LAYER4_CHROMA_RMASK_END                (16)

/* ovl2_l5_ckey_value */
#define DU_OVL2_LAYER5_CHROMA_BDATA_START              (7)
#define DU_OVL2_LAYER5_CHROMA_BDATA_END                (0)
#define DU_OVL2_LAYER5_CHROMA_GDATA_START              (15)
#define DU_OVL2_LAYER5_CHROMA_GDATA_END                (8)
#define DU_OVL2_LAYER5_CHROMA_RDATA_START              (23)
#define DU_OVL2_LAYER5_CHROMA_RDATA_END                (16)

/* ovl2_l5_ckey_mask_value */
#define DU_OVL2_LAYER5_CHROMA_BMASK_START              (7)
#define DU_OVL2_LAYER5_CHROMA_BMASK_END                (0)
#define DU_OVL2_LAYER5_CHROMA_GMASK_START              (15)
#define DU_OVL2_LAYER5_CHROMA_GMASK_END                (8)
#define DU_OVL2_LAYER5_CHROMA_RMASK_START              (23)
#define DU_OVL2_LAYER5_CHROMA_RMASK_END                (16)

/* ovl2_cfg2 */
#define DU_OVL2_SRC0_SEL_START                         (2)
#define DU_OVL2_SRC0_SEL_END                           (0)
#define DU_OVL2_SRC1_SEL_START                         (5)
#define DU_OVL2_SRC1_SEL_END                           (3)
#define DU_OVL2_SRC2_SEL_START                         (8)
#define DU_OVL2_SRC2_SEL_END                           (6)
#define DU_OVL2_SRC3_SEL_START                         (11)
#define DU_OVL2_SRC3_SEL_END                           (9)
#define DU_OVL2_SRC4_SEL_START                         (14)
#define DU_OVL2_SRC4_SEL_END                           (12)
#define DU_OVL2_SRC5_SEL_START                         (17)
#define DU_OVL2_SRC5_SEL_END                           (15)
#define DU_OVL2_SRC6_SEL_START                         (20)
#define DU_OVL2_SRC6_SEL_END                           (18)
#define DU_OVL2_SRC0_ALPHA_REG_EN_START                (24)
#define DU_OVL2_SRC0_ALPHA_REG_EN_END                  (24)
#define DU_OVL2_SRC1_ALPHA_REG_EN_START                (25)
#define DU_OVL2_SRC1_ALPHA_REG_EN_END                  (25)
#define DU_OVL2_SRC2_ALPHA_REG_EN_START                (26)
#define DU_OVL2_SRC2_ALPHA_REG_EN_END                  (26)
#define DU_OVL2_SRC3_ALPHA_REG_EN_START                (27)
#define DU_OVL2_SRC3_ALPHA_REG_EN_END                  (27)
#define DU_OVL2_SRC4_ALPHA_REG_EN_START                (28)
#define DU_OVL2_SRC4_ALPHA_REG_EN_END                  (28)
#define DU_OVL2_SRC5_ALPHA_REG_EN_START                (29)
#define DU_OVL2_SRC5_ALPHA_REG_EN_END                  (29)
#define DU_OVL2_SRC6_ALPHA_REG_EN_START                (30)
#define DU_OVL2_SRC6_ALPHA_REG_EN_END                  (30)

/* ovl2_alpha_reg0 */
#define DU_OVL2_SRC0_ALPHA_START                       (7)
#define DU_OVL2_SRC0_ALPHA_END                         (0)
#define DU_OVL2_SRC1_ALPHA_START                       (15)
#define DU_OVL2_SRC1_ALPHA_END                         (8)
#define DU_OVL2_SRC2_ALPHA_START                       (23)
#define DU_OVL2_SRC2_ALPHA_END                         (16)
#define DU_OVL2_SRC3_ALPHA_START                       (31)
#define DU_OVL2_SRC3_ALPHA_END                         (24)

/* ovl2_alpha_reg1 */
#define DU_OVL2_SRC4_ALPHA_START                       (7)
#define DU_OVL2_SRC4_ALPHA_END                         (0)
#define DU_OVL2_SRC5_ALPHA_START                       (15)
#define DU_OVL2_SRC5_ALPHA_END                         (8)
#define DU_OVL2_SRC6_ALPHA_START                       (23)
#define DU_OVL2_SRC6_ALPHA_END                         (16)

/* ovl2_cfg3 */
#define DU_OVL2_SRC2_MUX_SEL_START                     (0)
#define DU_OVL2_SRC2_MUX_SEL_END                       (0)

/* ovl_cfg_g0 */
#define DU_OVL0_SRC0_EN_START                          (0)
#define DU_OVL0_SRC0_EN_END                            (0)
#define DU_OVL0_SRC1_EN_START                          (1)
#define DU_OVL0_SRC1_EN_END                            (1)
#define DU_OVL0_SRC2_EN_START                          (2)
#define DU_OVL0_SRC2_EN_END                            (2)
#define DU_OVL0_SRC3_EN_START                          (3)
#define DU_OVL0_SRC3_EN_END                            (3)
#define DU_OVL0_SRC4_EN_START                          (4)
#define DU_OVL0_SRC4_EN_END                            (4)
#define DU_OVL0_SRC5_EN_START                          (5)
#define DU_OVL0_SRC5_EN_END                            (5)
#define DU_OVL0_SRC6_EN_START                          (6)
#define DU_OVL0_SRC6_EN_END                            (6)
#define DU_OVL1_SRC0_EN_START                          (8)
#define DU_OVL1_SRC0_EN_END                            (8)
#define DU_OVL1_SRC1_EN_START                          (9)
#define DU_OVL1_SRC1_EN_END                            (9)
#define DU_OVL1_SRC2_EN_START                          (10)
#define DU_OVL1_SRC2_EN_END                            (10)
#define DU_OVL1_SRC3_EN_START                          (11)
#define DU_OVL1_SRC3_EN_END                            (11)
#define DU_OVL1_SRC4_EN_START                          (12)
#define DU_OVL1_SRC4_EN_END                            (12)
#define DU_OVL1_SRC5_EN_START                          (13)
#define DU_OVL1_SRC5_EN_END                            (13)
#define DU_OVL1_SRC6_EN_START                          (14)
#define DU_OVL1_SRC6_EN_END                            (14)
#define DU_OVL2_SRC0_EN_START                          (16)
#define DU_OVL2_SRC0_EN_END                            (16)
#define DU_OVL2_SRC1_EN_START                          (17)
#define DU_OVL2_SRC1_EN_END                            (17)
#define DU_OVL2_SRC2_EN_START                          (18)
#define DU_OVL2_SRC2_EN_END                            (18)
#define DU_OVL2_SRC3_EN_START                          (19)
#define DU_OVL2_SRC3_EN_END                            (19)
#define DU_OVL2_SRC4_EN_START                          (20)
#define DU_OVL2_SRC4_EN_END                            (20)
#define DU_OVL2_SRC5_EN_START                          (21)
#define DU_OVL2_SRC5_EN_END                            (21)
#define DU_OVL2_SRC6_EN_START                          (22)
#define DU_OVL2_SRC6_EN_END                            (22)

/* ovl_s0_pip_startxy */
#define DU_OVL_SRC0_PIP_SX_START                       (12)
#define DU_OVL_SRC0_PIP_SX_END                         (0)
#define DU_OVL_SRC0_PIP_SY_START                       (28)
#define DU_OVL_SRC0_PIP_SY_END                         (16)

/* ovl_s0_pip_sizexy */
#define DU_OVL_SRC0_PIP_SIZEX_START                    (12)
#define DU_OVL_SRC0_PIP_SIZEX_END                      (0)
#define DU_OVL_SRC0_PIP_SIZEY_START                    (28)
#define DU_OVL_SRC0_PIP_SIZEY_END                      (16)

/* ovl_s1_pip_startxy */
#define DU_OVL_SRC1_PIP_SX_START                       (12)
#define DU_OVL_SRC1_PIP_SX_END                         (0)
#define DU_OVL_SRC1_PIP_SY_START                       (28)
#define DU_OVL_SRC1_PIP_SY_END                         (16)

/* ovl_s1_pip_sizexy */
#define DU_OVL_SRC1_PIP_SIZEX_START                    (12)
#define DU_OVL_SRC1_PIP_SIZEX_END                      (0)
#define DU_OVL_SRC1_PIP_SIZEY_START                    (28)
#define DU_OVL_SRC1_PIP_SIZEY_END                      (16)

/* ovl_s2_pip_startxy */
#define DU_OVL_SRC2_PIP_SX_START                       (12)
#define DU_OVL_SRC2_PIP_SX_END                         (0)
#define DU_OVL_SRC2_PIP_SY_START                       (28)
#define DU_OVL_SRC2_PIP_SY_END                         (16)

/* ovl_s2_pip_sizexy */
#define DU_OVL_SRC2_PIP_SIZEX_START                    (12)
#define DU_OVL_SRC2_PIP_SIZEX_END                      (0)
#define DU_OVL_SRC2_PIP_SIZEY_START                    (28)
#define DU_OVL_SRC2_PIP_SIZEY_END                      (16)

/* ovl_s3_pip_startxy */
#define DU_OVL_SRC3_PIP_SX_START                       (12)
#define DU_OVL_SRC3_PIP_SX_END                         (0)
#define DU_OVL_SRC3_PIP_SY_START                       (28)
#define DU_OVL_SRC3_PIP_SY_END                         (16)

/* ovl_s3_pip_sizexy */
#define DU_OVL_SRC3_PIP_SIZEX_START                    (12)
#define DU_OVL_SRC3_PIP_SIZEX_END                      (0)
#define DU_OVL_SRC3_PIP_SIZEY_START                    (28)
#define DU_OVL_SRC3_PIP_SIZEY_END                      (16)

/* ovl_s4_pip_startxy */
#define DU_OVL_SRC4_PIP_SX_START                       (12)
#define DU_OVL_SRC4_PIP_SX_END                         (0)
#define DU_OVL_SRC4_PIP_SY_START                       (28)
#define DU_OVL_SRC4_PIP_SY_END                         (16)

/* ovl_s4_pip_sizexy */
#define DU_OVL_SRC4_PIP_SIZEX_START                    (12)
#define DU_OVL_SRC4_PIP_SIZEX_END                      (0)
#define DU_OVL_SRC4_PIP_SIZEY_START                    (28)
#define DU_OVL_SRC4_PIP_SIZEY_END                      (16)

/* ovl_s5_pip_startxy */
#define DU_OVL_SRC5_PIP_SX_START                       (12)
#define DU_OVL_SRC5_PIP_SX_END                         (0)
#define DU_OVL_SRC5_PIP_SY_START                       (28)
#define DU_OVL_SRC5_PIP_SY_END                         (16)

/* ovl_s5_pip_sizexy */
#define DU_OVL_SRC5_PIP_SIZEX_START                    (12)
#define DU_OVL_SRC5_PIP_SIZEX_END                      (0)
#define DU_OVL_SRC5_PIP_SIZEY_START                    (28)
#define DU_OVL_SRC5_PIP_SIZEY_END                      (16)

/* ovl_s6_pip_startxy */
#define DU_OVL_SRC6_PIP_SX_START                       (12)
#define DU_OVL_SRC6_PIP_SX_END                         (0)
#define DU_OVL_SRC6_PIP_SY_START                       (28)
#define DU_OVL_SRC6_PIP_SY_END                         (16)

/* ovl_s6_pip_sizexy */
#define DU_OVL_SRC6_PIP_SIZEX_START                    (12)
#define DU_OVL_SRC6_PIP_SIZEX_END                      (0)
#define DU_OVL_SRC6_PIP_SIZEY_START                    (28)
#define DU_OVL_SRC6_PIP_SIZEY_END                      (16)

/* ovl_sw_update */
#define DU_OVL0_REG_SW_UPDATE_START                    (0)
#define DU_OVL0_REG_SW_UPDATE_END                      (0)
#define DU_OVL1_REG_SW_UPDATE_START                    (1)
#define DU_OVL1_REG_SW_UPDATE_END                      (1)
#define DU_OVL2_REG_SW_UPDATE_START                    (2)
#define DU_OVL2_REG_SW_UPDATE_END                      (2)
#define DU_OVL0_SAVE_PIP_SRR_START                     (16)
#define DU_OVL0_SAVE_PIP_SRR_END                       (16)
#define DU_OVL1_SAVE_PIP_SRR_START                     (17)
#define DU_OVL1_SAVE_PIP_SRR_END                       (17)
#define DU_OVL2_SAVE_PIP_SRR_START                     (18)
#define DU_OVL2_SAVE_PIP_SRR_END                       (18)

/* ovl0_status */
#define DU_OVL0_S0_IFIFO_EMPTY_START                   (0)
#define DU_OVL0_S0_IFIFO_EMPTY_END                     (0)
#define DU_OVL0_S1_IFIFO_EMPTY_START                   (1)
#define DU_OVL0_S1_IFIFO_EMPTY_END                     (1)
#define DU_OVL0_S2_IFIFO_EMPTY_START                   (2)
#define DU_OVL0_S2_IFIFO_EMPTY_END                     (2)
#define DU_OVL0_S3_IFIFO_EMPTY_START                   (3)
#define DU_OVL0_S3_IFIFO_EMPTY_END                     (3)
#define DU_OVL0_S4_IFIFO_EMPTY_START                   (4)
#define DU_OVL0_S4_IFIFO_EMPTY_END                     (4)
#define DU_OVL0_S5_IFIFO_EMPTY_START                   (5)
#define DU_OVL0_S5_IFIFO_EMPTY_END                     (5)
#define DU_OVL0_S6_IFIFO_EMPTY_START                   (6)
#define DU_OVL0_S6_IFIFO_EMPTY_END                     (6)
#define DU_OVL0_S0_IFIFO_FULL_START                    (8)
#define DU_OVL0_S0_IFIFO_FULL_END                      (8)
#define DU_OVL0_S1_IFIFO_FULL_START                    (9)
#define DU_OVL0_S1_IFIFO_FULL_END                      (9)
#define DU_OVL0_S2_IFIFO_FULL_START                    (10)
#define DU_OVL0_S2_IFIFO_FULL_END                      (10)
#define DU_OVL0_S3_IFIFO_FULL_START                    (11)
#define DU_OVL0_S3_IFIFO_FULL_END                      (11)
#define DU_OVL0_S4_IFIFO_FULL_START                    (12)
#define DU_OVL0_S4_IFIFO_FULL_END                      (12)
#define DU_OVL0_S5_IFIFO_FULL_START                    (13)
#define DU_OVL0_S5_IFIFO_FULL_END                      (13)
#define DU_OVL0_S6_IFIFO_FULL_START                    (14)
#define DU_OVL0_S6_IFIFO_FULL_END                      (14)
#define DU_OVL0_CON_ST_START                           (16)
#define DU_OVL0_CON_ST_END                             (16)

/* ovl1_status */
#define DU_OVL1_S0_IFIFO_EMPTY_START                   (0)
#define DU_OVL1_S0_IFIFO_EMPTY_END                     (0)
#define DU_OVL1_S1_IFIFO_EMPTY_START                   (1)
#define DU_OVL1_S1_IFIFO_EMPTY_END                     (1)
#define DU_OVL1_S2_IFIFO_EMPTY_START                   (2)
#define DU_OVL1_S2_IFIFO_EMPTY_END                     (2)
#define DU_OVL1_S3_IFIFO_EMPTY_START                   (3)
#define DU_OVL1_S3_IFIFO_EMPTY_END                     (3)
#define DU_OVL1_S4_IFIFO_EMPTY_START                   (4)
#define DU_OVL1_S4_IFIFO_EMPTY_END                     (4)
#define DU_OVL1_S5_IFIFO_EMPTY_START                   (5)
#define DU_OVL1_S5_IFIFO_EMPTY_END                     (5)
#define DU_OVL1_S6_IFIFO_EMPTY_START                   (6)
#define DU_OVL1_S6_IFIFO_EMPTY_END                     (6)
#define DU_OVL1_S0_IFIFO_FULL_START                    (8)
#define DU_OVL1_S0_IFIFO_FULL_END                      (8)
#define DU_OVL1_S1_IFIFO_FULL_START                    (9)
#define DU_OVL1_S1_IFIFO_FULL_END                      (9)
#define DU_OVL1_S2_IFIFO_FULL_START                    (10)
#define DU_OVL1_S2_IFIFO_FULL_END                      (10)
#define DU_OVL1_S3_IFIFO_FULL_START                    (11)
#define DU_OVL1_S3_IFIFO_FULL_END                      (11)
#define DU_OVL1_S4_IFIFO_FULL_START                    (12)
#define DU_OVL1_S4_IFIFO_FULL_END                      (12)
#define DU_OVL1_S5_IFIFO_FULL_START                    (13)
#define DU_OVL1_S5_IFIFO_FULL_END                      (13)
#define DU_OVL1_S6_IFIFO_FULL_START                    (14)
#define DU_OVL1_S6_IFIFO_FULL_END                      (14)
#define DU_OVL1_CON_ST_START                           (16)
#define DU_OVL1_CON_ST_END                             (16)

/* ovl2_status */
#define DU_OVL2_S0_IFIFO_EMPTY_START                   (0)
#define DU_OVL2_S0_IFIFO_EMPTY_END                     (0)
#define DU_OVL2_S1_IFIFO_EMPTY_START                   (1)
#define DU_OVL2_S1_IFIFO_EMPTY_END                     (1)
#define DU_OVL2_S2_IFIFO_EMPTY_START                   (2)
#define DU_OVL2_S2_IFIFO_EMPTY_END                     (2)
#define DU_OVL2_S3_IFIFO_EMPTY_START                   (3)
#define DU_OVL2_S3_IFIFO_EMPTY_END                     (3)
#define DU_OVL2_S4_IFIFO_EMPTY_START                   (4)
#define DU_OVL2_S4_IFIFO_EMPTY_END                     (4)
#define DU_OVL2_S5_IFIFO_EMPTY_START                   (5)
#define DU_OVL2_S5_IFIFO_EMPTY_END                     (5)
#define DU_OVL2_S6_IFIFO_EMPTY_START                   (6)
#define DU_OVL2_S6_IFIFO_EMPTY_END                     (6)
#define DU_OVL2_S0_IFIFO_FULL_START                    (8)
#define DU_OVL2_S0_IFIFO_FULL_END                      (8)
#define DU_OVL2_S1_IFIFO_FULL_START                    (9)
#define DU_OVL2_S1_IFIFO_FULL_END                      (9)
#define DU_OVL2_S2_IFIFO_FULL_START                    (10)
#define DU_OVL2_S2_IFIFO_FULL_END                      (10)
#define DU_OVL2_S3_IFIFO_FULL_START                    (11)
#define DU_OVL2_S3_IFIFO_FULL_END                      (11)
#define DU_OVL2_S4_IFIFO_FULL_START                    (12)
#define DU_OVL2_S4_IFIFO_FULL_END                      (12)
#define DU_OVL2_S5_IFIFO_FULL_START                    (13)
#define DU_OVL2_S5_IFIFO_FULL_END                      (13)
#define DU_OVL2_S6_IFIFO_FULL_START                    (14)
#define DU_OVL2_S6_IFIFO_FULL_END                      (14)
#define DU_OVL2_CON_ST_START                           (16)
#define DU_OVL2_CON_ST_END                             (16)

/* ovl0_save_pip_pos */
#define DU_OVL0_SAVE_PIP_POSX_START                    (12)
#define DU_OVL0_SAVE_PIP_POSX_END                      (0)
#define DU_OVL0_SAVE_PIP_POSY_START                    (28)
#define DU_OVL0_SAVE_PIP_POSY_END                      (16)

/* ovl1_save_pip_pos */
#define DU_OVL0_SAVE_PIP_POSX_START                    (12)
#define DU_OVL0_SAVE_PIP_POSX_END                      (0)
#define DU_OVL0_SAVE_PIP_POSY_START                    (28)
#define DU_OVL0_SAVE_PIP_POSY_END                      (16)

/* ovl2_save_pip_pos */
#define DU_OVL0_SAVE_PIP_POSX_START                    (12)
#define DU_OVL0_SAVE_PIP_POSX_END                      (0)
#define DU_OVL0_SAVE_PIP_POSY_START                    (28)
#define DU_OVL0_SAVE_PIP_POSY_END                      (16)

/* ovl_se_src_secure_enable */
#define DU_OVL0_SE_SRC0_EN_START                       (0)
#define DU_OVL0_SE_SRC0_EN_END                         (0)
#define DU_OVL0_SE_SRC1_EN_START                       (1)
#define DU_OVL0_SE_SRC1_EN_END                         (1)
#define DU_OVL0_SE_SRC2_EN_START                       (2)
#define DU_OVL0_SE_SRC2_EN_END                         (2)
#define DU_OVL0_SE_SRC3_EN_START                       (3)
#define DU_OVL0_SE_SRC3_EN_END                         (3)
#define DU_OVL0_SE_SRC4_EN_START                       (4)
#define DU_OVL0_SE_SRC4_EN_END                         (4)
#define DU_OVL0_SE_SRC5_EN_START                       (5)
#define DU_OVL0_SE_SRC5_EN_END                         (5)
#define DU_OVL0_SE_SRC6_EN_START                       (6)
#define DU_OVL0_SE_SRC6_EN_END                         (6)
#define DU_OVL1_SE_SRC0_EN_START                       (8)
#define DU_OVL1_SE_SRC0_EN_END                         (8)
#define DU_OVL1_SE_SRC1_EN_START                       (9)
#define DU_OVL1_SE_SRC1_EN_END                         (9)
#define DU_OVL1_SE_SRC2_EN_START                       (10)
#define DU_OVL1_SE_SRC2_EN_END                         (10)
#define DU_OVL1_SE_SRC3_EN_START                       (11)
#define DU_OVL1_SE_SRC3_EN_END                         (11)
#define DU_OVL1_SE_SRC4_EN_START                       (12)
#define DU_OVL1_SE_SRC4_EN_END                         (12)
#define DU_OVL1_SE_SRC5_EN_START                       (13)
#define DU_OVL1_SE_SRC5_EN_END                         (13)
#define DU_OVL1_SE_SRC6_EN_START                       (14)
#define DU_OVL1_SE_SRC6_EN_END                         (14)
#define DU_OVL2_SE_SRC0_EN_START                       (16)
#define DU_OVL2_SE_SRC0_EN_END                         (16)
#define DU_OVL2_SE_SRC1_EN_START                       (17)
#define DU_OVL2_SE_SRC1_EN_END                         (17)
#define DU_OVL2_SE_SRC2_EN_START                       (18)
#define DU_OVL2_SE_SRC2_EN_END                         (18)
#define DU_OVL2_SE_SRC3_EN_START                       (19)
#define DU_OVL2_SE_SRC3_EN_END                         (19)
#define DU_OVL2_SE_SRC4_EN_START                       (20)
#define DU_OVL2_SE_SRC4_EN_END                         (20)
#define DU_OVL2_SE_SRC5_EN_START                       (21)
#define DU_OVL2_SE_SRC5_EN_END                         (21)
#define DU_OVL2_SE_SRC6_EN_START                       (22)
#define DU_OVL2_SE_SRC6_EN_END                         (22)
#define DU_OVL0_SE_SRC0_SEC_EN_START                   (0)
#define DU_OVL0_SE_SRC0_SEC_EN_END                     (0)
#define DU_OVL0_SE_SRC1_SEC_EN_START                   (1)
#define DU_OVL0_SE_SRC1_SEC_EN_END                     (1)
#define DU_OVL0_SE_SRC2_SEC_EN_START                   (2)
#define DU_OVL0_SE_SRC2_SEC_EN_END                     (2)
#define DU_OVL0_SE_SRC3_SEC_EN_START                   (3)
#define DU_OVL0_SE_SRC3_SEC_EN_END                     (3)
#define DU_OVL0_SE_SRC4_SEC_EN_START                   (4)
#define DU_OVL0_SE_SRC4_SEC_EN_END                     (4)
#define DU_OVL0_SE_SRC5_SEC_EN_START                   (5)
#define DU_OVL0_SE_SRC5_SEC_EN_END                     (5)
#define DU_OVL0_SE_SRC6_SEC_EN_START                   (6)
#define DU_OVL0_SE_SRC6_SEC_EN_END                     (6)
#define DU_OVL1_SE_SRC0_SEC_EN_START                   (8)
#define DU_OVL1_SE_SRC0_SEC_EN_END                     (8)
#define DU_OVL1_SE_SRC1_SEC_EN_START                   (9)
#define DU_OVL1_SE_SRC1_SEC_EN_END                     (9)
#define DU_OVL1_SE_SRC2_SEC_EN_START                   (10)
#define DU_OVL1_SE_SRC2_SEC_EN_END                     (10)
#define DU_OVL1_SE_SRC3_SEC_EN_START                   (11)
#define DU_OVL1_SE_SRC3_SEC_EN_END                     (11)
#define DU_OVL1_SE_SRC4_SEC_EN_START                   (12)
#define DU_OVL1_SE_SRC4_SEC_EN_END                     (12)
#define DU_OVL1_SE_SRC5_SEC_EN_START                   (13)
#define DU_OVL1_SE_SRC5_SEC_EN_END                     (13)
#define DU_OVL1_SE_SRC6_SEC_EN_START                   (14)
#define DU_OVL1_SE_SRC6_SEC_EN_END                     (14)
#define DU_OVL2_SE_SRC0_SEC_EN_START                   (16)
#define DU_OVL2_SE_SRC0_SEC_EN_END                     (16)
#define DU_OVL2_SE_SRC1_SEC_EN_START                   (17)
#define DU_OVL2_SE_SRC1_SEC_EN_END                     (17)
#define DU_OVL2_SE_SRC2_SEC_EN_START                   (18)
#define DU_OVL2_SE_SRC2_SEC_EN_END                     (18)
#define DU_OVL2_SE_SRC3_SEC_EN_START                   (19)
#define DU_OVL2_SE_SRC3_SEC_EN_END                     (19)
#define DU_OVL2_SE_SRC4_SEC_EN_START                   (20)
#define DU_OVL2_SE_SRC4_SEC_EN_END                     (20)
#define DU_OVL2_SE_SRC5_SEC_EN_START                   (21)
#define DU_OVL2_SE_SRC5_SEC_EN_END                     (21)
#define DU_OVL2_SE_SRC6_SEC_EN_START                   (22)
#define DU_OVL2_SE_SRC6_SEC_EN_END                     (22)
#define DU_OVL0_SE_LAYER0_SEC_EN_START                 (0)
#define DU_OVL0_SE_LAYER0_SEC_EN_END                   (0)
#define DU_OVL0_SE_LAYER1_SEC_EN_START                 (1)
#define DU_OVL0_SE_LAYER1_SEC_EN_END                   (1)
#define DU_OVL0_SE_LAYER2_SEC_EN_START                 (2)
#define DU_OVL0_SE_LAYER2_SEC_EN_END                   (2)
#define DU_OVL0_SE_LAYER3_SEC_EN_START                 (3)
#define DU_OVL0_SE_LAYER3_SEC_EN_END                   (3)
#define DU_OVL0_SE_LAYER4_SEC_EN_START                 (4)
#define DU_OVL0_SE_LAYER4_SEC_EN_END                   (4)
#define DU_OVL0_SE_LAYER5_SEC_EN_START                 (5)
#define DU_OVL0_SE_LAYER5_SEC_EN_END                   (5)
#define DU_OVL0_SE_LAYER6_SEC_EN_START                 (6)
#define DU_OVL0_SE_LAYER6_SEC_EN_END                   (6)
#define DU_OVL1_SE_LAYER0_SEC_EN_START                 (8)
#define DU_OVL1_SE_LAYER0_SEC_EN_END                   (8)
#define DU_OVL1_SE_LAYER1_SEC_EN_START                 (9)
#define DU_OVL1_SE_LAYER1_SEC_EN_END                   (9)
#define DU_OVL1_SE_LAYER2_SEC_EN_START                 (10)
#define DU_OVL1_SE_LAYER2_SEC_EN_END                   (10)
#define DU_OVL1_SE_LAYER3_SEC_EN_START                 (11)
#define DU_OVL1_SE_LAYER3_SEC_EN_END                   (11)
#define DU_OVL1_SE_LAYER4_SEC_EN_START                 (12)
#define DU_OVL1_SE_LAYER4_SEC_EN_END                   (12)
#define DU_OVL1_SE_LAYER5_SEC_EN_START                 (13)
#define DU_OVL1_SE_LAYER5_SEC_EN_END                   (13)
#define DU_OVL1_SE_LAYER6_SEC_EN_START                 (14)
#define DU_OVL1_SE_LAYER6_SEC_EN_END                   (14)
#define DU_OVL2_SE_LAYER0_SEC_EN_START                 (16)
#define DU_OVL2_SE_LAYER0_SEC_EN_END                   (16)
#define DU_OVL2_SE_LAYER1_SEC_EN_START                 (17)
#define DU_OVL2_SE_LAYER1_SEC_EN_END                   (17)
#define DU_OVL2_SE_LAYER2_SEC_EN_START                 (18)
#define DU_OVL2_SE_LAYER2_SEC_EN_END                   (18)
#define DU_OVL2_SE_LAYER3_SEC_EN_START                 (19)
#define DU_OVL2_SE_LAYER3_SEC_EN_END                   (19)
#define DU_OVL2_SE_LAYER4_SEC_EN_START                 (20)
#define DU_OVL2_SE_LAYER4_SEC_EN_END                   (20)
#define DU_OVL2_SE_LAYER5_SEC_EN_START                 (21)
#define DU_OVL2_SE_LAYER5_SEC_EN_END                   (21)
#define DU_OVL2_SE_LAYER6_SEC_EN_START                 (22)
#define DU_OVL2_SE_LAYER6_SEC_EN_END                   (22)

/* ovl_se_src_secure_enable */
#define DU_OVL0_SE_SRC0_EN_START                       (0)
#define DU_OVL0_SE_SRC0_EN_END                         (0)
#define DU_OVL0_SE_SRC1_EN_START                       (1)
#define DU_OVL0_SE_SRC1_EN_END                         (1)
#define DU_OVL0_SE_SRC2_EN_START                       (2)
#define DU_OVL0_SE_SRC2_EN_END                         (2)
#define DU_OVL0_SE_SRC3_EN_START                       (3)
#define DU_OVL0_SE_SRC3_EN_END                         (3)
#define DU_OVL0_SE_SRC4_EN_START                       (4)
#define DU_OVL0_SE_SRC4_EN_END                         (4)
#define DU_OVL0_SE_SRC5_EN_START                       (5)
#define DU_OVL0_SE_SRC5_EN_END                         (5)
#define DU_OVL0_SE_SRC6_EN_START                       (6)
#define DU_OVL0_SE_SRC6_EN_END                         (6)
#define DU_OVL1_SE_SRC0_EN_START                       (8)
#define DU_OVL1_SE_SRC0_EN_END                         (8)
#define DU_OVL1_SE_SRC1_EN_START                       (9)
#define DU_OVL1_SE_SRC1_EN_END                         (9)
#define DU_OVL1_SE_SRC2_EN_START                       (10)
#define DU_OVL1_SE_SRC2_EN_END                         (10)
#define DU_OVL1_SE_SRC3_EN_START                       (11)
#define DU_OVL1_SE_SRC3_EN_END                         (11)
#define DU_OVL1_SE_SRC4_EN_START                       (12)
#define DU_OVL1_SE_SRC4_EN_END                         (12)
#define DU_OVL1_SE_SRC5_EN_START                       (13)
#define DU_OVL1_SE_SRC5_EN_END                         (13)
#define DU_OVL1_SE_SRC6_EN_START                       (14)
#define DU_OVL1_SE_SRC6_EN_END                         (14)
#define DU_OVL2_SE_SRC0_EN_START                       (16)
#define DU_OVL2_SE_SRC0_EN_END                         (16)
#define DU_OVL2_SE_SRC1_EN_START                       (17)
#define DU_OVL2_SE_SRC1_EN_END                         (17)
#define DU_OVL2_SE_SRC2_EN_START                       (18)
#define DU_OVL2_SE_SRC2_EN_END                         (18)
#define DU_OVL2_SE_SRC3_EN_START                       (19)
#define DU_OVL2_SE_SRC3_EN_END                         (19)
#define DU_OVL2_SE_SRC4_EN_START                       (20)
#define DU_OVL2_SE_SRC4_EN_END                         (20)
#define DU_OVL2_SE_SRC5_EN_START                       (21)
#define DU_OVL2_SE_SRC5_EN_END                         (21)
#define DU_OVL2_SE_SRC6_EN_START                       (22)
#define DU_OVL2_SE_SRC6_EN_END                         (22)
#define DU_OVL0_SE_SRC0_SEC_EN_START                   (0)
#define DU_OVL0_SE_SRC0_SEC_EN_END                     (0)
#define DU_OVL0_SE_SRC1_SEC_EN_START                   (1)
#define DU_OVL0_SE_SRC1_SEC_EN_END                     (1)
#define DU_OVL0_SE_SRC2_SEC_EN_START                   (2)
#define DU_OVL0_SE_SRC2_SEC_EN_END                     (2)
#define DU_OVL0_SE_SRC3_SEC_EN_START                   (3)
#define DU_OVL0_SE_SRC3_SEC_EN_END                     (3)
#define DU_OVL0_SE_SRC4_SEC_EN_START                   (4)
#define DU_OVL0_SE_SRC4_SEC_EN_END                     (4)
#define DU_OVL0_SE_SRC5_SEC_EN_START                   (5)
#define DU_OVL0_SE_SRC5_SEC_EN_END                     (5)
#define DU_OVL0_SE_SRC6_SEC_EN_START                   (6)
#define DU_OVL0_SE_SRC6_SEC_EN_END                     (6)
#define DU_OVL1_SE_SRC0_SEC_EN_START                   (8)
#define DU_OVL1_SE_SRC0_SEC_EN_END                     (8)
#define DU_OVL1_SE_SRC1_SEC_EN_START                   (9)
#define DU_OVL1_SE_SRC1_SEC_EN_END                     (9)
#define DU_OVL1_SE_SRC2_SEC_EN_START                   (10)
#define DU_OVL1_SE_SRC2_SEC_EN_END                     (10)
#define DU_OVL1_SE_SRC3_SEC_EN_START                   (11)
#define DU_OVL1_SE_SRC3_SEC_EN_END                     (11)
#define DU_OVL1_SE_SRC4_SEC_EN_START                   (12)
#define DU_OVL1_SE_SRC4_SEC_EN_END                     (12)
#define DU_OVL1_SE_SRC5_SEC_EN_START                   (13)
#define DU_OVL1_SE_SRC5_SEC_EN_END                     (13)
#define DU_OVL1_SE_SRC6_SEC_EN_START                   (14)
#define DU_OVL1_SE_SRC6_SEC_EN_END                     (14)
#define DU_OVL2_SE_SRC0_SEC_EN_START                   (16)
#define DU_OVL2_SE_SRC0_SEC_EN_END                     (16)
#define DU_OVL2_SE_SRC1_SEC_EN_START                   (17)
#define DU_OVL2_SE_SRC1_SEC_EN_END                     (17)
#define DU_OVL2_SE_SRC2_SEC_EN_START                   (18)
#define DU_OVL2_SE_SRC2_SEC_EN_END                     (18)
#define DU_OVL2_SE_SRC3_SEC_EN_START                   (19)
#define DU_OVL2_SE_SRC3_SEC_EN_END                     (19)
#define DU_OVL2_SE_SRC4_SEC_EN_START                   (20)
#define DU_OVL2_SE_SRC4_SEC_EN_END                     (20)
#define DU_OVL2_SE_SRC5_SEC_EN_START                   (21)
#define DU_OVL2_SE_SRC5_SEC_EN_END                     (21)
#define DU_OVL2_SE_SRC6_SEC_EN_START                   (22)
#define DU_OVL2_SE_SRC6_SEC_EN_END                     (22)
#define DU_OVL0_SE_LAYER0_SEC_EN_START                 (0)
#define DU_OVL0_SE_LAYER0_SEC_EN_END                   (0)
#define DU_OVL0_SE_LAYER1_SEC_EN_START                 (1)
#define DU_OVL0_SE_LAYER1_SEC_EN_END                   (1)
#define DU_OVL0_SE_LAYER2_SEC_EN_START                 (2)
#define DU_OVL0_SE_LAYER2_SEC_EN_END                   (2)
#define DU_OVL0_SE_LAYER3_SEC_EN_START                 (3)
#define DU_OVL0_SE_LAYER3_SEC_EN_END                   (3)
#define DU_OVL0_SE_LAYER4_SEC_EN_START                 (4)
#define DU_OVL0_SE_LAYER4_SEC_EN_END                   (4)
#define DU_OVL0_SE_LAYER5_SEC_EN_START                 (5)
#define DU_OVL0_SE_LAYER5_SEC_EN_END                   (5)
#define DU_OVL0_SE_LAYER6_SEC_EN_START                 (6)
#define DU_OVL0_SE_LAYER6_SEC_EN_END                   (6)
#define DU_OVL1_SE_LAYER0_SEC_EN_START                 (8)
#define DU_OVL1_SE_LAYER0_SEC_EN_END                   (8)
#define DU_OVL1_SE_LAYER1_SEC_EN_START                 (9)
#define DU_OVL1_SE_LAYER1_SEC_EN_END                   (9)
#define DU_OVL1_SE_LAYER2_SEC_EN_START                 (10)
#define DU_OVL1_SE_LAYER2_SEC_EN_END                   (10)
#define DU_OVL1_SE_LAYER3_SEC_EN_START                 (11)
#define DU_OVL1_SE_LAYER3_SEC_EN_END                   (11)
#define DU_OVL1_SE_LAYER4_SEC_EN_START                 (12)
#define DU_OVL1_SE_LAYER4_SEC_EN_END                   (12)
#define DU_OVL1_SE_LAYER5_SEC_EN_START                 (13)
#define DU_OVL1_SE_LAYER5_SEC_EN_END                   (13)
#define DU_OVL1_SE_LAYER6_SEC_EN_START                 (14)
#define DU_OVL1_SE_LAYER6_SEC_EN_END                   (14)
#define DU_OVL2_SE_LAYER0_SEC_EN_START                 (16)
#define DU_OVL2_SE_LAYER0_SEC_EN_END                   (16)
#define DU_OVL2_SE_LAYER1_SEC_EN_START                 (17)
#define DU_OVL2_SE_LAYER1_SEC_EN_END                   (17)
#define DU_OVL2_SE_LAYER2_SEC_EN_START                 (18)
#define DU_OVL2_SE_LAYER2_SEC_EN_END                   (18)
#define DU_OVL2_SE_LAYER3_SEC_EN_START                 (19)
#define DU_OVL2_SE_LAYER3_SEC_EN_END                   (19)
#define DU_OVL2_SE_LAYER4_SEC_EN_START                 (20)
#define DU_OVL2_SE_LAYER4_SEC_EN_END                   (20)
#define DU_OVL2_SE_LAYER5_SEC_EN_START                 (21)
#define DU_OVL2_SE_LAYER5_SEC_EN_END                   (21)
#define DU_OVL2_SE_LAYER6_SEC_EN_START                 (22)
#define DU_OVL2_SE_LAYER6_SEC_EN_END                   (22)

/* ovl_se_src_secure_enable */
#define DU_OVL0_SE_SRC0_EN_START                       (0)
#define DU_OVL0_SE_SRC0_EN_END                         (0)
#define DU_OVL0_SE_SRC1_EN_START                       (1)
#define DU_OVL0_SE_SRC1_EN_END                         (1)
#define DU_OVL0_SE_SRC2_EN_START                       (2)
#define DU_OVL0_SE_SRC2_EN_END                         (2)
#define DU_OVL0_SE_SRC3_EN_START                       (3)
#define DU_OVL0_SE_SRC3_EN_END                         (3)
#define DU_OVL0_SE_SRC4_EN_START                       (4)
#define DU_OVL0_SE_SRC4_EN_END                         (4)
#define DU_OVL0_SE_SRC5_EN_START                       (5)
#define DU_OVL0_SE_SRC5_EN_END                         (5)
#define DU_OVL0_SE_SRC6_EN_START                       (6)
#define DU_OVL0_SE_SRC6_EN_END                         (6)
#define DU_OVL1_SE_SRC0_EN_START                       (8)
#define DU_OVL1_SE_SRC0_EN_END                         (8)
#define DU_OVL1_SE_SRC1_EN_START                       (9)
#define DU_OVL1_SE_SRC1_EN_END                         (9)
#define DU_OVL1_SE_SRC2_EN_START                       (10)
#define DU_OVL1_SE_SRC2_EN_END                         (10)
#define DU_OVL1_SE_SRC3_EN_START                       (11)
#define DU_OVL1_SE_SRC3_EN_END                         (11)
#define DU_OVL1_SE_SRC4_EN_START                       (12)
#define DU_OVL1_SE_SRC4_EN_END                         (12)
#define DU_OVL1_SE_SRC5_EN_START                       (13)
#define DU_OVL1_SE_SRC5_EN_END                         (13)
#define DU_OVL1_SE_SRC6_EN_START                       (14)
#define DU_OVL1_SE_SRC6_EN_END                         (14)
#define DU_OVL2_SE_SRC0_EN_START                       (16)
#define DU_OVL2_SE_SRC0_EN_END                         (16)
#define DU_OVL2_SE_SRC1_EN_START                       (17)
#define DU_OVL2_SE_SRC1_EN_END                         (17)
#define DU_OVL2_SE_SRC2_EN_START                       (18)
#define DU_OVL2_SE_SRC2_EN_END                         (18)
#define DU_OVL2_SE_SRC3_EN_START                       (19)
#define DU_OVL2_SE_SRC3_EN_END                         (19)
#define DU_OVL2_SE_SRC4_EN_START                       (20)
#define DU_OVL2_SE_SRC4_EN_END                         (20)
#define DU_OVL2_SE_SRC5_EN_START                       (21)
#define DU_OVL2_SE_SRC5_EN_END                         (21)
#define DU_OVL2_SE_SRC6_EN_START                       (22)
#define DU_OVL2_SE_SRC6_EN_END                         (22)
#define DU_OVL0_SE_SRC0_SEC_EN_START                   (0)
#define DU_OVL0_SE_SRC0_SEC_EN_END                     (0)
#define DU_OVL0_SE_SRC1_SEC_EN_START                   (1)
#define DU_OVL0_SE_SRC1_SEC_EN_END                     (1)
#define DU_OVL0_SE_SRC2_SEC_EN_START                   (2)
#define DU_OVL0_SE_SRC2_SEC_EN_END                     (2)
#define DU_OVL0_SE_SRC3_SEC_EN_START                   (3)
#define DU_OVL0_SE_SRC3_SEC_EN_END                     (3)
#define DU_OVL0_SE_SRC4_SEC_EN_START                   (4)
#define DU_OVL0_SE_SRC4_SEC_EN_END                     (4)
#define DU_OVL0_SE_SRC5_SEC_EN_START                   (5)
#define DU_OVL0_SE_SRC5_SEC_EN_END                     (5)
#define DU_OVL0_SE_SRC6_SEC_EN_START                   (6)
#define DU_OVL0_SE_SRC6_SEC_EN_END                     (6)
#define DU_OVL1_SE_SRC0_SEC_EN_START                   (8)
#define DU_OVL1_SE_SRC0_SEC_EN_END                     (8)
#define DU_OVL1_SE_SRC1_SEC_EN_START                   (9)
#define DU_OVL1_SE_SRC1_SEC_EN_END                     (9)
#define DU_OVL1_SE_SRC2_SEC_EN_START                   (10)
#define DU_OVL1_SE_SRC2_SEC_EN_END                     (10)
#define DU_OVL1_SE_SRC3_SEC_EN_START                   (11)
#define DU_OVL1_SE_SRC3_SEC_EN_END                     (11)
#define DU_OVL1_SE_SRC4_SEC_EN_START                   (12)
#define DU_OVL1_SE_SRC4_SEC_EN_END                     (12)
#define DU_OVL1_SE_SRC5_SEC_EN_START                   (13)
#define DU_OVL1_SE_SRC5_SEC_EN_END                     (13)
#define DU_OVL1_SE_SRC6_SEC_EN_START                   (14)
#define DU_OVL1_SE_SRC6_SEC_EN_END                     (14)
#define DU_OVL2_SE_SRC0_SEC_EN_START                   (16)
#define DU_OVL2_SE_SRC0_SEC_EN_END                     (16)
#define DU_OVL2_SE_SRC1_SEC_EN_START                   (17)
#define DU_OVL2_SE_SRC1_SEC_EN_END                     (17)
#define DU_OVL2_SE_SRC2_SEC_EN_START                   (18)
#define DU_OVL2_SE_SRC2_SEC_EN_END                     (18)
#define DU_OVL2_SE_SRC3_SEC_EN_START                   (19)
#define DU_OVL2_SE_SRC3_SEC_EN_END                     (19)
#define DU_OVL2_SE_SRC4_SEC_EN_START                   (20)
#define DU_OVL2_SE_SRC4_SEC_EN_END                     (20)
#define DU_OVL2_SE_SRC5_SEC_EN_START                   (21)
#define DU_OVL2_SE_SRC5_SEC_EN_END                     (21)
#define DU_OVL2_SE_SRC6_SEC_EN_START                   (22)
#define DU_OVL2_SE_SRC6_SEC_EN_END                     (22)
#define DU_OVL0_SE_LAYER0_SEC_EN_START                 (0)
#define DU_OVL0_SE_LAYER0_SEC_EN_END                   (0)
#define DU_OVL0_SE_LAYER1_SEC_EN_START                 (1)
#define DU_OVL0_SE_LAYER1_SEC_EN_END                   (1)
#define DU_OVL0_SE_LAYER2_SEC_EN_START                 (2)
#define DU_OVL0_SE_LAYER2_SEC_EN_END                   (2)
#define DU_OVL0_SE_LAYER3_SEC_EN_START                 (3)
#define DU_OVL0_SE_LAYER3_SEC_EN_END                   (3)
#define DU_OVL0_SE_LAYER4_SEC_EN_START                 (4)
#define DU_OVL0_SE_LAYER4_SEC_EN_END                   (4)
#define DU_OVL0_SE_LAYER5_SEC_EN_START                 (5)
#define DU_OVL0_SE_LAYER5_SEC_EN_END                   (5)
#define DU_OVL0_SE_LAYER6_SEC_EN_START                 (6)
#define DU_OVL0_SE_LAYER6_SEC_EN_END                   (6)
#define DU_OVL1_SE_LAYER0_SEC_EN_START                 (8)
#define DU_OVL1_SE_LAYER0_SEC_EN_END                   (8)
#define DU_OVL1_SE_LAYER1_SEC_EN_START                 (9)
#define DU_OVL1_SE_LAYER1_SEC_EN_END                   (9)
#define DU_OVL1_SE_LAYER2_SEC_EN_START                 (10)
#define DU_OVL1_SE_LAYER2_SEC_EN_END                   (10)
#define DU_OVL1_SE_LAYER3_SEC_EN_START                 (11)
#define DU_OVL1_SE_LAYER3_SEC_EN_END                   (11)
#define DU_OVL1_SE_LAYER4_SEC_EN_START                 (12)
#define DU_OVL1_SE_LAYER4_SEC_EN_END                   (12)
#define DU_OVL1_SE_LAYER5_SEC_EN_START                 (13)
#define DU_OVL1_SE_LAYER5_SEC_EN_END                   (13)
#define DU_OVL1_SE_LAYER6_SEC_EN_START                 (14)
#define DU_OVL1_SE_LAYER6_SEC_EN_END                   (14)
#define DU_OVL2_SE_LAYER0_SEC_EN_START                 (16)
#define DU_OVL2_SE_LAYER0_SEC_EN_END                   (16)
#define DU_OVL2_SE_LAYER1_SEC_EN_START                 (17)
#define DU_OVL2_SE_LAYER1_SEC_EN_END                   (17)
#define DU_OVL2_SE_LAYER2_SEC_EN_START                 (18)
#define DU_OVL2_SE_LAYER2_SEC_EN_END                   (18)
#define DU_OVL2_SE_LAYER3_SEC_EN_START                 (19)
#define DU_OVL2_SE_LAYER3_SEC_EN_END                   (19)
#define DU_OVL2_SE_LAYER4_SEC_EN_START                 (20)
#define DU_OVL2_SE_LAYER4_SEC_EN_END                   (20)
#define DU_OVL2_SE_LAYER5_SEC_EN_START                 (21)
#define DU_OVL2_SE_LAYER5_SEC_EN_END                   (21)
#define DU_OVL2_SE_LAYER6_SEC_EN_START                 (22)
#define DU_OVL2_SE_LAYER6_SEC_EN_END                   (22)


#endif

