obj-$(CONFIG_BATTERY_HISI_HI6421V300)	+= hisi_battery_data.o hisi_hi6421v300_coul.o
obj-$(CONFIG_BATTERY_HISI_COUL_TEST)	+= hisi_coul_drv_test.o
obj-$(CONFIG_BATTERY_HISI_COUL)		+= hisi_coul_drv.o
obj-$(CONFIG_BQ_BCI_BATTERY)		+= bq_bci_battery.o
obj-$(CONFIG_BQ2419X_CHARGER)		+= bq2419x_charger.o pd_charge_flag_parse.o
