#obj-$(CONFIG_ODIN_GFX) += gfx_drv.o gfx_draw.o gfx_hw.o gfx_surface.o gfx_sw_draw.o gfx_cfg.o os_util.o gfx_proc.o core/gfx_core_drv.o core/gfx_core_hw.o
obj-$(CONFIG_ODIN_GFX) += gfx_drv.o gfx_draw.o gfx_hw.o gfx_surface.o gfx_cfg.o os_util.o gfx_proc.o gfx_core_drv.o gfx_core_hw.o
