/*!
 *****************************************************************************
 *
 * @file       msvdx_vec_vc1_reg_io2.h
 *
 * This file contains the MSVDX_VEC_VC1_REG_IO2_H Defintions.
 * ---------------------------------------------------------------------------
 *
 * Copyright (c) Imagination Technologies Ltd.
 * 
 * The contents of this file are subject to the MIT license as set out below.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a 
 * copy of this software and associated documentation files (the "Software"), 
 * to deal in the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, sublicense, 
 * and/or sell copies of the Software, and to permit persons to whom the 
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in 
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
 * THE SOFTWARE.
 * 
 * Alternatively, the contents of this file may be used under the terms of the 
 * GNU General Public License Version 2 ("GPL")in which case the provisions of
 * GPL are applicable instead of those above. 
 * 
 * If you wish to allow use of your version of this file only under the terms 
 * of GPL, and not to allow others to use your version of this file under the 
 * terms of the MIT license, indicate your decision by deleting the provisions 
 * above and replace them with the notice and other provisions required by GPL 
 * as set out in the file called “GPLHEADER” included in this distribution. If 
 * you do not delete the provisions above, a recipient may use your version of 
 * this file under the terms of either the MIT license or GPL.
 * 
 * This License is also included in this distribution in the file called 
 * "MIT_COPYING".
 *
 *****************************************************************************/

#if !defined (__MSVDX_VEC_VC1_REG_IO2_H__)
#define __MSVDX_VEC_VC1_REG_IO2_H__

#ifdef __cplusplus
extern "C" {
#endif


#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_OFFSET		(0x0400)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_SPS0, VC1_FE_SYNCMARKER
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_SYNCMARKER_MASK		(0x00000004)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_SYNCMARKER_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_SYNCMARKER_SHIFT		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_SYNCMARKER_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_SYNCMARKER_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_SYNCMARKER_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_SPS0, VC1_FE_VSTRANSFORM
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_VSTRANSFORM_MASK		(0x00000002)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_VSTRANSFORM_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_VSTRANSFORM_SHIFT		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_VSTRANSFORM_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_VSTRANSFORM_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_VSTRANSFORM_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_SPS0, VC1_FE_INTERLACE
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_INTERLACE_MASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_INTERLACE_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_INTERLACE_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_INTERLACE_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_INTERLACE_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_SPS0_VC1_FE_INTERLACE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_OFFSET		(0x0404)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS0, VC1_FE_FIRST_MB_IN_SLICE_Y_EXT
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FIRST_MB_IN_SLICE_Y_EXT_MASK		(0x10000000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FIRST_MB_IN_SLICE_Y_EXT_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FIRST_MB_IN_SLICE_Y_EXT_SHIFT		(28)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FIRST_MB_IN_SLICE_Y_EXT_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FIRST_MB_IN_SLICE_Y_EXT_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FIRST_MB_IN_SLICE_Y_EXT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS0, VC1_FE_PIC_HEIGHT_IN_MBS_EXT
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_HEIGHT_IN_MBS_EXT_MASK		(0x08000000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_HEIGHT_IN_MBS_EXT_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_HEIGHT_IN_MBS_EXT_SHIFT		(27)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_HEIGHT_IN_MBS_EXT_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_HEIGHT_IN_MBS_EXT_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_HEIGHT_IN_MBS_EXT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS0, VC1_FE_PIC_WIDTH_IN_MBS_LESS1
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_WIDTH_IN_MBS_LESS1_MASK		(0x07F80000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_WIDTH_IN_MBS_LESS1_LSBMASK		(0x000000FF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_WIDTH_IN_MBS_LESS1_SHIFT		(19)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_WIDTH_IN_MBS_LESS1_LENGTH		(8)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_WIDTH_IN_MBS_LESS1_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_WIDTH_IN_MBS_LESS1_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS0, VC1_FE_PIC_HEIGHT_IN_MBS_LESS1
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_HEIGHT_IN_MBS_LESS1_MASK		(0x0007F000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_HEIGHT_IN_MBS_LESS1_LSBMASK		(0x0000007F)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_HEIGHT_IN_MBS_LESS1_SHIFT		(12)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_HEIGHT_IN_MBS_LESS1_LENGTH		(7)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_HEIGHT_IN_MBS_LESS1_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PIC_HEIGHT_IN_MBS_LESS1_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS0, VC1_FE_FIRST_MB_IN_SLICE_Y
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FIRST_MB_IN_SLICE_Y_MASK		(0x00000FE0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FIRST_MB_IN_SLICE_Y_LSBMASK		(0x0000007F)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FIRST_MB_IN_SLICE_Y_SHIFT		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FIRST_MB_IN_SLICE_Y_LENGTH		(7)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FIRST_MB_IN_SLICE_Y_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FIRST_MB_IN_SLICE_Y_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS0, VC1_FE_PTYPE
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PTYPE_MASK		(0x0000001C)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PTYPE_LSBMASK		(0x00000007)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PTYPE_SHIFT		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PTYPE_LENGTH		(3)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PTYPE_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PTYPE_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_PTYPE_ENUM {
	MSVDX_VEC_VC1_VC1_FE_PTYPE_RESERVED3 = 0x7,
	MSVDX_VEC_VC1_VC1_FE_PTYPE_RESERVED2 = 0x6,
	MSVDX_VEC_VC1_VC1_FE_PTYPE_RESERVED1 = 0x5,
	MSVDX_VEC_VC1_VC1_FE_PTYPE_SKIPPED_PICTURE = 0x4,
	MSVDX_VEC_VC1_VC1_FE_PTYPE_BI_PICTURE = 0x3,
	MSVDX_VEC_VC1_VC1_FE_PTYPE_B_PICTURE = 0x2,
	MSVDX_VEC_VC1_VC1_FE_PTYPE_P_PICTURE = 0x1,
	MSVDX_VEC_VC1_VC1_FE_PTYPE_I_PICTURE = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS0, VC1_FE_FCM

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FCM_MASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FCM_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FCM_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FCM_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FCM_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FCM_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS0_VC1_FE_FCM_ENUM {
	MSVDX_VEC_VC1_VC1_FE_FCM_FIELD_INTERLACED_PICTURE = 0x3,
	MSVDX_VEC_VC1_VC1_FE_FCM_FRAME_INTERLACED_PICTURE = 0x2,
	MSVDX_VEC_VC1_VC1_FE_FCM_RESERVED = 0x1,
	MSVDX_VEC_VC1_VC1_FE_FCM_PROGRESSIVE_PICTURE = 0x0,
};

#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_OFFSET		(0x0408)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS1, VC1_FE_BP_FORMAT
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BP_FORMAT_MASK		(0x20000000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BP_FORMAT_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BP_FORMAT_SHIFT		(29)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BP_FORMAT_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BP_FORMAT_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BP_FORMAT_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BP_FORMAT_ENUM {
	MSVDX_VEC_VC1_VC1_FE_BP_FORMAT_NON_INTERLEAVED = 0x1,
	MSVDX_VEC_VC1_VC1_FE_BP_FORMAT_INTERLEAVED = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS1, VC1_FE_BP_PRESENT

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BP_PRESENT_MASK		(0x1C000000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BP_PRESENT_LSBMASK		(0x00000007)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BP_PRESENT_SHIFT		(26)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BP_PRESENT_LENGTH		(3)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BP_PRESENT_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BP_PRESENT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS1, VC1_FE_RAWCODINGFLAG

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_RAWCODINGFLAG_MASK		(0x03F80000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_RAWCODINGFLAG_LSBMASK		(0x0000007F)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_RAWCODINGFLAG_SHIFT		(19)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_RAWCODINGFLAG_LENGTH		(7)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_RAWCODINGFLAG_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_RAWCODINGFLAG_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS1, VC1_FE_MVMODE
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE_MASK		(0x00070000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE_LSBMASK		(0x00000007)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE_SHIFT		(16)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE_LENGTH		(3)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE_ENUM {
	MSVDX_VEC_VC1_VC1_FE_MVMODE_RESERVED1 = 0x7,
	MSVDX_VEC_VC1_VC1_FE_MVMODE_RESERVED0 = 0x6,
	MSVDX_VEC_VC1_VC1_FE_MVMODE_QUARTER_PEL_BICUBIC = 0x5,
	MSVDX_VEC_VC1_VC1_FE_MVMODE_INTENSITY_COMPENSTATION = 0x4,
	MSVDX_VEC_VC1_VC1_FE_MVMODE_MIXED_MV = 0x3,
	MSVDX_VEC_VC1_VC1_FE_MVMODE_1MV_HALF_PEL = 0x2,
	MSVDX_VEC_VC1_VC1_FE_MVMODE_1MV_HALF_PEL_BILINEAR = 0x1,
	MSVDX_VEC_VC1_VC1_FE_MVMODE_1MV = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS1, VC1_FE_MVMODE2

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE2_MASK		(0x00006000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE2_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE2_SHIFT		(13)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE2_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE2_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE2_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_MVMODE2_ENUM {
	MSVDX_VEC_VC1_VC1_FE_MVMODE2_MIXED_MV = 0x3,
	MSVDX_VEC_VC1_VC1_FE_MVMODE2_1MV_HALF_PEL = 0x2,
	MSVDX_VEC_VC1_VC1_FE_MVMODE2_1MV_HALF_PEL_BILINEAR = 0x1,
	MSVDX_VEC_VC1_VC1_FE_MVMODE2_1MV = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS1, VC1_FE_TTMBF

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_TTMBF_MASK		(0x00001000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_TTMBF_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_TTMBF_SHIFT		(12)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_TTMBF_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_TTMBF_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_TTMBF_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS1, VC1_FE_TTFRM

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_TTFRM_MASK		(0x00000C00)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_TTFRM_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_TTFRM_SHIFT		(10)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_TTFRM_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_TTFRM_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_TTFRM_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_TTFRM_ENUM {
	MSVDX_VEC_VC1_VC1_FE_TTFRM_4X4_TRANSFORM = 0x3,
	MSVDX_VEC_VC1_VC1_FE_TTFRM_4X8_TRANSFORM = 0x2,
	MSVDX_VEC_VC1_VC1_FE_TTFRM_8X4_TRANSFORM = 0x1,
	MSVDX_VEC_VC1_VC1_FE_TTFRM_8X8_TRANSFORM = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS1, VC1_FE_BFRACTION
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BFRACTION_MASK		(0x000003E0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BFRACTION_LSBMASK		(0x0000001F)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BFRACTION_SHIFT		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BFRACTION_LENGTH		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BFRACTION_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_BFRACTION_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS1, VC1_FE_CONDOVER

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_CONDOVER_MASK		(0x0000000C)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_CONDOVER_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_CONDOVER_SHIFT		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_CONDOVER_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_CONDOVER_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_CONDOVER_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_CONDOVER_ENUM {
	MSVDX_VEC_VC1_VC1_FE_CONDOVER_SOME_MB_SMOOTHING = 0x3,
	MSVDX_VEC_VC1_VC1_FE_CONDOVER_ALL_MB_SMOOTHING = 0x2,
	MSVDX_VEC_VC1_VC1_FE_CONDOVER_RESERVED = 0x1,
	MSVDX_VEC_VC1_VC1_FE_CONDOVER_NO_OVERLAP_SMOOTHING = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS1, VC1_FE_EXTEND_X
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_X_MASK		(0x00000002)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_X_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_X_SHIFT		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_X_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_X_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_X_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_X_ENUM {
	MSVDX_VEC_VC1_VC1_FE_EXTEND_X_EXTENDED_HORIZ_DIFF_RANGE = 0x1,
	MSVDX_VEC_VC1_VC1_FE_EXTEND_X_NO_EXTENDED_HORIZ_DIFF_RANGE = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS1, VC1_FE_EXTEND_Y
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_Y_MASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_Y_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_Y_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_Y_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_Y_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_Y_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS1_VC1_FE_EXTEND_Y_ENUM {
	MSVDX_VEC_VC1_VC1_FE_EXTEND_Y_EXTENDED_VERT_DIFF_RANGE = 0x1,
	MSVDX_VEC_VC1_VC1_FE_EXTEND_Y_NO_EXTENDED_VERT_DIFF_RANGE = 0x0,
};

#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_OFFSET		(0x040C)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS2, VC1_FE_DQXBEDGE

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQXBEDGE_MASK		(0x03000000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQXBEDGE_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQXBEDGE_SHIFT		(24)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQXBEDGE_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQXBEDGE_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQXBEDGE_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS2, VC1_FE_DQUANT
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANT_MASK		(0x00C00000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANT_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANT_SHIFT		(22)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANT_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANT_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS2, VC1_FE_VOPDQUANT_PRESENT
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_VOPDQUANT_PRESENT_MASK		(0x00200000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_VOPDQUANT_PRESENT_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_VOPDQUANT_PRESENT_SHIFT		(21)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_VOPDQUANT_PRESENT_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_VOPDQUANT_PRESENT_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_VOPDQUANT_PRESENT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS2, VC1_FE_PQUANT
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_PQUANT_MASK		(0x001F0000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_PQUANT_LSBMASK		(0x0000001F)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_PQUANT_SHIFT		(16)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_PQUANT_LENGTH		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_PQUANT_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_PQUANT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS2, VC1_FE_HALFQP

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_HALFQP_MASK		(0x00008000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_HALFQP_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_HALFQP_SHIFT		(15)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_HALFQP_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_HALFQP_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_HALFQP_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS2, VC1_FE_DQUANTFRM

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANTFRM_MASK		(0x00004000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANTFRM_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANTFRM_SHIFT		(14)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANTFRM_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANTFRM_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANTFRM_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS2, VC1_FE_DQUANT_INFRAME
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANT_INFRAME_MASK		(0x00002000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANT_INFRAME_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANT_INFRAME_SHIFT		(13)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANT_INFRAME_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANT_INFRAME_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQUANT_INFRAME_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS2, VC1_FE_ALTPQUANT

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_ALTPQUANT_MASK		(0x00001F00)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_ALTPQUANT_LSBMASK		(0x0000001F)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_ALTPQUANT_SHIFT		(8)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_ALTPQUANT_LENGTH		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_ALTPQUANT_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_ALTPQUANT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS2, VC1_FE_DQPROFILE
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQPROFILE_MASK		(0x000000C0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQPROFILE_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQPROFILE_SHIFT		(6)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQPROFILE_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQPROFILE_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQPROFILE_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQPROFILE_ENUM {
	MSVDX_VEC_VC1_VC1_FE_DQPROFILE_ALL_MACROBLOCKS = 0x3,
	MSVDX_VEC_VC1_VC1_FE_DQPROFILE_SINGLE_EDGES = 0x2,
	MSVDX_VEC_VC1_VC1_FE_DQPROFILE_DOUBLE_EDGES = 0x1,
	MSVDX_VEC_VC1_VC1_FE_DQPROFILE_ALL_FOUR_EDGES = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS2, VC1_FE_DQBILEVEL
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQBILEVEL_MASK		(0x00000020)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQBILEVEL_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQBILEVEL_SHIFT		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQBILEVEL_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQBILEVEL_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_DQBILEVEL_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS2, VC1_FE_PQINDEX_GT8

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_PQINDEX_GT8_MASK		(0x00000010)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_PQINDEX_GT8_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_PQINDEX_GT8_SHIFT		(4)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_PQINDEX_GT8_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_PQINDEX_GT8_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_PQINDEX_GT8_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS2, VC1_FE_TRANSACFRM

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM_MASK		(0x0000000C)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM_SHIFT		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM_ENUM {
	MSVDX_VEC_VC1_VC1_FE_TRANSACFRM_RESERVED = 0x3,
	MSVDX_VEC_VC1_VC1_FE_TRANSACFRM_TRANSACFRM_INDEX_2 = 0x2,
	MSVDX_VEC_VC1_VC1_FE_TRANSACFRM_TRANSACFRM_INDEX_1 = 0x1,
	MSVDX_VEC_VC1_VC1_FE_TRANSACFRM_TRANSACFRM_INDEX_0 = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS2, VC1_FE_TRANSACFRM2

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM2_MASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM2_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM2_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM2_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM2_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM2_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS2_VC1_FE_TRANSACFRM2_ENUM {
	MSVDX_VEC_VC1_VC1_FE_TRANSACFRM2_RESERVED = 0x3,
	MSVDX_VEC_VC1_VC1_FE_TRANSACFRM2_TRANSACFRM_INDEX_2 = 0x2,
	MSVDX_VEC_VC1_VC1_FE_TRANSACFRM2_TRANSACFRM_INDEX_1 = 0x1,
	MSVDX_VEC_VC1_VC1_FE_TRANSACFRM2_TRANSACFRM_INDEX_0 = 0x0,
};

#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_OFFSET		(0x0410)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_MVD_LITE0, VC1_FE_MVD_LITE_ENABLE

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_MVD_LITE_ENABLE_MASK		(0x40000000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_MVD_LITE_ENABLE_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_MVD_LITE_ENABLE_SHIFT		(30)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_MVD_LITE_ENABLE_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_MVD_LITE_ENABLE_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_MVD_LITE_ENABLE_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_MVD_LITE_ENABLE_ENUM {
	MSVDX_VEC_VC1_VC1_FE_MVD_LITE_ENABLE_ENABLE = 0x1,
	MSVDX_VEC_VC1_VC1_FE_MVD_LITE_ENABLE_DISABLE = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_MVD_LITE0, VC1_FE_PULLBACK_X

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_PULLBACK_X_MASK		(0x3FFF0000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_PULLBACK_X_LSBMASK		(0x00003FFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_PULLBACK_X_SHIFT		(16)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_PULLBACK_X_LENGTH		(14)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_PULLBACK_X_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_PULLBACK_X_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_MVD_LITE0, VC1_FE_PULLBACK_Y

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_PULLBACK_Y_MASK		(0x00003FFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_PULLBACK_Y_LSBMASK		(0x00003FFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_PULLBACK_Y_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_PULLBACK_Y_LENGTH		(14)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_PULLBACK_Y_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE0_VC1_FE_PULLBACK_Y_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_OFFSET		(0x0414)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_MVD_LITE1, VC1_FE_TFF

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_TFF_MASK		(0x40000000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_TFF_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_TFF_SHIFT		(30)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_TFF_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_TFF_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_TFF_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_MVD_LITE1, VC1_FE_SCAN_INDEX
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_SCAN_INDEX_MASK		(0x38000000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_SCAN_INDEX_LSBMASK		(0x00000007)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_SCAN_INDEX_SHIFT		(27)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_SCAN_INDEX_LENGTH		(3)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_SCAN_INDEX_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_SCAN_INDEX_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_MVD_LITE1, VC1_FE_REFDIST
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_REFDIST_MASK		(0x07C00000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_REFDIST_LSBMASK		(0x0000001F)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_REFDIST_SHIFT		(22)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_REFDIST_LENGTH		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_REFDIST_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_REFDIST_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_MVD_LITE1, VC1_FE_NUMREF

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_NUMREF_MASK		(0x00200000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_NUMREF_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_NUMREF_SHIFT		(21)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_NUMREF_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_NUMREF_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_NUMREF_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_NUMREF_ENUM {
	MSVDX_VEC_VC1_VC1_FE_NUMREF_2_REF = 0x1,
	MSVDX_VEC_VC1_VC1_FE_NUMREF_1_REF = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_MVD_LITE1, VC1_FE_REFFIELD

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_REFFIELD_MASK		(0x00100000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_REFFIELD_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_REFFIELD_SHIFT		(20)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_REFFIELD_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_REFFIELD_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_REFFIELD_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_REFFIELD_ENUM {
	MSVDX_VEC_VC1_VC1_FE_REFFIELD_BOTTOM_FIELD_REF = 0x1,
	MSVDX_VEC_VC1_VC1_FE_REFFIELD_TOP_FIELD_REF = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_MVD_LITE1, VC1_FE_MVRANGE
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_MVRANGE_MASK		(0x000C0000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_MVRANGE_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_MVRANGE_SHIFT		(18)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_MVRANGE_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_MVRANGE_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_MVRANGE_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_MVRANGE_ENUM {
	MSVDX_VEC_VC1_VC1_FE_MVRANGE_3 = 0x3,
	MSVDX_VEC_VC1_VC1_FE_MVRANGE_2 = 0x2,
	MSVDX_VEC_VC1_VC1_FE_MVRANGE_1 = 0x1,
	MSVDX_VEC_VC1_VC1_FE_MVRANGE_DEFAULT0 = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_MVD_LITE1, VC1_FE_HALFPEL_FLAG
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_HALFPEL_FLAG_MASK		(0x00020000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_HALFPEL_FLAG_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_HALFPEL_FLAG_SHIFT		(17)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_HALFPEL_FLAG_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_HALFPEL_FLAG_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_HALFPEL_FLAG_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_HALFPEL_FLAG_ENUM {
	MSVDX_VEC_VC1_VC1_FE_HALFPEL_FLAG_HALF = 0x1,
	MSVDX_VEC_VC1_VC1_FE_HALFPEL_FLAG_QUARTER = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_MVD_LITE1, VC1_FE_BOTTOM_FIELD_FLAG
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_BOTTOM_FIELD_FLAG_MASK		(0x00010000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_BOTTOM_FIELD_FLAG_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_BOTTOM_FIELD_FLAG_SHIFT		(16)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_BOTTOM_FIELD_FLAG_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_BOTTOM_FIELD_FLAG_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_BOTTOM_FIELD_FLAG_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_BOTTOM_FIELD_FLAG_ENUM {
	MSVDX_VEC_VC1_VC1_FE_BOTTOM_FIELD_FLAG_BOTTOM = 0x1,
	MSVDX_VEC_VC1_VC1_FE_BOTTOM_FIELD_FLAG_TOP = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_MVD_LITE1, VC1_FE_ADVANCED_PROFILE
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_ADVANCED_PROFILE_MASK		(0x00008000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_ADVANCED_PROFILE_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_ADVANCED_PROFILE_SHIFT		(15)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_ADVANCED_PROFILE_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_ADVANCED_PROFILE_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_MVD_LITE1_VC1_FE_ADVANCED_PROFILE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR0_OFFSET		(0x0418)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_BITPLANES_BASE_ADDR0, VC1_FE_BITPLANES_BASE_ADDR0
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR0_VC1_FE_BITPLANES_BASE_ADDR0_MASK		(0xFFFFF000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR0_VC1_FE_BITPLANES_BASE_ADDR0_LSBMASK		(0x000FFFFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR0_VC1_FE_BITPLANES_BASE_ADDR0_SHIFT		(12)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR0_VC1_FE_BITPLANES_BASE_ADDR0_LENGTH		(20)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR0_VC1_FE_BITPLANES_BASE_ADDR0_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR0_VC1_FE_BITPLANES_BASE_ADDR0_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR1_OFFSET		(0x041C)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_BITPLANES_BASE_ADDR1, VC1_FE_BITPLANES_BASE_ADDR1
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR1_VC1_FE_BITPLANES_BASE_ADDR1_MASK		(0xFFFFF000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR1_VC1_FE_BITPLANES_BASE_ADDR1_LSBMASK		(0x000FFFFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR1_VC1_FE_BITPLANES_BASE_ADDR1_SHIFT		(12)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR1_VC1_FE_BITPLANES_BASE_ADDR1_LENGTH		(20)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR1_VC1_FE_BITPLANES_BASE_ADDR1_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR1_VC1_FE_BITPLANES_BASE_ADDR1_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR2_OFFSET		(0x0420)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_BITPLANES_BASE_ADDR2, VC1_FE_BITPLANES_BASE_ADDR2
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR2_VC1_FE_BITPLANES_BASE_ADDR2_MASK		(0xFFFFF000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR2_VC1_FE_BITPLANES_BASE_ADDR2_LSBMASK		(0x000FFFFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR2_VC1_FE_BITPLANES_BASE_ADDR2_SHIFT		(12)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR2_VC1_FE_BITPLANES_BASE_ADDR2_LENGTH		(20)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR2_VC1_FE_BITPLANES_BASE_ADDR2_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_BITPLANES_BASE_ADDR2_VC1_FE_BITPLANES_BASE_ADDR2_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS3_OFFSET		(0x0424)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS3, VC1_FE_PARSER_VLR_BASE_ADDR
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS3_VC1_FE_PARSER_VLR_BASE_ADDR_MASK		(0x0FFC0000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS3_VC1_FE_PARSER_VLR_BASE_ADDR_LSBMASK		(0x000003FF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS3_VC1_FE_PARSER_VLR_BASE_ADDR_SHIFT		(18)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS3_VC1_FE_PARSER_VLR_BASE_ADDR_LENGTH		(10)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS3_VC1_FE_PARSER_VLR_BASE_ADDR_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS3_VC1_FE_PARSER_VLR_BASE_ADDR_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_FE_PPS3, VC1_FE_PIC_SIZE_IN_MBS_LESS1
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS3_VC1_FE_PIC_SIZE_IN_MBS_LESS1_MASK		(0x0000FFFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS3_VC1_FE_PIC_SIZE_IN_MBS_LESS1_LSBMASK		(0x0000FFFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS3_VC1_FE_PIC_SIZE_IN_MBS_LESS1_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS3_VC1_FE_PIC_SIZE_IN_MBS_LESS1_LENGTH		(16)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS3_VC1_FE_PIC_SIZE_IN_MBS_LESS1_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_FE_PPS3_VC1_FE_PIC_SIZE_IN_MBS_LESS1_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_OFFSET		(0x0450)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_SPS0, VC1_BE_EXTENDED_DMV
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_EXTENDED_DMV_MASK		(0x00000008)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_EXTENDED_DMV_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_EXTENDED_DMV_SHIFT		(3)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_EXTENDED_DMV_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_EXTENDED_DMV_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_EXTENDED_DMV_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_SPS0, VC1_BE_EXTENDED_MV
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_EXTENDED_MV_MASK		(0x00000004)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_EXTENDED_MV_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_EXTENDED_MV_SHIFT		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_EXTENDED_MV_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_EXTENDED_MV_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_EXTENDED_MV_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_EXTENDED_MV_ENUM {
	MSVDX_VEC_VC1_VC1_BE_EXTENDED_MV_ENABLED = 0x1,
	MSVDX_VEC_VC1_VC1_BE_EXTENDED_MV_DISABLED = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_SPS0, VC1_BE_FASTUVMC
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_FASTUVMC_MASK		(0x00000002)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_FASTUVMC_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_FASTUVMC_SHIFT		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_FASTUVMC_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_FASTUVMC_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_FASTUVMC_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_FASTUVMC_ENUM {
	MSVDX_VEC_VC1_VC1_BE_FASTUVMC_ENABLED = 0x1,
	MSVDX_VEC_VC1_VC1_BE_FASTUVMC_DISABLED = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_SPS0, VC1_BE_INTERLACE
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_INTERLACE_MASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_INTERLACE_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_INTERLACE_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_INTERLACE_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_INTERLACE_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_INTERLACE_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS0_VC1_BE_INTERLACE_ENUM {
	MSVDX_VEC_VC1_VC1_BE_INTERLACE_BOTH = 0x1,
	MSVDX_VEC_VC1_VC1_BE_INTERLACE_PROGRESSIVE = 0x0,
};

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS1_OFFSET		(0x0454)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_SPS1, VC1_BE_PIC_HEIGHT_IN_MBS_LESS1

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS1_VC1_BE_PIC_HEIGHT_IN_MBS_LESS1_MASK		(0x000000FF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS1_VC1_BE_PIC_HEIGHT_IN_MBS_LESS1_LSBMASK		(0x000000FF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS1_VC1_BE_PIC_HEIGHT_IN_MBS_LESS1_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS1_VC1_BE_PIC_HEIGHT_IN_MBS_LESS1_LENGTH		(8)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS1_VC1_BE_PIC_HEIGHT_IN_MBS_LESS1_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS1_VC1_BE_PIC_HEIGHT_IN_MBS_LESS1_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS2_OFFSET		(0x0458)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_SPS2, VC1_BE_PIC_WIDTH_IN_MBS_LESS1

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS2_VC1_BE_PIC_WIDTH_IN_MBS_LESS1_MASK		(0x000000FF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS2_VC1_BE_PIC_WIDTH_IN_MBS_LESS1_LSBMASK		(0x000000FF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS2_VC1_BE_PIC_WIDTH_IN_MBS_LESS1_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS2_VC1_BE_PIC_WIDTH_IN_MBS_LESS1_LENGTH		(8)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS2_VC1_BE_PIC_WIDTH_IN_MBS_LESS1_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_SPS2_VC1_BE_PIC_WIDTH_IN_MBS_LESS1_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_OFFSET		(0x0460)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS2, VC1_BE_COLLOCATED_SKIPPED

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_COLLOCATED_SKIPPED_MASK		(0x00000040)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_COLLOCATED_SKIPPED_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_COLLOCATED_SKIPPED_SHIFT		(6)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_COLLOCATED_SKIPPED_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_COLLOCATED_SKIPPED_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_COLLOCATED_SKIPPED_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS2, VC1_BE_FCM_REF2

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF2_MASK		(0x00000030)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF2_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF2_SHIFT		(4)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF2_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF2_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF2_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS2, VC1_BE_FCM_REF1

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF1_MASK		(0x0000000C)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF1_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF1_SHIFT		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF1_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF1_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF1_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS2, VC1_BE_FCM_REF0

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF0_MASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF0_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF0_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF0_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF0_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS2_VC1_BE_FCM_REF0_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_OFFSET		(0x0464)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS0, VC1_BE_IQ_OVERLAP
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_IQ_OVERLAP_MASK		(0x00004000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_IQ_OVERLAP_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_IQ_OVERLAP_SHIFT		(14)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_IQ_OVERLAP_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_IQ_OVERLAP_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_IQ_OVERLAP_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS0, VC1_BE_UNIFORM_QUANTIZER

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_UNIFORM_QUANTIZER_MASK		(0x00002000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_UNIFORM_QUANTIZER_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_UNIFORM_QUANTIZER_SHIFT		(13)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_UNIFORM_QUANTIZER_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_UNIFORM_QUANTIZER_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_UNIFORM_QUANTIZER_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_UNIFORM_QUANTIZER_ENUM {
	MSVDX_VEC_VC1_VC1_BE_UNIFORM_QUANTIZER_UNIFORM = 0x1,
	MSVDX_VEC_VC1_VC1_BE_UNIFORM_QUANTIZER_DEFAULT = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS0, VC1_BE_TFF_BWD
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_BWD_MASK		(0x00001000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_BWD_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_BWD_SHIFT		(12)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_BWD_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_BWD_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_BWD_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_BWD_ENUM {
	MSVDX_VEC_VC1_VC1_BE_TFF_BWD_TFF = 0x1,
	MSVDX_VEC_VC1_VC1_BE_TFF_BWD_BFF = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS0, VC1_BE_TFF_FWD
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_FWD_MASK		(0x00000800)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_FWD_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_FWD_SHIFT		(11)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_FWD_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_FWD_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_FWD_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_FWD_ENUM {
	MSVDX_VEC_VC1_VC1_BE_TFF_FWD_TFF = 0x1,
	MSVDX_VEC_VC1_VC1_BE_TFF_FWD_BFF = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS0, VC1_BE_TFF

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_MASK		(0x00000400)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_SHIFT		(10)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_TFF_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS0, VC1_BE_SECOND_FIELD

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_SECOND_FIELD_MASK		(0x00000200)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_SECOND_FIELD_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_SECOND_FIELD_SHIFT		(9)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_SECOND_FIELD_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_SECOND_FIELD_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_SECOND_FIELD_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_SECOND_FIELD_ENUM {
	MSVDX_VEC_VC1_VC1_BE_SECOND_FIELD_SECOND_FIELD = 0x1,
	MSVDX_VEC_VC1_VC1_BE_SECOND_FIELD_FIRST_FIELD = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS0, VC1_BE_HALFQP

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_HALFQP_MASK		(0x00000100)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_HALFQP_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_HALFQP_SHIFT		(8)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_HALFQP_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_HALFQP_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_HALFQP_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_HALFQP_ENUM {
	MSVDX_VEC_VC1_VC1_BE_HALFQP_ENABLED = 0x1,
	MSVDX_VEC_VC1_VC1_BE_HALFQP_DISABLED = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS0, VC1_BE_BFRACTION

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_BFRACTION_MASK		(0x000000F8)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_BFRACTION_LSBMASK		(0x0000001F)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_BFRACTION_SHIFT		(3)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_BFRACTION_LENGTH		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_BFRACTION_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_BFRACTION_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS0, VC1_BE_FCM

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_FCM_MASK		(0x00000006)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_FCM_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_FCM_SHIFT		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_FCM_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_FCM_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_FCM_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_FCM_ENUM {
	MSVDX_VEC_VC1_VC1_BE_FCM_VC1_FCM_FLDI = 0x3,
	MSVDX_VEC_VC1_VC1_BE_FCM_VC1_FCM_FRMI = 0x2,
	MSVDX_VEC_VC1_VC1_BE_FCM_RESERVED = 0x1,
	MSVDX_VEC_VC1_VC1_BE_FCM_VC1_FCM_P = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS0, VC1_BE_RNDCTRL

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_RNDCTRL_MASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_RNDCTRL_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_RNDCTRL_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_RNDCTRL_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_RNDCTRL_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_RNDCTRL_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS0_VC1_BE_RNDCTRL_ENUM {
	MSVDX_VEC_VC1_VC1_BE_RNDCTRL_ENABLED = 0x1,
	MSVDX_VEC_VC1_VC1_BE_RNDCTRL_DISABLED = 0x0,
};

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_OFFSET		(0x0468)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS1, VC1_BE_EXTEND_Y
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_Y_MASK		(0x00010000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_Y_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_Y_SHIFT		(16)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_Y_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_Y_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_Y_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_Y_ENUM {
	MSVDX_VEC_VC1_VC1_BE_EXTEND_Y_EXTENDED_VERT_DIFF_RANGE = 0x1,
	MSVDX_VEC_VC1_VC1_BE_EXTEND_Y_NO_EXTENDED_VERT_DIFF_RANGE = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS1, VC1_BE_EXTEND_X
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_X_MASK		(0x00008000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_X_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_X_SHIFT		(15)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_X_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_X_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_X_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_EXTEND_X_ENUM {
	MSVDX_VEC_VC1_VC1_BE_EXTEND_X_EXTENDED_HORIZ_DIFF_RANGE = 0x1,
	MSVDX_VEC_VC1_VC1_BE_EXTEND_X_NO_EXTENDED_HORIZ_DIFF_RANGE = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS1, VC1_BE_QUANTIZER

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_QUANTIZER_MASK		(0x00006000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_QUANTIZER_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_QUANTIZER_SHIFT		(13)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_QUANTIZER_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_QUANTIZER_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_QUANTIZER_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_QUANTIZER_ENUM {
	MSVDX_VEC_VC1_VC1_BE_QUANTIZER_UNIFORM = 0x3,
	MSVDX_VEC_VC1_VC1_BE_QUANTIZER_NON_UNIFORM = 0x2,
	MSVDX_VEC_VC1_VC1_BE_QUANTIZER_EXPLICIT = 0x1,
	MSVDX_VEC_VC1_VC1_BE_QUANTIZER_IMPLICIT = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS1, VC1_BE_PQUANT
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_PQUANT_MASK		(0x00001F00)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_PQUANT_LSBMASK		(0x0000001F)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_PQUANT_SHIFT		(8)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_PQUANT_LENGTH		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_PQUANT_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_PQUANT_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS1, VC1_BE_MVMODE

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE_MASK		(0x000000E0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE_LSBMASK		(0x00000007)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE_SHIFT		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE_LENGTH		(3)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE_ENUM {
	MSVDX_VEC_VC1_VC1_BE_MVMODE_RESERVED1 = 0x7,
	MSVDX_VEC_VC1_VC1_BE_MVMODE_RESERVED0 = 0x6,
	MSVDX_VEC_VC1_VC1_BE_MVMODE_QUARTER_PEL_BICUBIC = 0x5,
	MSVDX_VEC_VC1_VC1_BE_MVMODE_INTENSITY_COMPENSTATION = 0x4,
	MSVDX_VEC_VC1_VC1_BE_MVMODE_MIXED_MV = 0x3,
	MSVDX_VEC_VC1_VC1_BE_MVMODE_1MV_HALF_PEL = 0x2,
	MSVDX_VEC_VC1_VC1_BE_MVMODE_1MV_HALF_PEL_BILINEAR = 0x1,
	MSVDX_VEC_VC1_VC1_BE_MVMODE_1MV = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS1, VC1_BE_MVMODE2

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE2_MASK		(0x00000018)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE2_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE2_SHIFT		(3)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE2_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE2_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE2_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_MVMODE2_ENUM {
	MSVDX_VEC_VC1_VC1_BE_MVMODE2_MIXED_MV = 0x3,
	MSVDX_VEC_VC1_VC1_BE_MVMODE2_1MV_HALF_PEL = 0x2,
	MSVDX_VEC_VC1_VC1_BE_MVMODE2_1MV_HALF_PEL_BILINEAR = 0x1,
	MSVDX_VEC_VC1_VC1_BE_MVMODE2_1MV = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PPS1, VC1_BE_PTYPE

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_PTYPE_MASK		(0x00000007)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_PTYPE_LSBMASK		(0x00000007)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_PTYPE_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_PTYPE_LENGTH		(3)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_PTYPE_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PPS1_VC1_BE_PTYPE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD0_OFFSET		(0x046C)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD0, VC1_BE_BRPD
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD0_VC1_BE_BRPD_MASK		(0x00001F00)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD0_VC1_BE_BRPD_LSBMASK		(0x0000001F)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD0_VC1_BE_BRPD_SHIFT		(8)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD0_VC1_BE_BRPD_LENGTH		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD0_VC1_BE_BRPD_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD0_VC1_BE_BRPD_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD0, VC1_BE_FRPD
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD0_VC1_BE_FRPD_MASK		(0x0000001F)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD0_VC1_BE_FRPD_LSBMASK		(0x0000001F)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD0_VC1_BE_FRPD_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD0_VC1_BE_FRPD_LENGTH		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD0_VC1_BE_FRPD_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD0_VC1_BE_FRPD_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD1_OFFSET		(0x0470)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD1, VC1_BE_SCALEFACTOR
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD1_VC1_BE_SCALEFACTOR_MASK		(0x000007FF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD1_VC1_BE_SCALEFACTOR_LSBMASK		(0x000007FF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD1_VC1_BE_SCALEFACTOR_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD1_VC1_BE_SCALEFACTOR_LENGTH		(11)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD1_VC1_BE_SCALEFACTOR_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD1_VC1_BE_SCALEFACTOR_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD2_OFFSET		(0x0474)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD2, VC1_BE_PULLBACK_X
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD2_VC1_BE_PULLBACK_X_MASK		(0x00003FFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD2_VC1_BE_PULLBACK_X_LSBMASK		(0x00003FFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD2_VC1_BE_PULLBACK_X_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD2_VC1_BE_PULLBACK_X_LENGTH		(14)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD2_VC1_BE_PULLBACK_X_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD2_VC1_BE_PULLBACK_X_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD3_OFFSET		(0x0478)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD3, VC1_BE_PULLBACK_Y
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD3_VC1_BE_PULLBACK_Y_MASK		(0x00003FFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD3_VC1_BE_PULLBACK_Y_LSBMASK		(0x00003FFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD3_VC1_BE_PULLBACK_Y_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD3_VC1_BE_PULLBACK_Y_LENGTH		(14)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD3_VC1_BE_PULLBACK_Y_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD3_VC1_BE_PULLBACK_Y_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD4_OFFSET		(0x047C)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD4, VC1_BE_FIRST_MB_IN_SLICE_Y

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD4_VC1_BE_FIRST_MB_IN_SLICE_Y_MASK		(0x000000FF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD4_VC1_BE_FIRST_MB_IN_SLICE_Y_LSBMASK		(0x000000FF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD4_VC1_BE_FIRST_MB_IN_SLICE_Y_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD4_VC1_BE_FIRST_MB_IN_SLICE_Y_LENGTH		(8)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD4_VC1_BE_FIRST_MB_IN_SLICE_Y_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD4_VC1_BE_FIRST_MB_IN_SLICE_Y_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_OFFSET		(0x0480)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD5, VC1_BE_SCAN_INDEX
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_SCAN_INDEX_MASK		(0x00007000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_SCAN_INDEX_LSBMASK		(0x00000007)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_SCAN_INDEX_SHIFT		(12)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_SCAN_INDEX_LENGTH		(3)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_SCAN_INDEX_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_SCAN_INDEX_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD5, VC1_BE_REFDIST

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_REFDIST_MASK		(0x00000F80)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_REFDIST_LSBMASK		(0x0000001F)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_REFDIST_SHIFT		(7)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_REFDIST_LENGTH		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_REFDIST_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_REFDIST_SIGNED_FIELD	(IMG_FALSE)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD5, VC1_BE_NUMREF

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_NUMREF_MASK		(0x00000040)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_NUMREF_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_NUMREF_SHIFT		(6)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_NUMREF_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_NUMREF_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_NUMREF_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_NUMREF_ENUM {
	MSVDX_VEC_VC1_VC1_BE_NUMREF_2_REF = 0x1,
	MSVDX_VEC_VC1_VC1_BE_NUMREF_1_REF = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD5, VC1_BE_REFFIELD

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_REFFIELD_MASK		(0x00000020)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_REFFIELD_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_REFFIELD_SHIFT		(5)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_REFFIELD_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_REFFIELD_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_REFFIELD_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_REFFIELD_ENUM {
	MSVDX_VEC_VC1_VC1_BE_REFFIELD_BOTTOM_FIELD_REF = 0x1,
	MSVDX_VEC_VC1_VC1_BE_REFFIELD_TOP_FIELD_REF = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD5, VC1_BE_MVRANGE

*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_MVRANGE_MASK		(0x00000018)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_MVRANGE_LSBMASK		(0x00000003)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_MVRANGE_SHIFT		(3)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_MVRANGE_LENGTH		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_MVRANGE_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_MVRANGE_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_MVRANGE_ENUM {
	MSVDX_VEC_VC1_VC1_BE_MVRANGE_3 = 0x3,
	MSVDX_VEC_VC1_VC1_BE_MVRANGE_2 = 0x2,
	MSVDX_VEC_VC1_VC1_BE_MVRANGE_1 = 0x1,
	MSVDX_VEC_VC1_VC1_BE_MVRANGE_0 = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD5, VC1_BE_HALFPEL_FLAG
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_HALFPEL_FLAG_MASK		(0x00000004)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_HALFPEL_FLAG_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_HALFPEL_FLAG_SHIFT		(2)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_HALFPEL_FLAG_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_HALFPEL_FLAG_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_HALFPEL_FLAG_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_HALFPEL_FLAG_ENUM {
	MSVDX_VEC_VC1_VC1_BE_HALFPEL_FLAG_HALF = 0x1,
	MSVDX_VEC_VC1_VC1_BE_HALFPEL_FLAG_QUARTER = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD5, VC1_BE_BOTTOM_FIELD_FLAG
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_BOTTOM_FIELD_FLAG_MASK		(0x00000002)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_BOTTOM_FIELD_FLAG_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_BOTTOM_FIELD_FLAG_SHIFT		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_BOTTOM_FIELD_FLAG_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_BOTTOM_FIELD_FLAG_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_BOTTOM_FIELD_FLAG_SIGNED_FIELD	(IMG_FALSE)

enum MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_BOTTOM_FIELD_FLAG_ENUM {
	MSVDX_VEC_VC1_VC1_BE_BOTTOM_FIELD_FLAG_BOTTOM = 0x1,
	MSVDX_VEC_VC1_VC1_BE_BOTTOM_FIELD_FLAG_TOP = 0x0,
};

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_MVD5, VC1_BE_ADVANCED_PROFILE
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_ADVANCED_PROFILE_MASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_ADVANCED_PROFILE_LSBMASK		(0x00000001)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_ADVANCED_PROFILE_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_ADVANCED_PROFILE_LENGTH		(1)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_ADVANCED_PROFILE_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_MVD5_VC1_BE_ADVANCED_PROFILE_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PARAM_BASE_ADDR_OFFSET		(0x04EC)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_PARAM_BASE_ADDR, VC1_BE_PARAM_BASE_ADDRESS
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PARAM_BASE_ADDR_VC1_BE_PARAM_BASE_ADDRESS_MASK		(0xFFFFF000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PARAM_BASE_ADDR_VC1_BE_PARAM_BASE_ADDRESS_LSBMASK		(0x000FFFFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PARAM_BASE_ADDR_VC1_BE_PARAM_BASE_ADDRESS_SHIFT		(12)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PARAM_BASE_ADDR_VC1_BE_PARAM_BASE_ADDRESS_LENGTH		(20)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PARAM_BASE_ADDR_VC1_BE_PARAM_BASE_ADDRESS_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_PARAM_BASE_ADDR_VC1_BE_PARAM_BASE_ADDRESS_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_COLPARAM_BASE_ADDR_OFFSET		(0x04F8)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BE_COLPARAM_BASE_ADDR, VC1_BE_COLPARAM_BASE_ADDRESS
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_COLPARAM_BASE_ADDR_VC1_BE_COLPARAM_BASE_ADDRESS_MASK		(0xFFFFF000)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_COLPARAM_BASE_ADDR_VC1_BE_COLPARAM_BASE_ADDRESS_LSBMASK		(0x000FFFFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_COLPARAM_BASE_ADDR_VC1_BE_COLPARAM_BASE_ADDRESS_SHIFT		(12)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_COLPARAM_BASE_ADDR_VC1_BE_COLPARAM_BASE_ADDRESS_LENGTH		(20)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_COLPARAM_BASE_ADDR_VC1_BE_COLPARAM_BASE_ADDRESS_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BE_COLPARAM_BASE_ADDR_VC1_BE_COLPARAM_BASE_ADDRESS_SIGNED_FIELD	(IMG_FALSE)

#define MSVDX_VEC_VC1_CR_VEC_VC1_BP_READ_OFFSET		(0x0500)

/* MSVDX_VEC_VC1, CR_VEC_VC1_BP_READ, VC1_BP_READ
*/
#define MSVDX_VEC_VC1_CR_VEC_VC1_BP_READ_VC1_BP_READ_MASK		(0x0000FFFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BP_READ_VC1_BP_READ_LSBMASK		(0x0000FFFF)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BP_READ_VC1_BP_READ_SHIFT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BP_READ_VC1_BP_READ_LENGTH		(16)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BP_READ_VC1_BP_READ_DEFAULT		(0)
#define MSVDX_VEC_VC1_CR_VEC_VC1_BP_READ_VC1_BP_READ_SIGNED_FIELD	(IMG_FALSE)



#ifdef __cplusplus
}
#endif

#endif /* __MSVDX_VEC_VC1_REG_IO2_H__ */
