#include <mach/mt_gpio_def.h>

static const struct mt_pin_desc mt_pin_desc_tbl[] = {
{ .pin = "MSDC0_DAT7", .pad = "D21",
.drv_grp = "MSDC0", .chip = "mt8135",
.modes = { "GPIO0", "MSDC0_DAT7", "EINT49", "I2SOUT_DAT",
"DAC_DAT_OUT", "PCM1_DO", "SPI1_MO", "NALE" }, },
{ .pin = "MSDC0_DAT6", .pad = "D22",
.drv_grp = "MSDC0", .chip = "mt8135",
.modes = { "GPIO1", "MSDC0_DAT6", "EINT48", "I2SIN_WS",
"DAC_WS", "PCM1_WS", "SPI1_CSN", "NCLE" }, },
{ .pin = "MSDC0_DAT5", .pad = "E22",
.drv_grp = "MSDC0", .chip = "mt8135",
.modes = { "GPIO2", "MSDC0_DAT5", "EINT47", "I2SIN_CK",
"DAC_CK", "PCM1_CK", "SPI1_CLK", "NLD4" }, },
{ .pin = "MSDC0_DAT4", .pad = "F21",
.drv_grp = "MSDC0", .chip = "mt8135",
.modes = { "GPIO3", "MSDC0_DAT4", "EINT46", "A_FUNC_CK",
NULL, NULL, "LSCE1B_2X", "NLD5" }, },
{ .pin = "MSDC0_CMD", .pad = "F20",
.drv_grp = "MSDC0CM", .chip = "mt8135",
.modes = { "GPIO4", "MSDC0_CMD", "EINT41", "A_FUNC_DOUT[0]",
NULL, "USB_TEST_IO[0]", "LRSTB_2X", "NRNB" }, },
{ .pin = "MSDC0_CLK", .pad = "G18",
.drv_grp = "MSDC0CK", .chip = "mt8135",
.modes = { "GPIO5", "MSDC0_CLK", "EINT40", "A_FUNC_DOUT[1]",
NULL, "USB_TEST_IO[1]", "LPTE", "NREB" }, },
{ .pin = "MSDC0_DAT3", .pad = "G21",
.drv_grp = "MSDC0", .chip = "mt8135",
.modes = { "GPIO6", "MSDC0_DAT3", "EINT45", "A_FUNC_DOUT[2]",
NULL, "USB_TEST_IO[2]", "LSCE0B_2X", "NLD7" }, },
{ .pin = "MSDC0_DAT2", .pad = "E21",
.drv_grp = "MSDC0", .chip = "mt8135",
.modes = { "GPIO7", "MSDC0_DAT2", "EINT44", "A_FUNC_DOUT[3]",
NULL, "USB_TEST_IO[3]", "LSA0_2X", "NLD14" }, },
{ .pin = "MSDC0_DAT1", .pad = "E23",
.drv_grp = "MSDC0", .chip = "mt8135",
.modes = { "GPIO8", "MSDC0_DAT1", "EINT43", NULL,
NULL, "USB_TEST_IO[4]", "LSCK_2X", "NLD11" }, },
{ .pin = "MSDC0_DAT0", .pad = "F22",
.drv_grp = "MSDC0", .chip = "mt8135",
.modes = { "GPIO9", "MSDC0_DAT0", "EINT42", NULL,
NULL, "USB_TEST_IO[5]", "LSDA_2X", NULL }, },
{ .pin = "NCEB0", .pad = "G20",
.drv_grp = "NFI", .chip = "mt8135",
.modes = { "GPIO10", "NCEB0", "EINT139", NULL,
NULL, NULL, NULL, "TESTA_OUT4" }, },
{ .pin = "NCEB1", .pad = "L17",
.drv_grp = "NFI", .chip = "mt8135",
.modes = { "GPIO11", "NCEB1", "EINT140", NULL,
NULL, NULL, "USB_DRVVBUS", "TESTA_OUT5" }, },
{ .pin = "NRNB", .pad = "G19",
.drv_grp = "NFI", .chip = "mt8135",
.modes = { "GPIO12", "NRNB", "EINT141", "A_FUNC_DOUT[4]",
NULL, NULL, NULL, "TESTA_OUT6" }, },
{ .pin = "NCLE", .pad = "J18",
.drv_grp = "NFI", .chip = "mt8135",
.modes = { "GPIO13", "NCLE", "EINT142", "A_FUNC_DOUT[5]",
"CM2PDN_1X", NULL, "NALE", "TESTA_OUT7" }, },
{ .pin = "NALE", .pad = "J19",
.drv_grp = "NFI", .chip = "mt8135",
.modes = { "GPIO14", "NALE", "EINT143", "A_FUNC_DOUT[6]",
"CM2MCLK_1X", "IRDA_RXD", "NCLE", "TESTA_OUT8" }, },
{ .pin = "NREB", .pad = "L18",
.drv_grp = "NFI", .chip = "mt8135",
.modes = { "GPIO15", "NREB", "EINT144", "A_FUNC_DOUT[7]",
"CM2RST_1X", "IRDA_TXD", NULL, "TESTA_OUT9" }, },
{ .pin = "NWEB", .pad = "J20",
.drv_grp = "NFI", .chip = "mt8135",
.modes = { "GPIO16", "NWEB", "EINT145", "A_FUNC_DIN[0]",
"CM2PCLK_1X", "IRDA_PDN", NULL, "TESTA_OUT10" }, },
{ .pin = "NLD0", .pad = "K21",
.drv_grp = "NLD_0", .chip = "mt8135",
.modes = { "GPIO17", "NLD0", "EINT146", "A_FUNC_DIN[1]",
"CM2DAT_1X[0]", "I2SIN_CK", "DAC_CK", "TESTA_OUT11" }, },
{ .pin = "NLD1", .pad = "K22",
.drv_grp = "NLD_0", .chip = "mt8135",
.modes = { "GPIO18", "NLD1", "EINT147", "A_FUNC_DIN[2]",
"CM2DAT_1X[1]", "I2SIN_WS", "DAC_WS", "TESTA_OUT12" }, },
{ .pin = "NLD2", .pad = "J21",
.drv_grp = "NLD_0", .chip = "mt8135",
.modes = { "GPIO19", "NLD2", "EINT148", "A_FUNC_DIN[3]",
"CM2DAT_1X[2]", "I2SOUT_DAT", "DAC_DAT_OUT", "TESTA_OUT13" }, },
{ .pin = "NLD3", .pad = "J23",
.drv_grp = "NLD_0", .chip = "mt8135",
.modes = { "GPIO20", "NLD3", "EINT149", "A_FUNC_DIN[4]",
"CM2DAT_1X[3]", NULL, NULL, "TESTA_OUT14" }, },
{ .pin = "NLD4", .pad = "J22",
.drv_grp = "NLD_0", .chip = "mt8135",
.modes = { "GPIO21", "NLD4", "EINT150", "A_FUNC_DIN[5]",
"CM2DAT_1X[4]", NULL, NULL, "TESTA_OUT15" }, },
{ .pin = "NLD5", .pad = "H21",
.drv_grp = "NLD_0", .chip = "mt8135",
.modes = { "GPIO22", "NLD5", "EINT151", "A_FUNC_DIN[6]",
"CM2DAT_1X[5]", NULL, NULL, "TESTA_OUT16" }, },
{ .pin = "NLD6", .pad = "H22",
.drv_grp = "NLD_0", .chip = "mt8135",
.modes = { "GPIO23", "NLD6", "EINT152", "A_FUNC_DIN[7]",
"CM2DAT_1X[6]", NULL, NULL, "TESTA_OUT17" }, },
{ .pin = "NLD7", .pad = "H20",
.drv_grp = "NLD_0", .chip = "mt8135",
.modes = { "GPIO24", "NLD7", "EINT153", "A_FUNC_DIN[8]",
"CM2DAT_1X[7]", NULL, NULL, "TESTA_OUT18" }, },
{ .pin = "NLD8", .pad = NULL,
.drv_grp = "NLD_1", .chip = "mt8135",
.modes = { "GPIO25", "NLD8", "EINT154", NULL,
"CM2DAT_1X[8]", NULL, NULL, NULL }, },
{ .pin = "NLD9", .pad = NULL,
.drv_grp = "NLD_1", .chip = "mt8135",
.modes = { "GPIO26", "NLD9", "EINT155", NULL,
"CM2DAT_1X[9]", "PWM1", NULL, NULL }, },
{ .pin = "NLD10", .pad = NULL,
.drv_grp = "NLD_1", .chip = "mt8135",
.modes = { "GPIO27", "NLD10", "EINT156", NULL,
"CM2VSYNC_1X", "PWM2", NULL, NULL }, },
{ .pin = "NLD11", .pad = NULL,
.drv_grp = "NLD_1", .chip = "mt8135",
.modes = { "GPIO28", "NLD11", "EINT157", NULL,
"CM2HSYNC_1X", "PWM3", NULL, NULL }, },
{ .pin = "NLD12", .pad = NULL,
.drv_grp = "NLD_1", .chip = "mt8135",
.modes = { "GPIO29", "NLD12", "EINT158", "I2SIN_CK",
"DAC_CK", "PCM1_CK", NULL, NULL }, },
{ .pin = "NLD13", .pad = NULL,
.drv_grp = "NLD_1", .chip = "mt8135",
.modes = { "GPIO30", "NLD13", "EINT159", "I2SIN_WS",
"DAC_WS", "PCM1_WS", NULL, NULL }, },
{ .pin = "NLD14", .pad = NULL,
.drv_grp = "NLD_1", .chip = "mt8135",
.modes = { "GPIO31", "NLD14", "EINT160", "I2SOUT_DAT",
"DAC_DAT_OUT", "PCM1_DO", NULL, NULL }, },
{ .pin = "NLD15", .pad = NULL,
.drv_grp = "NLD_1", .chip = "mt8135",
.modes = { "GPIO32", "NLD15", "EINT161", "DISP_PWM",
"PWM4", "PCM1_DI", NULL, NULL }, },
{ .pin = "MSDC0_RSTB", .pad = "G22",
.drv_grp = "MSDC0RSTB", .chip = "mt8135",
.modes = { "GPIO33", "MSDC0_RSTB", "EINT50", "I2SIN_DAT",
NULL, "PCM1_DI", "SPI1_MI", "NLD10" }, },
{ .pin = "IDDIG", .pad = "N17",
.drv_grp = "GPIO_1", .chip = "mt8135",
.modes = { "GPIO34", "IDDIG", "EINT34", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "SCL3", .pad = "L19",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO35", "SCL3", "EINT96", "CLKM6",
"PWM6", NULL, NULL, NULL }, },
{ .pin = "SDA3", .pad = "L20",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO36", "SDA3", "EINT97", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "AUD_CLK_MOSI", .pad = "L21",
.drv_grp = "ADC", .chip = "mt8135",
.modes = { "GPIO37", "AUD_CLK", "ADC_CK", " HDMI_SDATA0",
"EINT19", "USB_TEST_IO[6]", NULL, "TESTA_OUT19" }, },
{ .pin = "AUD_DAT_MOSI", .pad = "L23",
.drv_grp = "ADC", .chip = "mt8135",
.modes = { "GPIO38", "AUD_DAT_MOSI", "ADC_WS", "AUD_DAT_MISO",
"EINT21", "USB_TEST_IO[7]", NULL, "TESTA_OUT20" }, },
{ .pin = "AUD_DAT_MISO", .pad = "L22",
.drv_grp = "ADC", .chip = "mt8135",
.modes = { "GPIO39", "AUD_DAT_MISO", "ADC_DAT_IN", "AUD_DAT_MOSI",
"EINT20", "USB_TEST_IO[8]", NULL, "TESTA_OUT21" }, },
{ .pin = "DAC_CLK", .pad = "P21",
.drv_grp = "DAC", .chip = "mt8135",
.modes = { "GPIO40", "DAC_CK", "EINT22", " HDMI_SDATA1",
NULL, "USB_TEST_IO[9]", NULL, "TESTA_OUT22" }, },
{ .pin = "DAC_WS", .pad = "N18",
.drv_grp = "DAC", .chip = "mt8135",
.modes = { "GPIO41", "DAC_WS", "EINT24", " HDMI_SDATA2",
NULL, "USB_TEST_IO[10]", NULL, "TESTA_OUT23" }, },
{ .pin = "DAC_DAT_OUT", .pad = "N22",
.drv_grp = "DAC", .chip = "mt8135",
.modes = { "GPIO42", "DAC_DAT_OUT", "EINT23", " HDMI_SDATA3",
NULL, "USB_TEST_IO[11]", NULL, "TESTA_OUT24" }, },
{ .pin = "PWRAP_SPI0_MO", .pad = "M22",
.drv_grp = "SPI0", .chip = "mt8135",
.modes = { "GPIO43", "PWRAP_SPIDI", "EINT29", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "PWRAP_SPI0_MI", .pad = "P23",
.drv_grp = "SPI0", .chip = "mt8135",
.modes = { "GPIO44", "PWRAP_SPIDO", "EINT28", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "PWRAP_SPI0_CSN", .pad = "M21",
.drv_grp = "SPI0", .chip = "mt8135",
.modes = { "GPIO45", "PWRAP_SPICS_B_I", "EINT27", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "PWRAP_SPI0_CLK", .pad = "P22",
.drv_grp = "SPI0", .chip = "mt8135",
.modes = { "GPIO46", "PWRAP_SPICK_I", "EINT26", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "PWRAP_EVENT", .pad = "M23",
.drv_grp = "SPI0", .chip = "mt8135",
.modes = { "GPIO47", "PWRAP_EVENT_IN", "EINT25", NULL,
NULL, NULL, NULL, "TESTA_OUT2" }, },
{ .pin = "RTC32K_CK", .pad = "N20",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO48", "RTC32K_CK", NULL, NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "WATCHDOG", .pad = "R22",
.drv_grp = "GPIO_2", .chip = "mt8135",
.modes = { "GPIO49", "WATCHDOG", "EINT36", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "SRCLKENA", .pad = "T22",
.drv_grp = "GPIO_3", .chip = "mt8135",
.modes = { "GPIO50", "SRCLKENA", "EINT38", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "SRCVOLTEN", .pad = "T23",
.drv_grp = "GPIO_4", .chip = "mt8135",
.modes = { "GPIO51", "SRCVOLTEN", "EINT37", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "EINT0", .pad = "T21",
.drv_grp = "EINT0", .chip = "mt8135",
.modes = { "GPIO52", "EINT0", "PWM1", "CLKM0",
" SPDIF_OUT", "USB_TEST_IO[12]", NULL, "USB_SCL" }, },
{ .pin = "URXD2", .pad = "R18",
.drv_grp = "UR2_0", .chip = "mt8135",
.modes = { "GPIO53", "URXD2", "EINT83", NULL,
" HDMI_LRCK", "CLKM3", NULL, "UTXD2" }, },
{ .pin = "UTXD2", .pad = "R17",
.drv_grp = "UR2_1", .chip = "mt8135",
.modes = { "GPIO54", "UTXD2", "EINT82", NULL,
" HDMI_BCK_OUT", "CLKM2", NULL, "URXD2" }, },
{ .pin = "UCTS2", .pad = "R20",
.drv_grp = "UR2_2", .chip = "mt8135",
.modes = { "GPIO55", "UCTS2", "EINT84", NULL,
NULL, "PWM1", NULL, "URTS2" }, },
{ .pin = "URTS2", .pad = "R19",
.drv_grp = "UR2_3", .chip = "mt8135",
.modes = { "GPIO56", "URTS2", "EINT85", NULL,
NULL, "PWM2", NULL, "UCTS2" }, },
{ .pin = "JTCK", .pad = "V17",
.drv_grp = "JTAG", .chip = "mt8135",
.modes = { "GPIO57", "JTCK", "EINT188", "DSP1_ICK",
NULL, NULL, NULL, NULL }, },
{ .pin = "JTDO", .pad = "T16",
.drv_grp = "JTAG", .chip = "mt8135",
.modes = { "GPIO58", "JTDO", "EINT190", "DSP2_IMS",
NULL, NULL, NULL, NULL }, },
{ .pin = "JTRST_B", .pad = "T19",
.drv_grp = "JTAG", .chip = "mt8135",
.modes = { "GPIO59", "JTRST_B", "EINT0", "DSP2_ICK",
NULL, NULL, NULL, NULL }, },
{ .pin = "JTDI", .pad = "T18",
.drv_grp = "JTAG", .chip = "mt8135",
.modes = { "GPIO60", "JTDI", "EINT189", "DSP1_IMS",
NULL, NULL, NULL, NULL }, },
{ .pin = "JRTCK", .pad = "T20",
.drv_grp = "JTAG", .chip = "mt8135",
.modes = { "GPIO61", "JRTCK", "EINT187", "DSP1_ID",
NULL, NULL, NULL, NULL }, },
{ .pin = "JTMS", .pad = "T17",
.drv_grp = "JTAG", .chip = "mt8135",
.modes = { "GPIO62", "JTMS", "EINT191", "DSP2_ID",
NULL, NULL, NULL, NULL }, },
{ .pin = "MSDC1_INSI", .pad = "V18",
.drv_grp = "MSDC1INSI", .chip = "mt8135",
.modes = { "GPIO63", "MSDC1_INSI", "EINT57", "SCL5",
"PWM6", "CLKM5", NULL, "TESTB_OUT6" }, },
{ .pin = "MSDC1_SDWPI", .pad = "W18",
.drv_grp = "MSDC1SDWPI", .chip = "mt8135",
.modes = { "GPIO64", "MSDC1_SDWPI", "EINT58", "SDA5",
"PWM7", "CLKM6", NULL, "TESTB_OUT7" }, },
{ .pin = "MSDC2_INSI", .pad = "U22",
.drv_grp = "MSDC2INSI", .chip = "mt8135",
.modes = { "GPIO65", "MSDC2_INSI", "EINT65", NULL,
NULL, "USB_TEST_IO[27]", NULL, "TESTA_OUT3" }, },
{ .pin = "MSDC2_SDWPI", .pad = "U21",
.drv_grp = "MSDC2SDWPI", .chip = "mt8135",
.modes = { "GPIO66", "MSDC2_SDWPI", "EINT66", NULL,
NULL, "USB_TEST_IO[28]", NULL, NULL }, },
{ .pin = "URXD4", .pad = "V23",
.drv_grp = "UR4_0", .chip = "mt8135",
.modes = { "GPIO67", "URXD4", "EINT89", "URXD1",
NULL, NULL, "UTXD4", "TESTB_OUT10" }, },
{ .pin = "UTXD4", .pad = "V22",
.drv_grp = "UR4_1", .chip = "mt8135",
.modes = { "GPIO68", "UTXD4", "EINT88", "UTXD1",
NULL, NULL, "URXD4", "TESTB_OUT11" }, },
{ .pin = "URXD1", .pad = "W22",
.drv_grp = "UR1_0", .chip = "mt8135",
.modes = { "GPIO69", "URXD1", "EINT79", "URXD4",
NULL, NULL, "UTXD1", "TESTB_OUT24" }, },
{ .pin = "UTXD1", .pad = "V21",
.drv_grp = "UR1_1", .chip = "mt8135",
.modes = { "GPIO70", "UTXD1", "EINT78", "UTXD4",
NULL, NULL, "URXD1", "TESTB_OUT25" }, },
{ .pin = "UCTS1", .pad = "V19",
.drv_grp = "UR1_2", .chip = "mt8135",
.modes = { "GPIO71", "UCTS1", "EINT80", NULL,
NULL, "CLKM0", "URTS1", "TESTB_OUT31" }, },
{ .pin = "URTS1", .pad = "V20",
.drv_grp = "UR1_3", .chip = "mt8135",
.modes = { "GPIO72", "URTS1", "EINT81", NULL,
NULL, "CLKM1", "UCTS1", "TESTB_OUT21" }, },
{ .pin = "PWM1", .pad = "W17",
.drv_grp = "PWM1", .chip = "mt8135",
.modes = { "GPIO73", "PWM1", "EINT73", NULL,
NULL, "USB_DRVVBUS", "DISP_PWM", "TESTB_OUT8" }, },
{ .pin = "PWM2", .pad = "Y17",
.drv_grp = "PWM2", .chip = "mt8135",
.modes = { "GPIO74", "PWM2", "EINT74", "DPI33_CK",
"PWM5", "URXD2", "DISP_PWM", "TESTB_OUT9" }, },
{ .pin = "PWM3", .pad = "Y19",
.drv_grp = "PWM3", .chip = "mt8135",
.modes = { "GPIO75", "PWM3", "EINT75", "DPI33_D0",
"PWM6", "UTXD2", "DISP_PWM", "TESTB_OUT12" }, },
{ .pin = "PWM4", .pad = "W19",
.drv_grp = "PWM4", .chip = "mt8135",
.modes = { "GPIO76", "PWM4", "EINT76", "DPI33_D1",
"PWM7", NULL, "DISP_PWM", "TESTB_OUT13" }, },
{ .pin = "MSDC2_DAT2", .pad = "W21",
.drv_grp = "MSDC2", .chip = "mt8135",
.modes = { "GPIO77", "MSDC2_DAT2", "EINT63", NULL,
"DSP2_IMS", NULL, "DPI33_D6", "TESTA_OUT25" }, },
{ .pin = "MSDC2_DAT3", .pad = "AA23",
.drv_grp = "MSDC2", .chip = "mt8135",
.modes = { "GPIO78", "MSDC2_DAT3", "EINT64", NULL,
"DSP2_ID", NULL, "DPI33_D7", "TESTA_OUT26" }, },
{ .pin = "MSDC2_CMD", .pad = "Y22",
.drv_grp = "MSDC2CM", .chip = "mt8135",
.modes = { "GPIO79", "MSDC2_CMD", "EINT60", NULL,
"DSP1_IMS", "PCM1_WS", "DPI33_D3", "TESTA_OUT0" }, },
{ .pin = "MSDC2_CLK", .pad = "AA22",
.drv_grp = "MSDC2CK", .chip = "mt8135",
.modes = { "GPIO80", "MSDC2_CLK", "EINT59", NULL,
"DSP1_ICK", "PCM1_CK", "DPI33_D2", "TESTA_OUT1" }, },
{ .pin = "MSDC2_DAT1", .pad = "Y21",
.drv_grp = "MSDC2", .chip = "mt8135",
.modes = { "GPIO81", "MSDC2_DAT1", "EINT62", NULL,
"DSP2_ICK", "PCM1_DO", "DPI33_D5", NULL }, },
{ .pin = "MSDC2_DAT0", .pad = "AB22",
.drv_grp = "MSDC2", .chip = "mt8135",
.modes = { "GPIO82", "MSDC2_DAT0", "EINT61", NULL,
"DSP1_ID", "PCM1_DI", "DPI33_D4", NULL }, },
{ .pin = "MSDC1_DAT0", .pad = "AC19",
.drv_grp = "MSDC1", .chip = "mt8135",
.modes = { "GPIO83", "MSDC1_DAT0", "EINT53", "SCL1",
"PWM2", "CLKM1", NULL, "TESTB_OUT2" }, },
{ .pin = "MSDC1_DAT1", .pad = "AA19",
.drv_grp = "MSDC1", .chip = "mt8135",
.modes = { "GPIO84", "MSDC1_DAT1", "EINT54", "SDA1",
"PWM3", "CLKM2", NULL, "TESTB_OUT3" }, },
{ .pin = "MSDC1_CMD", .pad = "AA20",
.drv_grp = "MSDC1CM", .chip = "mt8135",
.modes = { "GPIO85", "MSDC1_CMD", "EINT52", "SDA0",
"PWM1", "CLKM0", NULL, "TESTB_OUT1" }, },
{ .pin = "MSDC1_CLK", .pad = "AB19",
.drv_grp = "MSDC1CK", .chip = "mt8135",
.modes = { "GPIO86", "MSDC1_CLK", "EINT51", "SCL0",
"DISP_PWM", NULL, NULL, "TESTB_OUT0" }, },
{ .pin = "MSDC1_DAT2", .pad = "AA21",
.drv_grp = "MSDC1", .chip = "mt8135",
.modes = { "GPIO87", "MSDC1_DAT2", "EINT55", "SCL4",
"PWM4", "CLKM3", NULL, "TESTB_OUT4" }, },
{ .pin = "MSDC1_DAT3", .pad = "AB20",
.drv_grp = "MSDC1", .chip = "mt8135",
.modes = { "GPIO88", "MSDC1_DAT3", "EINT56", "SDA4",
"PWM5", "CLKM4", NULL, "TESTB_OUT5" }, },
{ .pin = "MSDC4_DAT0", .pad = "AB8",
.drv_grp = "LCD_0", .chip = "mt8135",
.modes = { "GPIO89", "MSDC4_DAT0", "EINT133", NULL,
"EXT_FRAME_SYNC", "USB_DRVVBUS", "A_FUNC_DIN[9]", "LPTE" }, },
{ .pin = "MSDC4_DAT1", .pad = "AB7",
.drv_grp = "LCD_0", .chip = "mt8135",
.modes = { "GPIO90", "MSDC4_DAT1", "EINT134", NULL,
NULL, NULL, "A_FUNC_DIN[10]", "LRSTB_1X" }, },
{ .pin = "MSDC4_DAT5", .pad = "AA8",
.drv_grp = "LCD_0", .chip = "mt8135",
.modes = { "GPIO91", "MSDC4_DAT5", "EINT136", "I2SIN_WS",
"DAC_WS", "PCM1_WS", "A_FUNC_DIN[11]", "SPI1_CSN" }, },
{ .pin = "MSDC4_DAT6", .pad = "AC4",
.drv_grp = "LCD_0", .chip = "mt8135",
.modes = { "GPIO92", "MSDC4_DAT6", "EINT137", "I2SOUT_DAT",
"DAC_DAT_OUT", "PCM1_DO", "A_FUNC_DIN[12]", "SPI1_MO" }, },
{ .pin = "MSDC4_DAT7", .pad = "AC6",
.drv_grp = "LCD_0", .chip = "mt8135",
.modes = { "GPIO93", "MSDC4_DAT7", "EINT138", "I2SIN_DAT",
NULL, "PCM1_DI", "A_FUNC_DIN[13]", "SPI1_MI" }, },
{ .pin = "MSDC4_DAT4", .pad = "AA7",
.drv_grp = "LCD_0", .chip = "mt8135",
.modes = { "GPIO94", "MSDC4_DAT4", "EINT135", "I2SIN_CK",
"DAC_CK", "PCM1_CK", "A_FUNC_DIN[14]", "SPI1_CLK" }, },
{ .pin = "MSDC4_DAT2", .pad = "AB6",
.drv_grp = "LCD_0", .chip = "mt8135",
.modes = { "GPIO95", "MSDC4_DAT2", "EINT131", "I2SIN_WS",
"CM2PDN_2X", "DAC_WS", "PCM1_WS", "LSCE0B_1X" }, },
{ .pin = "MSDC4_CLK", .pad = "AB5",
.drv_grp = "MSDC4CK", .chip = "mt8135",
.modes = { "GPIO96", "MSDC4_CLK", "EINT129", "DPI1_CK_2X",
"CM2PCLK_2X", "PWM4", "PCM1_DI", "LSCK_1X" }, },
{ .pin = "MSDC4_DAT3", .pad = "Y8",
.drv_grp = "LCD_0", .chip = "mt8135",
.modes = { "GPIO97", "MSDC4_DAT3", "EINT132", "I2SOUT_DAT",
"CM2RST_2X", "DAC_DAT_OUT", "PCM1_DO", "LSCE1B_1X" }, },
{ .pin = "MSDC4_CMD", .pad = "AC3",
.drv_grp = "SLCD_2", .chip = "mt8135",
.modes = { "GPIO98", "MSDC4_CMD", "EINT128", "DPI1_DE_2X",
NULL, "PWM3", NULL, "LSDA_1X" }, },
{ .pin = "MSDC4_RSTB", .pad = "AB4",
.drv_grp = "SLCD_3", .chip = "mt8135",
.modes = { "GPIO99", "MSDC4_RSTB", "EINT130", "I2SIN_CK",
"CM2MCLK_2X", "DAC_CK", "PCM1_CK", "LSA0_1X" }, },
{ .pin = "SDA0", .pad = "W9",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO100", "SDA0", "EINT91", "CLKM1",
"PWM1", NULL, NULL, "A_FUNC_DIN[15]" }, },
{ .pin = "SCL0", .pad = "W11",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO101", "SCL0", "EINT90", "CLKM0",
"DISP_PWM", NULL, NULL, "A_FUNC_DIN[16]" }, },
{ .pin = "EINT10_AUXIN2", .pad = "AA3",
.drv_grp = "GPIO_8", .chip = "mt8135",
.modes = { "GPIO102", "EINT10", NULL, NULL,
NULL, "USB_TEST_IO[16]", "TESTB_OUT16", "A_FUNC_DIN[17]" }, },
{ .pin = "EINT11_AUXIN3", .pad = "AB2",
.drv_grp = "GPIO_9", .chip = "mt8135",
.modes = { "GPIO103", "EINT11", NULL, NULL,
NULL, "USB_TEST_IO[17]", "TESTB_OUT17", "A_FUNC_DIN[18]" }, },
{ .pin = "EINT16_AUXIN4", .pad = "AB3",
.drv_grp = "GPIO_10", .chip = "mt8135",
.modes = { "GPIO104", "EINT16", NULL, NULL,
NULL, "USB_TEST_IO[18]", "TESTB_OUT18", "A_FUNC_DIN[19]" }, },
{ .pin = "I2S_CLK", .pad = "W6",
.drv_grp = "PCM1", .chip = "mt8135",
.modes = { "GPIO105", "I2SIN_CK", "EINT10", "DAC_CK",
"PCM1_CK", "USB_TEST_IO[19]", "TESTB_OUT19", "A_FUNC_DIN[20]" }, },
{ .pin = "I2S_WS", .pad = "AA6",
.drv_grp = "PCM1", .chip = "mt8135",
.modes = { "GPIO106", "I2SIN_WS", "EINT13", "DAC_WS",
"PCM1_WS", "USB_TEST_IO[20]", "TESTB_OUT20", "A_FUNC_DIN[21]" }, },
{ .pin = "I2S_DATA_IN", .pad = "AA5",
.drv_grp = "PCM1", .chip = "mt8135",
.modes = { "GPIO107", "I2SIN_DAT", "EINT11", NULL,
"PCM1_DI", "USB_TEST_IO[21]", "TESTB_OUT22", "A_FUNC_DIN[22]" }, },
{ .pin = "I2S_DATA_OUT", .pad = "AA4",
.drv_grp = "PCM1", .chip = "mt8135",
.modes = { "GPIO108", "I2SOUT_DAT", "EINT12", "DAC_DAT_OUT",
"PCM1_DO", "USB_TEST_IO[22]", "TESTB_OUT23", "A_FUNC_DIN[23]" }, },
{ .pin = "EINT5", .pad = "W5",
.drv_grp = "EINT5", .chip = "mt8135",
.modes = { "GPIO109", "EINT5", "PWM5", "CLKM3",
"GPU_JTRSTB", "USB_TEST_IO[23]", "TESTB_OUT26", "A_FUNC_DIN[24]" }, },
{ .pin = "EINT6", .pad = "V5",
.drv_grp = "EINT6", .chip = "mt8135",
.modes = { "GPIO110", "EINT6", "PWM6", "CLKM4",
"GPU_JTMS", "USB_TEST_IO[24]", "TESTB_OUT27", "A_FUNC_DIN[25]" }, },
{ .pin = "EINT7", .pad = "W3",
.drv_grp = "EINT7", .chip = "mt8135",
.modes = { "GPIO111", "EINT7", "PWM7", "CLKM5",
"GPU_JTDO", "USB_TEST_IO[25]", "TESTB_OUT28", "A_FUNC_DIN[26]" }, },
{ .pin = "EINT8", .pad = "V6",
.drv_grp = "EINT8", .chip = "mt8135",
.modes = { "GPIO112", "EINT8", "DISP_PWM", "CLKM6",
"GPU_JTDI", "USB_TEST_IO[26]", "TESTB_OUT29", "EXT_FRAME_SYNC" }, },
{ .pin = "EINT9", .pad = "W8",
.drv_grp = "EINT9", .chip = "mt8135",
.modes = { "GPIO113", "EINT9", NULL, NULL,
"GPU_JTCK", "USB_DRVVBUS", "TESTB_OUT30", "A_FUNC_DIN[27]" }, },
{ .pin = "LPCE1B", .pad = "W4",
.drv_grp = "LCD_2", .chip = "mt8135",
.modes = { "GPIO114", "LPCE1B", "EINT127", NULL,
NULL, "PWM2", "TESTB_OUT14", "A_FUNC_DIN[28]" }, },
{ .pin = "LPCE0B", .pad = "T5",
.drv_grp = "LCD_3", .chip = "mt8135",
.modes = { "GPIO115", "LPCE0B", "EINT126", NULL,
NULL, "PWM1", "TESTB_OUT15", "A_FUNC_DIN[29]" }, },
{ .pin = "DISP_PWM", .pad = "V4",
.drv_grp = "SLCD_5", .chip = "mt8135",
.modes = { "GPIO116", "DISP_PWM", "EINT77", "LSDI",
"PWM1", "PWM2", NULL, "PWM3" }, },
{ .pin = "EINT1", .pad = "T6",
.drv_grp = "EINT1", .chip = "mt8135",
.modes = { "GPIO117", "EINT1", "PWM2", "CLKM1",
NULL, "USB_TEST_IO[13]", NULL, "USB_SDA" }, },
{ .pin = "EINT2", .pad = "T4",
.drv_grp = "EINT2", .chip = "mt8135",
.modes = { "GPIO118", "EINT2", "PWM3", "CLKM2",
NULL, "USB_TEST_IO[14]", "SRCLKENAI2", "A_FUNC_DIN[30]" }, },
{ .pin = "EINT3", .pad = "R4",
.drv_grp = "EINT3", .chip = "mt8135",
.modes = { "GPIO119", "EINT3", NULL, NULL,
NULL, "USB_TEST_IO[15]", "SRCLKENAI1", "EXT_26M_CK" }, },
{ .pin = "EINT4", .pad = "R5",
.drv_grp = "EINT4", .chip = "mt8135",
.modes = { "GPIO120", "EINT4", "PWM4", NULL,
NULL, "USB_DRVVBUS", NULL, "A_FUNC_DIN[31]" }, },
{ .pin = "DPIDE", .pad = NULL,
.drv_grp = "DPI", .chip = "mt8135",
.modes = { "GPIO121", "DPI0_DE", "EINT100", "I2SOUT_DAT",
"DAC_DAT_OUT", "PCM1_DO", "IRDA_TXD", NULL }, },
{ .pin = "DPICK", .pad = NULL,
.drv_grp = "DPI", .chip = "mt8135",
.modes = { "GPIO122", "DPI0_CK", "EINT101", "I2SIN_DAT",
NULL, "PCM1_DI", "IRDA_PDN", NULL }, },
{ .pin = "DPIG4", .pad = NULL,
.drv_grp = "DPI1", .chip = "mt8135",
.modes = { "GPIO123", "DPI0_G4", "EINT114", NULL,
"CM2DAT_2X[0]", "DSP2_ID", NULL, NULL }, },
{ .pin = "DPIG5", .pad = NULL,
.drv_grp = "DPI1", .chip = "mt8135",
.modes = { "GPIO124", "DPI0_G5", "EINT115", NULL,
"CM2DAT_2X[1]", "DSP2_ICK", NULL, NULL }, },
{ .pin = "DPIR3", .pad = NULL,
.drv_grp = "DPI2", .chip = "mt8135",
.modes = { "GPIO125", "DPI0_R3", "EINT121", NULL,
"CM2DAT_2X[7]", NULL, NULL, NULL }, },
{ .pin = "DPIG1", .pad = NULL,
.drv_grp = "DPI1", .chip = "mt8135",
.modes = { "GPIO126", "DPI0_G1", "EINT111", NULL,
NULL, "DSP1_ICK", NULL, NULL }, },
{ .pin = "DPIVSYNC", .pad = NULL,
.drv_grp = "DPI", .chip = "mt8135",
.modes = { "GPIO127", "DPI0_VSYNC", "EINT98", "I2SIN_CK",
"DAC_CK", "PCM1_CK", NULL, NULL }, },
{ .pin = "DPIHSYNC", .pad = NULL,
.drv_grp = "DPI", .chip = "mt8135",
.modes = { "GPIO128", "DPI0_HSYNC", "EINT99", "I2SIN_WS",
"DAC_WS", "PCM1_WS", "IRDA_RXD", NULL }, },
{ .pin = "DPIB0", .pad = NULL,
.drv_grp = "DPI0", .chip = "mt8135",
.modes = { "GPIO129", "DPI0_B0", "EINT102", NULL,
"SCL0", "DISP_PWM", NULL, NULL }, },
{ .pin = "DPIB1", .pad = NULL,
.drv_grp = "DPI0", .chip = "mt8135",
.modes = { "GPIO130", "DPI0_B1", "EINT103", "CLKM0",
"SDA0", "PWM1", NULL, NULL }, },
{ .pin = "DPIB2", .pad = NULL,
.drv_grp = "DPI0", .chip = "mt8135",
.modes = { "GPIO131", "DPI0_B2", "EINT104", "CLKM1",
"SCL1", "PWM2", NULL, NULL }, },
{ .pin = "DPIB3", .pad = NULL,
.drv_grp = "DPI0", .chip = "mt8135",
.modes = { "GPIO132", "DPI0_B3", "EINT105", "CLKM2",
"SDA1", "PWM3", NULL, NULL }, },
{ .pin = "DPIB4", .pad = NULL,
.drv_grp = "DPI0", .chip = "mt8135",
.modes = { "GPIO133", "DPI0_B4", "EINT106", "CLKM3",
"SCL2", "PWM4", NULL, NULL }, },
{ .pin = "DPIB5", .pad = NULL,
.drv_grp = "DPI0", .chip = "mt8135",
.modes = { "GPIO134", "DPI0_B5", "EINT107", "CLKM4",
"SDA2", "PWM5", NULL, NULL }, },
{ .pin = "DPIB6", .pad = NULL,
.drv_grp = "DPI0", .chip = "mt8135",
.modes = { "GPIO135", "DPI0_B6", "EINT108", "CLKM5",
"SCL3", "PWM6", NULL, NULL }, },
{ .pin = "DPIB7", .pad = NULL,
.drv_grp = "DPI0", .chip = "mt8135",
.modes = { "GPIO136", "DPI0_B7", "EINT109", "CLKM6",
"SDA3", "PWM7", NULL, NULL }, },
{ .pin = "DPIG0", .pad = NULL,
.drv_grp = "DPI1", .chip = "mt8135",
.modes = { "GPIO137", "DPI0_G0", "EINT110", NULL,
NULL, "DSP1_ID", NULL, NULL }, },
{ .pin = "DPIG2", .pad = NULL,
.drv_grp = "DPI1", .chip = "mt8135",
.modes = { "GPIO138", "DPI0_G2", "EINT112", NULL,
NULL, "DSP1_IMS", NULL, NULL }, },
{ .pin = "DPIG3", .pad = NULL,
.drv_grp = "DPI1", .chip = "mt8135",
.modes = { "GPIO139", "DPI0_G3", "EINT113", NULL,
NULL, "DSP2_IMS", NULL, NULL }, },
{ .pin = "DPIG6", .pad = NULL,
.drv_grp = "DPI1", .chip = "mt8135",
.modes = { "GPIO140", "DPI0_G6", "EINT116", NULL,
"CM2DAT_2X[2]", NULL, NULL, NULL }, },
{ .pin = "DPIG7", .pad = NULL,
.drv_grp = "DPI1", .chip = "mt8135",
.modes = { "GPIO141", "DPI0_G7", "EINT117", NULL,
"CM2DAT_2X[3]", NULL, NULL, NULL }, },
{ .pin = "DPIR0", .pad = NULL,
.drv_grp = "DPI2", .chip = "mt8135",
.modes = { "GPIO142", "DPI0_R0", "EINT118", NULL,
"CM2DAT_2X[4]", NULL, NULL, NULL }, },
{ .pin = "DPIR1", .pad = NULL,
.drv_grp = "DPI2", .chip = "mt8135",
.modes = { "GPIO143", "DPI0_R1", "EINT119", NULL,
"CM2DAT_2X[5]", NULL, NULL, NULL }, },
{ .pin = "DPIR2", .pad = NULL,
.drv_grp = "DPI2", .chip = "mt8135",
.modes = { "GPIO144", "DPI0_R2", "EINT120", NULL,
"CM2DAT_2X[6]", NULL, NULL, NULL }, },
{ .pin = "DPIR4", .pad = NULL,
.drv_grp = "DPI2", .chip = "mt8135",
.modes = { "GPIO145", "DPI0_R4", "EINT122", NULL,
"CM2DAT_2X[8]", NULL, NULL, NULL }, },
{ .pin = "DPIR5", .pad = NULL,
.drv_grp = "DPI2", .chip = "mt8135",
.modes = { "GPIO146", "DPI0_R5", "EINT123", NULL,
"CM2DAT_2X[9]", NULL, NULL, NULL }, },
{ .pin = "DPIR6", .pad = NULL,
.drv_grp = "DPI2", .chip = "mt8135",
.modes = { "GPIO147", "DPI0_R6", "EINT124", NULL,
"CM2VSYNC_2X", NULL, NULL, NULL }, },
{ .pin = "DPIR7", .pad = NULL,
.drv_grp = "DPI2", .chip = "mt8135",
.modes = { "GPIO148", "DPI0_R7", "EINT125", NULL,
"CM2HSYNC_2X", NULL, NULL, NULL }, },
{ .pin = "TDN3/LVDS(TDN3)", .pad = "AA2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO149", NULL, "EINT36", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "TDP3/LVDS(TDP3)", .pad = "AA1",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO150", NULL, "EINT35", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "TDN2/LVDS(TCN)", .pad = "Y2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO151", NULL, "EINT169", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "TDP2/LVDS(TCP)", .pad = "Y1",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO152", NULL, "EINT168", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "TCN/LVDS(TDN2)", .pad = "W2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO153", NULL, "EINT163", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "TCP/LVDS(TDP2)", .pad = "W1",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO154", NULL, "EINT162", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "TDN1/LVDS(TDN1)", .pad = "V3",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO155", NULL, "EINT167", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "TDP1/LVDS(TDP1)", .pad = "V2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO156", NULL, "EINT166", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "TDN0/LVDS(TDN0)", .pad = "U3",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO157", NULL, "EINT165", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "TDP0/LVDS(TDP0)", .pad = "U2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO158", NULL, "EINT164", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDN3", .pad = "N5",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO159", NULL, "EINT18", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDP3", .pad = "N4",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO160", NULL, "EINT30", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDN2", .pad = "T2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO161", NULL, "EINT31", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDP2", .pad = "T3",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO162", NULL, "EINT32", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RCN", .pad = "P2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO163", NULL, "EINT33", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RCP", .pad = "P3",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO164", NULL, "EINT39", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDN1", .pad = "R3",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO165", NULL, NULL, NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDP1", .pad = "R2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO166", NULL, NULL, NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDN0", .pad = "N3",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO167", NULL, NULL, NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDP0", .pad = "N2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO168", NULL, NULL, NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDN1_A", .pad = "M4",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO169", "CMDAT6", "EINT175", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDP1_A", .pad = "M3",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO170", "CMDAT7", "EINT174", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RCN_A", .pad = "L3",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO171", "CMDAT8", "EINT171", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RCP_A", .pad = "L2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO172", "CMDAT9", "EINT170", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDN0_A", .pad = "M2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO173", "CMHSYNC", "EINT173", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDP0_A", .pad = "M1",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO174", "CMVSYNC", "EINT172", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDN1_B", .pad = "H2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO175", "CMDAT2", "EINT181", "CMCSD2",
NULL, NULL, NULL, NULL }, },
{ .pin = "RDP1_B", .pad = "H1",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO176", "CMDAT3", "EINT180", "CMCSD3",
NULL, NULL, NULL, NULL }, },
{ .pin = "RCN_B", .pad = "K3",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO177", "CMDAT4", "EINT177", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RCP_B", .pad = "K2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO178", "CMDAT5", "EINT176", NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "RDN0_B", .pad = "J3",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO179", "CMDAT0", "EINT179", "CMCSD0",
NULL, NULL, NULL, NULL }, },
{ .pin = "RDP0_B", .pad = "J2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO180", "CMDAT1", "EINT178", "CMCSD1",
NULL, NULL, NULL, NULL }, },
{ .pin = "CMPCLK", .pad = "K4",
.drv_grp = "CMPCLK", .chip = "mt8135",
.modes = { "GPIO181", "CMPCLK", "EINT182", "CMCSK",
"CM2MCLK_4X", "TS_AUXADC_SEL[3]", "VENC_TEST_CK", "TESTA_OUT27" }, },
{ .pin = "CMMCLK", .pad = "J5",
.drv_grp = "CMMCLK", .chip = "mt8135",
.modes = { "GPIO182", "CMMCLK", "EINT183", NULL,
NULL, "TS_AUXADC_SEL[2]", NULL, "TESTA_OUT28" }, },
{ .pin = "CMRST", .pad = "J6",
.drv_grp = "CAMRST", .chip = "mt8135",
.modes = { "GPIO183", "CMRST", "EINT185", NULL,
NULL, "TS_AUXADC_SEL[1]", NULL, "TESTA_OUT30" }, },
{ .pin = "CMPDN", .pad = "J4",
.drv_grp = "CAMPDN", .chip = "mt8135",
.modes = { "GPIO184", "CMPDN", "EINT184", NULL,
NULL, "TS_AUXADC_SEL[0]", NULL, "TESTA_OUT29" }, },
{ .pin = "CMFLASH", .pad = "G4",
.drv_grp = "CAMFLASH", .chip = "mt8135",
.modes = { "GPIO185", "CMFLASH", "EINT186", "CM2MCLK_3X",
NULL, NULL, "MFG_TEST_CK_1", "TESTA_OUT31" }, },
{ .pin = "MRG_I2S_PCM_CLK", .pad = "F5",
.drv_grp = "PCM0", .chip = "mt8135",
.modes = { "GPIO186", "MRG_I2S_PCM_CLK", "EINT14", "I2SIN_CK",
"PCM0_CK", "DSP2_ICK", "IMG_TEST_CK", "USB_SCL" }, },
{ .pin = "MRG_I2S_PCM_SYNC", .pad = "G6",
.drv_grp = "PCM0", .chip = "mt8135",
.modes = { "GPIO187", "MRG_I2S_PCM_SYNC", "EINT16", "I2SIN_WS",
"PCM0_WS", NULL, "DISP_TEST_CK", NULL }, },
{ .pin = "MRG_I2S_PCM_RX", .pad = "G3",
.drv_grp = "PCM0", .chip = "mt8135",
.modes = { "GPIO188", "MRG_I2S_PCM_RX", "EINT15", "I2SIN_DAT",
"PCM0_DI", "DSP2_ID", "MFG_TEST_CK", "USB_SDA" }, },
{ .pin = "MRG_I2S_PCM_TX", .pad = "G5",
.drv_grp = "PCM0", .chip = "mt8135",
.modes = { "GPIO189", "MRG_I2S_PCM_TX", "EINT17", "I2SOUT_DAT",
"PCM0_DO", NULL, "VDEC_TEST_CK", NULL }, },
{ .pin = "SRCLKENAI", .pad = "K5",
.drv_grp = "GPIO_11", .chip = "mt8135",
.modes = { "GPIO190", "SRCLKENAI", NULL, NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "URXD3", .pad = "C3",
.drv_grp = "UR3_0", .chip = "mt8135",
.modes = { "GPIO191", "URXD3", "EINT87", "UTXD3",
NULL, "TS_AUX_ST", "PWM4", NULL }, },
{ .pin = "UTXD3", .pad = "B2",
.drv_grp = "UR3_1", .chip = "mt8135",
.modes = { "GPIO192", "UTXD3", "EINT86", "URXD3",
NULL, "TS_AUX_CS_B", "PWM3", NULL }, },
{ .pin = "SDA2", .pad = "G2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO193", "SDA2", "EINT95", "CLKM5",
"PWM5", "TS_AUX_PWDB", NULL, NULL }, },
{ .pin = "SCL2", .pad = "F4",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO194", "SCL2", "EINT94", "CLKM4",
"PWM4", "TS_AUXADC_TEST_CK", NULL, NULL }, },
{ .pin = "SDA1", .pad = "F2",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO195", "SDA1", "EINT93", "CLKM3",
"PWM3", "TS_AUX_SCLK_PWDB", NULL, NULL }, },
{ .pin = "SCL1", .pad = "F3",
.drv_grp = NULL, .chip = "mt8135",
.modes = { "GPIO196", "SCL1", "EINT92", "CLKM2",
"PWM2", "TS_AUX_DIN", NULL, NULL }, },
{ .pin = "MSDC3_DAT2", .pad = "E1",
.drv_grp = "MSDC3", .chip = "mt8135",
.modes = { "GPIO197", "MSDC3_DAT2", "EINT71", "SCL6",
"PWM5", "CLKM4", "MFG_TEST_CK_2", NULL }, },
{ .pin = "MSDC3_DAT3", .pad = "C2",
.drv_grp = "MSDC3", .chip = "mt8135",
.modes = { "GPIO198", "MSDC3_DAT3", "EINT72", "SDA6",
"PWM6", "CLKM5", "MFG_TEST_CK_3", NULL }, },
{ .pin = "MSDC3_CMD", .pad = "D2",
.drv_grp = "MSDC3CM", .chip = "mt8135",
.modes = { "GPIO199", "MSDC3_CMD", "EINT68", "SDA2",
"PWM2", "CLKM1", "MFG_TEST_CK_4", NULL }, },
{ .pin = "MSDC3_CLK", .pad = "E2",
.drv_grp = "MSDC3CK", .chip = "mt8135",
.modes = { "GPIO200", "MSDC3_CLK", "EINT67", "SCL2",
"PWM1", "CLKM0", NULL, NULL }, },
{ .pin = "MSDC3_DAT1", .pad = "D3",
.drv_grp = "MSDC3", .chip = "mt8135",
.modes = { "GPIO201", "MSDC3_DAT1", "EINT70", "SDA3",
"PWM4", "CLKM3", NULL, NULL }, },
{ .pin = "MSDC3_DAT0", .pad = "E3",
.drv_grp = "MSDC3", .chip = "mt8135",
.modes = { "GPIO202", "MSDC3_DAT0", "EINT69", "SCL3",
"PWM3", "CLKM2", NULL, NULL }, },
{ .pin = "INT", .pad = "N2",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO0", "INT", NULL, NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "SRCVOLTEN", .pad = "M4",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO1", "SRCVOLTEN", NULL, NULL,
NULL, NULL, "TEST_CK1", NULL }, },
{ .pin = "SRCLKEN_PERI", .pad = "M2",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO2", "SRCLKEN_PERI", NULL, NULL,
NULL, NULL, "TEST_CK2", NULL }, },
{ .pin = "RTC_32K1V8", .pad = "K3",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO3", "RTC_32K1V8", NULL, NULL,
NULL, NULL, "TEST_CK3", NULL }, },
{ .pin = "WRAP_EVENT", .pad = "J2",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO4", "WRAP_EVENT", NULL, NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "SPI_CLK", .pad = "L4",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO5", "SPI_CLK", NULL, NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "SPI_CSN", .pad = "J3",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO6", "SPI_CSN", NULL, NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "SPI_MOSI", .pad = "J1",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO7", "SPI_MOSI", NULL, NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "SPI_MISO", .pad = "L3",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO8", "SPI_MISO", NULL, NULL,
NULL, NULL, NULL, NULL }, },
{ .pin = "AUD_CLK_MOSI", .pad = "H2",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO9", "AUD_CLK", NULL, NULL,
NULL, NULL, "TEST_IN0", "TEST_OUT0" }, },
{ .pin = "AUD_DAT_MISO", .pad = "H3",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO10", "AUD_MISO", NULL, NULL,
NULL, NULL, "TEST_IN1", "TEST_OUT1" }, },
{ .pin = "AUD_DAT_MOSI", .pad = "H1",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO11", "AUD_MOSI", NULL, NULL,
NULL, NULL, "TEST_IN2", "TEST_OUT2" }, },
{ .pin = "COL0", .pad = "F3",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO12", "COL0_USBDL", "EINT10_1X", "PWM1_3X",
NULL, NULL, "TEST_IN3", "TEST_OUT3" }, },
{ .pin = "COL1", .pad = "G8",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO13", "COL1", "EINT11_1X", "SCL0_2X",
NULL, NULL, "TEST_IN4", "TEST_OUT4" }, },
{ .pin = "COL2", .pad = "H4",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO14", "COL2", "EINT12_1X", "SDA0_2X",
NULL, NULL, "TEST_IN5", "TEST_OUT5" }, },
{ .pin = "COL3", .pad = "G2",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO15", "COL3", "EINT13_1X", "SCL1_2X",
NULL, NULL, "TEST_IN6", "TEST_OUT6" }, },
{ .pin = "COL4", .pad = "F2",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO16", "COL4", "EINT14_1X", "SDA1_2X",
NULL, NULL, "TEST_IN7", "TEST_OUT7" }, },
{ .pin = "COL5", .pad = "G7",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO17", "COL5", "EINT15_1X", "SCL2_2X",
NULL, NULL, "TEST_IN8", "TEST_OUT8" }, },
{ .pin = "COL6", .pad = "J6",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO18", "COL6", "EINT16_1X", "SDA2_2X",
"GPIO32K_0", "GPIO26M_0", "TEST_IN9", "TEST_OUT9" }, },
{ .pin = "COL7", .pad = "J5",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO19", "COL7", "EINT17_1X", "PWM2_3X",
"GPIO32K_1", "GPIO26M_1", "TEST_IN10", "TEST_OUT10" }, },
{ .pin = "ROW0", .pad = "L7",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO20", "ROW0", "EINT18_1X", "SCL0_3X",
NULL, NULL, "TEST_IN11", "TEST_OUT11" }, },
{ .pin = "ROW1", .pad = "P1",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO21", "ROW1", "EINT19_1X", "SDA0_3X",
"AUD_TSTCK", NULL, "TEST_IN12", "TEST_OUT12" }, },
{ .pin = "ROW2", .pad = "J8",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO22", "ROW2", "EINT20_1X", "SCL1_3X",
NULL, NULL, "TEST_IN13", "TEST_OUT13" }, },
{ .pin = "ROW3", .pad = "J7",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO23", "ROW3", "EINT21_1X", "SDA1_3X",
NULL, NULL, "TEST_IN14", "TEST_OUT14" }, },
{ .pin = "ROW4", .pad = "L5",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO24", "ROW4", "EINT22_1X", "SCL2_3X",
NULL, NULL, "TEST_IN15", "TEST_OUT15" }, },
{ .pin = "ROW5", .pad = "N6",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO25", "ROW5", "EINT23_1X", "SDA2_3X",
NULL, NULL, "TEST_IN16", "TEST_OUT16" }, },
{ .pin = "ROW6", .pad = "L6",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO26", "ROW6", "EINT24_1X", "PWM3_3X",
"GPIO32K_2", "GPIO26M_2", "TEST_IN17", "TEST_OUT17" }, },
{ .pin = "ROW7", .pad = "P2",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO27", "ROW7", "EINT3_1X", "CBUS",
"GPIO32K_3", "GPIO26M_3", "TEST_IN18", "TEST_OUT18" }, },
{ .pin = "PWM1(VMSEL1)", .pad = "J4",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO28", "PWM1", "EINT4_1X", NULL,
"GPIO32K_4", "GPIO26M_4", "TEST_IN19", "TEST_OUT19" }, },
{ .pin = "PWM2(VMSEL2)", .pad = "N5",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO29", "PWM2", "EINT5_1X", NULL,
"GPIO32K_5", "GPIO26M_5", "TEST_IN20", "TEST_OUT20" }, },
{ .pin = "PWM3(PWM)", .pad = "R3",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO30", "PWM3", "EINT6_1X", "COL0",
"GPIO32K_6", "GPIO26M_6", "TEST_IN21", "TEST_OUT21" }, },
{ .pin = "SCL0", .pad = "N1",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO31", "SCL0", "EINT7_1X", "PWM1_2X",
NULL, NULL, "TEST_IN22", "TEST_OUT22" }, },
{ .pin = "SDA0", .pad = "N3",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO32", "SDA0", "EINT8_1X", "Z`",
NULL, NULL, "TEST_IN23", "TEST_OUT23" }, },
{ .pin = "SCL1", .pad = "T1",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO33", "SCL1", "EINT9_1X", "PWM2_2X",
NULL, NULL, "TEST_IN24", "TEST_OUT24" }, },
{ .pin = "SDA1", .pad = "T2",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO34", "SDA1", "EINT0_1X", NULL,
NULL, NULL, "TEST_IN25", "TEST_OUT25" }, },
{ .pin = "SCL2", .pad = "T3",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO35", "SCL2", "EINT1_1X", "PWM3_2X",
NULL, NULL, "TEST_IN26", "TEST_OUT26" }, },
{ .pin = "SDA2", .pad = "U2",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO36", "SDA2", "EINT2_1X", NULL,
NULL, NULL, "TEST_IN27", "TEST_OUT27" }, },
{ .pin = "HDMISD", .pad = "H6",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO37", "HDMISD", NULL, NULL,
NULL, NULL, "TEST_IN28", "TEST_OUT28" }, },
{ .pin = "HDMISCK", .pad = "H5",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO38", "HDMISCK", NULL, NULL,
NULL, NULL, "TEST_IN29", "TEST_OUT29" }, },
{ .pin = "HTPLG", .pad = "H7",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO39", "HTPLG", NULL, NULL,
NULL, NULL, "TEST_IN30", "TEST_OUT30" }, },
{ .pin = "CEC", .pad = "J9",
.drv_grp = NULL, .chip = "mt6397",
.modes = { "GPIO40", "CEC", NULL, NULL,
NULL, NULL, "TEST_IN31", "TEST_OUT31" }, },
};
static const struct mt_pin_drv_cls mt_pin_drv_cls_tbl[] = {
{ .name = "cls_4_32_8", .vals_ma = { 4, 8, 12, 16, 20, 24, 28, 32 } },
{ .name = "cls_2_16_8", .vals_ma = { 2, 4, 6, 8, 10, 12, 14, 16 } },
{ .name = "cls_2_8_4", .vals_ma = { 2, 4, 6, 8, 0, 0, 0, 0 } },
{ .name = "cls_4_16_4", .vals_ma = { 4, 0, 8, 0, 12, 0, 16, 0 } },
};
static const struct mt_pin_drv_grp_desc mt_pin_drv_grp_tbl[] = {
{ .name = "UR1_2", .drv_cls = "cls_4_16_4",
	.port = 4, .offset = 4, .type = 1, },
{ .name = "UR1_3", .drv_cls = "cls_4_16_4",
	.port = 4, .offset = 8, .type = 1, },
{ .name = "NLD_0", .drv_cls = "cls_4_16_4",
	.port = 0, .offset = 16, .type = 0, },
{ .name = "NLD_1", .drv_cls = "cls_4_16_4",
	.port = 0, .offset = 20, .type = 0, },
{ .name = "MSDC3CK", .drv_cls = "cls_2_16_8",
	.port = 11, .offset = 24, .type = 0, },
{ .name = "CMPCLK", .drv_cls = "cls_4_16_4",
	.port = 10, .offset = 12, .type = 0, },
{ .name = "MSDC0RSTB", .drv_cls = "cls_4_16_4",
	.port = 0, .offset = 24, .type = 0, },
{ .name = "PCM0", .drv_cls = "cls_2_8_4",
	.port = 11, .offset = 0, .type = 0, },
{ .name = "PCM1", .drv_cls = "cls_4_16_4",
	.port = 7, .offset = 4, .type = 1, },
{ .name = "DPI0", .drv_cls = "cls_4_16_4",
	.port = 8, .offset = 28, .type = 1, },
{ .name = "UR1_0", .drv_cls = "cls_4_16_4",
	.port = 3, .offset = 28, .type = 1, },
{ .name = "CAMFLASH", .drv_cls = "cls_4_16_4",
	.port = 10, .offset = 28, .type = 0, },
{ .name = "UR1_1", .drv_cls = "cls_4_16_4",
	.port = 4, .offset = 0, .type = 1, },
{ .name = "MSDC1CK", .drv_cls = "cls_4_32_8",
	.port = 5, .offset = 16, .type = 1, },
{ .name = "DPI", .drv_cls = "cls_4_16_4",
	.port = 8, .offset = 24, .type = 1, },
{ .name = "MSDC0CM", .drv_cls = "cls_2_16_8",
	.port = 0, .offset = 4, .type = 0, },
{ .name = "MSDC2INSI", .drv_cls = "cls_4_16_4",
	.port = 3, .offset = 12, .type = 1, },
{ .name = "MSDC0CK", .drv_cls = "cls_2_16_8",
	.port = 0, .offset = 8, .type = 0, },
{ .name = "JTAG", .drv_cls = "cls_4_16_4",
	.port = 3, .offset = 0, .type = 1, },
{ .name = "DPI2", .drv_cls = "cls_4_16_4",
	.port = 9, .offset = 4, .type = 1, },
{ .name = "SPI0", .drv_cls = "cls_4_16_4",
	.port = 1, .offset = 28, .type = 1, },
{ .name = "MSDC1SDWPI", .drv_cls = "cls_4_16_4",
	.port = 3, .offset = 8, .type = 1, },
{ .name = "MSDC2CM", .drv_cls = "cls_4_32_8",
	.port = 5, .offset = 0, .type = 1, },
{ .name = "UR4_1", .drv_cls = "cls_4_16_4",
	.port = 3, .offset = 24, .type = 1, },
{ .name = "DAC", .drv_cls = "cls_4_16_4",
	.port = 1, .offset = 24, .type = 1, },
{ .name = "CMMCLK", .drv_cls = "cls_4_16_4",
	.port = 10, .offset = 16, .type = 0, },
{ .name = "EINT7", .drv_cls = "cls_2_8_4",
	.port = 7, .offset = 16, .type = 1, },
{ .name = "EINT5", .drv_cls = "cls_2_8_4",
	.port = 7, .offset = 8, .type = 1, },
{ .name = "EINT4", .drv_cls = "cls_2_8_4",
	.port = 8, .offset = 20, .type = 1, },
{ .name = "MSDC2SDWPI", .drv_cls = "cls_4_16_4",
	.port = 3, .offset = 16, .type = 1, },
{ .name = "EINT6", .drv_cls = "cls_2_8_4",
	.port = 7, .offset = 12, .type = 1, },
{ .name = "MSDC1INSI", .drv_cls = "cls_4_16_4",
	.port = 3, .offset = 4, .type = 1, },
{ .name = "UR2_0", .drv_cls = "cls_4_16_4",
	.port = 2, .offset = 16, .type = 1, },
{ .name = "UR2_3", .drv_cls = "cls_4_16_4",
	.port = 2, .offset = 28, .type = 1, },
{ .name = "UR2_2", .drv_cls = "cls_4_16_4",
	.port = 2, .offset = 24, .type = 1, },
{ .name = "MSDC4CK", .drv_cls = "cls_2_16_8",
	.port = 11, .offset = 28, .type = 0, },
{ .name = "UR2_1", .drv_cls = "cls_4_16_4",
	.port = 2, .offset = 20, .type = 1, },
{ .name = "EINT9", .drv_cls = "cls_2_8_4",
	.port = 7, .offset = 24, .type = 1, },
{ .name = "EINT8", .drv_cls = "cls_2_8_4",
	.port = 7, .offset = 20, .type = 1, },
{ .name = "EINT0", .drv_cls = "cls_2_8_4",
	.port = 2, .offset = 12, .type = 1, },
{ .name = "MSDC3CM", .drv_cls = "cls_2_16_8",
	.port = 11, .offset = 20, .type = 0, },
{ .name = "CAMPDN", .drv_cls = "cls_4_16_4",
	.port = 10, .offset = 24, .type = 0, },
{ .name = "EINT1", .drv_cls = "cls_2_8_4",
	.port = 8, .offset = 8, .type = 1, },
{ .name = "EINT2", .drv_cls = "cls_2_8_4",
	.port = 8, .offset = 12, .type = 1, },
{ .name = "GPIO_10", .drv_cls = "cls_4_16_4",
	.port = 7, .offset = 0, .type = 1, },
{ .name = "MSDC2CK", .drv_cls = "cls_4_32_8",
	.port = 5, .offset = 4, .type = 1, },
{ .name = "NFI", .drv_cls = "cls_4_16_4",
	.port = 0, .offset = 12, .type = 0, },
{ .name = "EINT3", .drv_cls = "cls_2_8_4",
	.port = 8, .offset = 16, .type = 1, },
{ .name = "LCD_0", .drv_cls = "cls_2_16_8",
	.port = 6, .offset = 12, .type = 1, },
{ .name = "LCD_3", .drv_cls = "cls_2_8_4",
	.port = 8, .offset = 0, .type = 1, },
{ .name = "LCD_2", .drv_cls = "cls_2_8_4",
	.port = 7, .offset = 28, .type = 1, },
{ .name = "MSDC0", .drv_cls = "cls_2_16_8",
	.port = 0, .offset = 0, .type = 0, },
{ .name = "ADC", .drv_cls = "cls_4_16_4",
	.port = 1, .offset = 20, .type = 1, },
{ .name = "MSDC2", .drv_cls = "cls_4_32_8",
	.port = 4, .offset = 28, .type = 1, },
{ .name = "MSDC3", .drv_cls = "cls_2_16_8",
	.port = 11, .offset = 16, .type = 0, },
{ .name = "PWM4", .drv_cls = "cls_4_16_4",
	.port = 4, .offset = 24, .type = 1, },
{ .name = "DPI1", .drv_cls = "cls_4_16_4",
	.port = 9, .offset = 0, .type = 1, },
{ .name = "PWM1", .drv_cls = "cls_4_16_4",
	.port = 4, .offset = 12, .type = 1, },
{ .name = "PWM2", .drv_cls = "cls_4_16_4",
	.port = 4, .offset = 16, .type = 1, },
{ .name = "PWM3", .drv_cls = "cls_4_16_4",
	.port = 4, .offset = 20, .type = 1, },
{ .name = "GPIO_11", .drv_cls = "cls_4_16_4",
	.port = 11, .offset = 4, .type = 0, },
{ .name = "GPIO_8", .drv_cls = "cls_4_16_4",
	.port = 6, .offset = 24, .type = 1, },
{ .name = "GPIO_9", .drv_cls = "cls_4_16_4",
	.port = 6, .offset = 28, .type = 1, },
{ .name = "UR3_0", .drv_cls = "cls_4_16_4",
	.port = 11, .offset = 8, .type = 0, },
{ .name = "GPIO_4", .drv_cls = "cls_4_16_4",
	.port = 2, .offset = 8, .type = 1, },
{ .name = "UR4_0", .drv_cls = "cls_4_16_4",
	.port = 3, .offset = 20, .type = 1, },
{ .name = "GPIO_2", .drv_cls = "cls_4_16_4",
	.port = 2, .offset = 0, .type = 1, },
{ .name = "GPIO_3", .drv_cls = "cls_4_16_4",
	.port = 2, .offset = 4, .type = 1, },
{ .name = "CAMRST", .drv_cls = "cls_4_16_4",
	.port = 10, .offset = 20, .type = 0, },
{ .name = "GPIO_1", .drv_cls = "cls_2_8_4",
	.port = 1, .offset = 12, .type = 1, },
{ .name = "MSDC1CM", .drv_cls = "cls_4_32_8",
	.port = 5, .offset = 12, .type = 1, },
{ .name = "SLCD_3", .drv_cls = "cls_4_16_4",
	.port = 6, .offset = 20, .type = 1, },
{ .name = "SLCD_2", .drv_cls = "cls_2_16_8",
	.port = 6, .offset = 16, .type = 1, },
{ .name = "UR3_1", .drv_cls = "cls_4_16_4",
	.port = 11, .offset = 12, .type = 0, },
{ .name = "SLCD_5", .drv_cls = "cls_2_8_4",
	.port = 8, .offset = 4, .type = 1, },
{ .name = "MSDC1", .drv_cls = "cls_4_32_8",
	.port = 5, .offset = 8, .type = 1, },
};
