#obj-$(CONFIG_VIDEO_MEPSI_F) += floatlib.o drv_core.o drv_core_color.o drv_core_disp.o drv_driver.o drv_platform.o drv_port.o svc_api.o svc_context.o util_log.o util_vector.o
obj-$(CONFIG_ODIN_S3D) += formatter.o floatlib.o drv_core.o drv_core_color.o drv_core_disp.o drv_platform.o drv_port.o svc_api.o svc_context.o util_log.o
