#
# Makefile for Qualcomm MDM9K modem support.
#

GCOV_PROFILE := y

subdir-ccflags-y := -Werror

obj-$(CONFIG_QCOM_USB_MODEM_POWER) += qcom_usb_modem_power.o
obj-$(CONFIG_MSM_SUBSYSTEM_RESTART) += subsystem_notif.o
obj-$(CONFIG_MSM_SUBSYSTEM_RESTART) += subsystem_restart.o
obj-$(CONFIG_MSM_HSIC_SYSMON) += hsic_sysmon.o
obj-$(CONFIG_MSM_SYSMON_COMM) += sysmon.o
