/*
 * Generated by MTK SP DrvGen Version 03.13.1  for MT8135_NP. Copyright MediaTek Inc. (C) 2013.
 * Mon Sep  2 18:18:16 2013
 * Do Not Modify the File.
 */

#define MSDC_POWER_MC1     MSDC_VEMC_3V3
#define MSDC_POWER_MC2     MSDC_VMC
