# Makefile for the LDVT drivers for UVVTP

obj-y   += vdec/
obj-$(CONFIG_MTK_LDVT_PMIC)   += pmic/
obj-$(CONFIG_MTK_LDVT_PMIC_WARP)   += pmic_wrap/
obj-y   += hotplug/
#obj-y   += pwm/
#obj-y   += adc/
#obj-y   += mhltx/
#obj-y   += hdmitx/
